### ISSUE TITLE
Village recognized as suburb: Grzybowo near Kołobrzeg

### ISSUE THREAD

**Issue by esyscoder** [twain47/Nominatim#101]
In serach results it is returned with classification suburb which is wrong, it is independent village:
http://nominatim.openstreetmap.org/search.php?q=grzybowo%2C+ko%C5%82obrzeg&viewbox=15.43%2C54.18%2C15.55%2C54.14&polygon=1

**Comment by lonvia** [comment]
This is basically an issue of #213.
