### ISSUE TITLE
Ayuda con el reverse

### ISSUE THREAD

**Issue by maxicabanillas78** [twain47/Nominatim#128]
alguien me puede ayudar por favor
yo tengo un servidor de Rastramento veicular, instale sel servidor y el esta funcionado muy bien, pero estoy con un problema al pasar mas de una hora, mi sistema se para, por que mi servidor de mapa deja de enviar informacion a mi otro servidor rastramento Nominatim algo en algun lado que restige el envio de informacion pasado algunos hora

me pueden desir como sacar todo para que no restiga el envio de informacion

muchas gracias
maxi

**Comment by lonvia** [comment]
Closing because of language issues
