### ISSUE TITLE
support for names on junction=yes lacks

### ISSUE THREAD

**Issue by sommerluk** [twain47/Nominatim#137]
There is no support for junction=yes (http://wiki.openstreetmap.org/wiki/Key:junction) in Nominatim.

In some countries (e.g. Japan) crossroad names are important for the orientation (just like in most other countries the road names).

Nominatim should process the corresponding tags (name, alt_name, old_name ...) if junction=yes is present.

(At osm.org it is still not rendered, but a bug report for this is available. Support in Nominatim could be a first step.)

Example: node 2507603163

**Comment by lonvia** [comment]
Working now: http://nominatim.openstreetmap.org/search.php?q=Carrefour+Mouton

**Comment by sommerluk** [comment]
@lonvia Great work. Thanks a lot!
