### ISSUE TITLE
polygon_* and bounded are missing from reverse geo

### ISSUE THREAD

**Issue by soulraven** [twain47/Nominatim#138]
any ideea why polygon_* and bounded are missing from reverse geocoding searches?
i have try to modify the code, but i don't kno from where to start.

can provide a little more help?

**Comment by jeromegv** [comment]
:+1:

**Comment by lonvia** [comment]
More detailed description, what needs to be done (copied from mailing list here):
both search and reverse first find the correct result (the place_id in the placex table that contains all places known to Nominatim) and then collect the details for each result. Unfortunately, they use different functions to do this details lookup. 

For search you find it here:
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/Geocode.php#L366
and here (the part including polygon lookup)
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/Geocode.php#L1597

For reverse this code is used:
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/PlaceLookup.php

The simple solution would be to copy the polygon code over from search to reverse. The nice solution would be to unify these two parts of the code and make sure search uses PlaceLookup which then should be doing the fancy polygon stuff.

Once the lookup work, the output templates need to be adapted. Again, search provides the examples:
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/template/search-xml.php#L44
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/template/search-jsonv2.php#L56
https://github.com/twain47/Nominatim/blob/753227ae255cbd71015b042a41dc3cbbfb8f1904/lib/template/search-json.php#L57

And again, copying it over is the easy solution and factoring out the code would be the nice one.

**Comment by lonvia** [comment]
Implemented in #389.
