### ISSUE TITLE
Reverse geocoder nearest search issue

### ISSUE THREAD

**Issue by sofgarya** [twain47/Nominatim#143]
Taking reference from: https://help.openstreetmap.org/questions/31792/reverse-geocoder-nearest-search-issue

I'm trying to use that code, due to, when I use  http://nominatim.openstreetmap.org/search.php?q=50.8965%2C+4.4337&viewbox=4.45%2C50.92%2C4.47%2C50.9 and http://nominatim.openstreetmap.org/reverse.php?format=xml&lat=50.8965&lon=4.4337
but this point is over Woluwelaan, you can check it with the coordinates or with 
https://www.google.com/maps/place/50%C2%B053'47.4%22N+4%C2%B026'01.3%22E/@50.8968756,4.4313504,17z/data=!4m2!3m1!1s0x0:0x0 

So, I impemented it in the local nominatim but obtain the next one:

<reversegeocode timestamp="Wed, 04 Jun 14 14:50:24 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. &lt;a href=" http:="" www.openstreetmap.org="" copyright""="">http://www.openstreetmap.org/copyright" querystring="format=xml&lat=50.90921&lon=4.46187">
<error>Unable to geocode</error> 
</reversegeocode>

And I don't know if there is some change in PlaceLookup.php, or the changes are only in ReverseGeocode.php and reverse.php

I imagine that I need to make a change in /lib/template/address.php , but I'm not sure.

Has anyone tried to use this code? What am I doing wrong?

Thanks in advance!

**Comment by lonvia** [comment]
I suspect this question is outdated now.

See #512 for suggestions on how to improve reverse geocoding.
