### ISSUE TITLE
Return boundingbox on reverse geocoding

### ISSUE THREAD

**Issue by ghost** [twain47/Nominatim#150]
When reverse geocoding with Nominatim, it does not return "boundingbox" property.

Example on search: http://nominatim.openstreetmap.org/search?format=xml&addressdetails=1&limit=1&q=venice
Example on reverse geocoding: http://nominatim.openstreetmap.org/reverse?format=xml&addressdetails=1&&osm_type=R&osm_id=44741

**Comment by jk** [comment]
:+1: 

The same applies to all polygon_* things.

**Comment by lonvia** [comment]
Fixed in #389.
