### ISSUE TITLE
Multiple values for accept-language parameter

### ISSUE THREAD

**Issue by ramikay** [twain47/Nominatim#154]
This is a feature request. It would save multiple requests if a single /search or /reverse request can return the address in multiple languages when the value for the accept-language parameter holds multiple language codes. An example response would look something like this:

`..
"address": [
"en" : { ... },
"fr" : { ... },
"de": { ... }
]
...`

**Comment by lonvia** [comment]
The only way this use case makes sense is if you are bulk downloading data which is not what the API is for.
