### ISSUE TITLE
bridge:name and tunnel:name

### ISSUE THREAD

**Issue by jotpe** [twain47/Nominatim#157]
A way or railyway can contain multiple names. Espacially bridge:name or tunnel:name. 
This names can't be searched.

**Comment by lonvia** [comment]
Bridges and tunnels are now found only by bridge:name/tunnel:name (and the language variants), e.g. http://nominatim.openstreetmap.org/search.php?q=Pont+Matadi or http://nominatim.openstreetmap.org/search.php?q=matadi+bridge
