### ISSUE TITLE
Addresses should be matched on language variants not just on the name tag

### ISSUE THREAD

**Issue by simonpoole** [twain47/Nominatim#158]
Example of issue: http://nominatim.openstreetmap.org/search.php?q=Rue+de+Laeken+65&viewbox=4.34%2C50.86%2C4.36%2C50.85

The address is not found because in the addr:street tag dutch and french versiosn of the the street name are reversed relative to the name tag of the street. The language vaiants of the respective tags do however match up. Now the problem is rather simple to fix in the data, however it would be advantageous if nominatim could use the language variants for matching if it fails on the primary name/addr:street tag.

**Comment by lonvia** [comment]
I'm reluctant to do something about this because being more clever about the matching just hides more tagging errors, which in turn means that ever other data consumer needs to implement the same clever tricks as nominatim.

The simple rule here is that `addr:street` should match the `name` tag of the street exactly. Let's leave it at that.

**Comment by pyrog** [comment]
In Europe some country use 2 or more languages (Belgium, Switzerland…) and probably other countries in the world.

Example: In the city of Biel/Bienne in Switzerland, the french and the german languages are officially used.

* [Dammweg, Biel `DE`](http://www.openstreetmap.org/way/28031008)
* [Chemin du Terreau, Bienne `FR`](http://www.openstreetmap.org/way/28031008)

![biel-bienne](https://cloud.githubusercontent.com/assets/2158081/7462444/ca891cfa-f2b1-11e4-8a9d-6230305b36ac.png)

**Comment by lonvia** [comment]
addr:street is never used for such translations, it is just a link to the street it belongs to. Translation should be added to the street in the usual name:xx tags and are taken from there.
