### ISSUE TITLE
Unexpected results on less specific search queries with house number

### ISSUE THREAD

**Issue by tommedema** [twain47/Nominatim#160]
Steps to reproduce:

1. search for `melkweg 24 gronigen` (http://nominatim.openstreetmap.org/search.php?q=melkweg+24+groningen&viewbox=)
2. notice the result `24, Melkweg, Schildersbuurt, Groningen, Nederland, 9718ES, Nederland (House)`
3. repeat the query but less specific as `melkweg 24` (http://nominatim.openstreetmap.org/search.php?q=melkweg+24&viewbox=)
4. note that the same result with postcode `9718ES` is now only returned after pressing "search for more results" about 5 times, yet the results prior to that match the search query less because they do not specify the house number `24`, while the result of interest does

E.g. when searching for `melkweg 24` then `Melkweg, Bussum, Noord-Holland, Nederland, 1404DP, Nederland (Unclassified)` is returned prior to `24, Melkweg, Schildersbuurt, Groningen, Nederland, 9718ES, Nederland (House)`, which does not seem senseful to me, or am I missing something?

**Comment by lonvia** [comment]
This has been fixed in the meantime.
