### ISSUE TITLE
No results on exact match query with postcode

### ISSUE THREAD

**Issue by tommedema** [twain47/Nominatim#161]
Steps to reproduce:

1. search for `melkweg 24 groningen` (http://nominatim.openstreetmap.org/search.php?q=melkweg+24+groningen&viewbox=) and notice the result `24, Melkweg, Schildersbuurt, Groningen, Nederland, 9718ES, Nederland (House)`
2. repeat the search but now with the postcode, `melkweg 24 9718es groningen`, exactly as in the result: (http://nominatim.openstreetmap.org/search.php?q=melkweg+24+9718es+groningen&viewbox=)
3. notice how no results are returned, yet the search query is an exact match with the previous result
4. similarly, note that `melkweg 24 9718es` returns 0 results too

Why are there no results? This seems like a bug to me.

**Comment by lonvia** [comment]
Fixed in 2f8a29ba39e4ca995334f2702985afa761bfffbd
