### ISSUE TITLE
Search for "edinburgh restaurant" does not find all edinburgh restaurants

### ISSUE THREAD

**Issue by octosquid** [twain47/Nominatim#169]
On https://www.openstreetmap.org, I've searched for "edinburgh restaurant", and got a list of restaurants, but [this] (https://www.openstreetmap.org/node/1233436961) restaurant wasn't on the list (and I guess many others, too). Instead, [this](https://www.openstreetmap.org/node/1858008838) restaurant was, which is at the other end of the world, and not even has "edinburgh" in its name.

**Comment by mmd-osm** [comment]
> However I doubt that most users of OSM will take the time to look up the coords for the area they want to search for. There should be a more intuitive (and scalable) solution for this.

Do you know [overpass turbo wizard](http://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard)? A simple query with [`restaurant in Edinburgh`](http://overpass-turbo.eu/?w=restaurant in Edinburgh&R) will do. Looking up coords is not needed at all.

**Comment by octosquid** [comment]
nice, thanks. But still the bug affects the behaviour on the main site.

**Comment by lonvia** [comment]
overpass is the better tool for exhaustive poi search
