### ISSUE TITLE
Provide "website" tag if present

### ISSUE THREAD

**Issue by MKergall** [twain47/Nominatim#189]
The "website=*" tag is now frequently used in OSM features (http://wiki.openstreetmap.org/wiki/Key:website). 

It would be nice if it was made available in Nominatim results (as the image is). 

Use case: display this "more info" link in the results.

**Comment by farfromrefug** [comment]
I would love to see that feature. For me the most important one is opening_hours. But i think all extra tags should be exported.
I am also willing to help by implementing it but i am running on Mac OSX :s
Any news on the osx build?

Thanks

**Comment by mtmail** [comment]
You can develop on MacOS, see https://github.com/twain47/Nominatim/blob/master/VAGRANT.md The code is installed and executed in a local virtual machine but the editor is whatever editor you usually use on MacOS, e.g. textmate, sublime, atom etc.

**Comment by lonvia** [comment]
Feature now tracked in #304.

**Comment by farfromrefug** [comment]
I will look at it !
Thanks

**Comment by lonvia** [comment]
@farfromrefug In case you didn't see, this feature is implemented now, e.g. try http://nominatim.openstreetmap.org/search.php?q=musee+d%27orsay&extratags=1&format=xml and look at the first result.

**Comment by farfromrefug** [comment]
wow i didnt see that, you are awesome!!!!!!!!! thank you so much

**Comment by farfromrefug** [comment]
BTW : in JSON when extratags is empty it reports an array instead of an object

**Comment by lonvia** [comment]
Sigh, PHP arrays are a real pain. Fixed in 5c187182a3119640a65ed1545daef10c7f991f93 (and should be live in a few minutes). Let me know if there are other formatting problems but please be so kind and open a new issue for it. Make it easier to track.

**Comment by farfromrefug** [comment]
Thanks, sure i will ;) sorry!
