### ISSUE TITLE
Can't find towers by name

### ISSUE THREAD

**Issue by pyrog** [twain47/Nominatim#206]
Nominatim don't retrieve objects with only **man_made=tower** (+ __name=*__ ) tags…
* [Borbergturm](http://openstreetmap.org/node/192179581)

But could find **historic=tower** or **building=tower** (see #103)…
* [Limes Wachtposten 9/104](http://openstreetmap.org/node/35925003)
* [Xemeneia del Walden](http://openstreetmap.org/node/318796169)

Or find towers with __tourism=*__ tags
* [Hornisgrindeturm](http://openstreetmap.org/node/201685780)

**Comment by lonvia** [comment]
named man_made are now indexed, e.g. http://nominatim.openstreetmap.org/search.php?q=Borbergturm

**Comment by pyrog** [comment]
Thank you :smile:
