### ISSUE TITLE
Type of point of interest is YES

### ISSUE THREAD

**Issue by pyrog** [twain47/Nominatim#209]
See childs of:
* http://nominatim.openstreetmap.org/details.php?place_id=120271824
* http://nominatim.openstreetmap.org/details.php?place_id=128532610

They have tags like **building=yes**, **shop=yes**, **bridge=yes**

Could you use **Building** instead of **Yes** and so on ?

**Comment by pyrog** [comment]
Thank you Sarah :smile: 

I see a similar issue on the result list: [http://nominatim.openstreetmap.org/search.php?q=pont+de+la+guillotière+lyon](http://nominatim.openstreetmap.org/search.php?q=pont+de+la+guillotière+lyon&viewbox=4.81%2C45.77%2C4.87%2C45.74)
![Uploading Capture d’écran 2015-01-27 à 07.30.38.png . . .]()

**Comment by lonvia** [comment]
Fixed, too (but not yet live). For the future, please don't raise new issues on closed tickets. They tend to get ignored.
