### ISSUE TITLE
Error on Nominatim Update

### ISSUE THREAD

**Issue by djtak47** [twain47/Nominatim#214]
Hi, i have a nominatim server running with the DACH(Germany,Austria, Switzerland) extract from Geofabrik. Everthing works fine, and worked fine ... but now after a few updates i get this error

  Done 8 in 30 @ 0.266667 per second - Rank 16 ETA (seconds): 157.499985
  Done 8 in 30 @ 0.266667 per second - Rank 16 ETA (seconds): 157.499985
  Done 8 in 31 @ 0.258065 per second - Rank 16 ETA (seconds): 162.750000
  Done 8 in 31 @ 0.258065 per second - Rank 16 ETA (seconds): 162.750000
  Done 8 in 32 @ 0.250000 per second - Rank 16 ETA (seconds): 168.000000
index_placex: UPDATE failed: Error: 1

My Nominatim Data is Up to date until the 09.12.2014 .. somehow i cant find anything about this error, and the Errormessage is not really easy to figure out where the problem might be.. is there someone who can help me here? 

Btw.

Server Ubuntu 12.04 / 64 Bit

Thanks in advance

**Comment by lonvia** [comment]
Any news on this?

**Comment by lonvia** [comment]
Closing because no further information was provided.
