### ISSUE TITLE
Added new special phrases

### ISSUE THREAD

**Issue by pyrog** [twain47/Nominatim#215]
I had emergency=defibrillator to [Nominatim/Special_Phrases/FR](http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/FR#fr).

Could you merge them please ?

**Comment by lonvia** [comment]
DB was reimported and the special phrases thus updated.

**Comment by mutipg** [comment]
Hi, I found this thread and I want ask you for import new special phrases, which one I had added in Polish language. Some of them I had added 6 months ago. I think, that special phrases should be importing automatically at least monthly. Is there a possibility to write any script for this?

Frequently updating special phrases will be stimulating for adding new phrases in local language for users.

Once more please to import Polish Special Phrases to Nominatim: [Nominatim/Special_Phrases/PL](https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/PL)

Thank you!
