### ISSUE TITLE
Allow multiple values in reverse lookup by OSM ID

### ISSUE THREAD

**Issue by saerdnaer** [twain47/Nominatim#222]
Currently one can only ask for one reverse lookup by OSM ID per request:
Examples: 
 * http://nominatim.openstreetmap.org/reverse?format=json&osm_type=N&osm_id=271239092
 * http://nominatim.openstreetmap.org/reverse?format=json&osm_type=W&osm_id=27169996

If you want to use this endpoint to reverse lookup a list e.g. returned from an overpass query, you have to wait one second per result as the usage policy requests this.

I propose to add a osm_ids parameter, to allow to retrieve multiple addresses in one request, e.g. http://nominatim.openstreetmap.org/reverse?format=json&osm_ids=N271239092,W27169996

What's your opinion? Should I provide an patch?

**Comment by lonvia** [comment]
Would be ok for me, although I wonder if it wouldn't be better to provide something like that in an extra endpoint, something like '/address' maybe? There should also be a server configurable limit, how many items can be retrieved.

**Comment by saerdnaer** [comment]
Please ignore 52b21d8.

**Comment by saerdnaer** [comment]
Looks like this issue can be closed:
https://nominatim.openstreetmap.org/lookup.php?osm_ids=R146656,W104393803,N240109189

Thanks to all involved!

**Comment by lonvia** [comment]
There is still documentation missing at the http://wiki.openstreetmap.org/wiki/Nominatim wiki page. I wouldn't mind if somebody beats me to it.

**Comment by mtmail** [comment]
I'll add that later today.

**Comment by saerdnaer** [comment]
Here is my first first draft for the new section: http://wiki.openstreetmap.org/wiki/Nominatim#Address_lookup

I'm not so sure about the json_callback and accept-language parameters, so please delete these sections when they are not there.

**Comment by mtmail** [comment]
awesome. Looks good to me

**Comment by lonvia** [comment]
Wow, that was really quick. Thanks!
