### ISSUE TITLE
Error while indexing rank 30

### ISSUE THREAD

**Issue by lucasoares** [twain47/Nominatim#225]
(... Have more in log file)
```
  Done 32016 in 43 @ 744.558167 per second - Rank 21 ETA (seconds): 0.498282
  Done 32402 in 43 @ 753.534912 per second - ETA (seconds): -0.019906
  Done 35356 in 43 @ 822.232544 per second - ETA (seconds): -3.610901
  Done 35356 in 43 @ 822.232544 per second - FINISHED

Starting rank 22
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 23
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 24
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 25
  Done 0 in 0 @ 0.000000 per second - FINISHED

ANALYZE
nominatim version 2.4

Starting indexing rank (26 to 30) using 3 threads
Starting rank 26
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 27
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 28
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 29
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 30
index_placex: UPDATE failed: ERROR:  record "new" has no field "addr_place"
CONTEXT:  SQL statement "SELECT NEW.parent_place_id IS NULL AND NEW.addr_place IS NOT NULL"
PL/pgSQL function placex_update() line 305 at IF
ERROR: Error executing external command: /home/osm/Nominatim-2.3.1/nominatim/nominatim -i -d nominatim -P 5433 -t 3 -r 26
Error executing external command: /home/osm/Nominatim-2.3.1/nominatim/nominatim -i -d nominatim -P 5433 -t 3 -r 26
```

I'm trying to import south_america osm file. This error happens and I don't know how to fix.
Someone can help me? Thanks!

**Comment by lucasoares** [comment]
I discovered that the error occurs in the following line of "nominatim/index.c" file:

```
pthread_join (thread_data [i] .thread, NULL);
```

Now I'm trying to check what this can be.

**Comment by lonvia** [comment]
You are using the wrong osm2pgsql version. Have you changed the definition of `CONST_Osm2pgsql_Binary` in your settings/local.php?

**Comment by lucasoares** [comment]
Yes.. If I use the osm2pgsql in Nominatim/osm2pgsql my import get error... Then i'm using the /usr/bin/osm2pgsql... Oh god, three days trying to install nominatim...

**Comment by lucasoares** [comment]
There should be a more easy way to do the installation without worrying about dependencies... Proj, Gdal, GEOS, omg, so many dependencies =/ 

I will try again starting with nothing, with an empty linux server and using nominatim git version.. Any suggestions?

**Comment by lonvia** [comment]
Just follow the installation guide to the letter and try your import first with something small like the [Liechtenstein excerpt](http://download.geofabrik.de/europe/liechtenstein.html) to ensure that everything works. 2.3.1. should be working fine.

**Comment by lucasoares** [comment]
But i'm doing this.. In Installation have dependencies that doesn't have in repository, like postgresql 9.1 and proj =/

I don't know what to do anymore kkkk
Now my website is online but every search results empty (this happens because my index has fail?)

**Comment by trymodel** [comment]
Hi, I have the same problem, please help.

Starting rank 30
index_placex: UPDATE failed: ERROR:  record "new" has no field "addr_place"
CONTEXT:  SQL statement "SELECT NEW.parent_place_id IS NULL AND NEW.addr_place IS NOT NULL"

CONST_Osm2pgsql_Binary   /usr/bin/osm2pgsql   (version 0.82.0 64bit)
Nominatim latest version from github

thx

**Comment by lonvia** [comment]
You should not set `CONST_Osm2pgsql_Binary` in your local config unless you really know what you are doing. Remove it and start the import from the beginning.

**Comment by trymodel** [comment]
thx, i try clear instalation from the beginning

**Comment by moisesf** [comment]
**Hi, when i do not set CONST_Osm2pgsql_Binary i got this error:**

_Import
osm2pgsql SVN version 0.89.0-dev (64bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for sparse node cache
Node-cache: cache=512MB, maxblocks=65536*8192, allocation method=9
Mid: loading persistent node cache from /home/nominatim/flatnode.file
Allocated space for persistent node cache file
Maximum node in persistent node cache: 0
Mid: pgsql, scale=10000000 cache=512
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/nominatim/brazil-latest.osm.pbf
Using PBF parser.
Processing: Node(35523k 70.2k/s) Way(1484k 5.77k/s) Relation(0 0.00/s)Killed
ERROR: Error executing external command: /home/nominatim/Nominatim/osm2pgsql/osm2pgsql --flat-nodes /home/nominatim/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 --cache-strategy sparse -C 512 -P 5432 -d nominatim /home/nominatim/brazil-latest.osm.pbf
Error executing external command: /home/nominatim/Nominatim/osm2pgsql/osm2pgsql --flat-nodes /home/nominatim/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 --cache-strategy sparse -C 512 -P 5432 -d nominatim /home/nominatim/brazil-latest.osm.pbf_

**AND when i set CONST_Osm2pgsql_Binary to /usr/bin/osm2pgsql i got this error:**
_  Starting rank 30
index_placex: UPDATE failed: ERROR:  record "new" has no field "addr_place"
CONTEXT:  SQL statement "SELECT NEW.osm_type = 'N' AND NEW.street IS NULL AND NEW.addr_place IS NULL
         AND NEW.housenumber IS NULL"
PL/pgSQL function placex_update() line 191 at IF
ERROR: Error executing external command: /home/nominatim/Nominatim/nominatim/nominatim -i -d nominatim -P 5432 -t 1 -r 26
Error executing external command: /home/nominatim/Nominatim/nominatim/nominatim -i -d nominatim -P 5432 -t 1 -r 26_


**What should i do ?**

**Comment by lonvia** [comment]
1. Please do not post on closed tickets.
2. Make sure you read and understand the answers already given and try them out.
