### ISSUE TITLE
json_callback should give the name of the HTTP parameter, not the name of the callback function

### ISSUE THREAD

**Issue by juvation** [twain47/Nominatim#227]
IMHO, the Nominatum service should take the name of the HTTP parameter in which the client specifies the name of the JSONP callback function, rather than the name of the function itself.

The reasoning is that Nominatum client code may be several layers higher than the code which implements JSONP, and indeed, as Nominatum has a regular HTTP+JSON interface, the code which makes the request might be in a library. In my case, I use a declarative framework which allows me to make HTTP calls directly from HTML, so my only recourse was to hardcode json_callback into the Ajax library.

If the name of the HTTP parameter in which the callback function was specified instead, then the developer could simply insert whichever parameter name his library or framework uses, and everything would work without further impact on the client side.

Thanks for listening :-)

**Comment by lonvia** [comment]
Nominatim pretty much follows the established JSONP conventions here, at least if [wikipedia](https://en.wikipedia.org/wiki/JSONP) is to be believed. So it sound rather like something odd is going on with the framework. In any case, JSONP seems to be dying out. You should have a look into CORS instead which is the more modern solution of cross-scripting and well supported by Nominatim.

**Comment by juvation** [comment]
Thanks for the response, but an isolated sample code fragment in Wikipedia does not necessarily demonstrate robust design.

I don't think you're understanding the problem. If the piece of code making the Nominatum call is not the piece of code implementing JSONP, then there will be a problem, as the client doesn't know how the JSONP callback name is generated. For example, in order to allow multiple parallel JSONP requests from different clients, a library (such as jQuery) may dynamically generate JSONP callback functions. There would be no way for a piece of code way above this process to know the name of the function ahead of time. 

However, if Nominatum allowed the specification of the parameter name and not the callback name, then that would solve the problem for all cases.

I agree on CORS, but so far i have been unable to make it work with Nominatim, at least on Firefox OS. And not everyone is CORS generous :-)
