### ISSUE TITLE
Minor enhancement for junction=yes

### ISSUE THREAD

**Issue by sommerluk** [twain47/Nominatim#229]
With #137 we got support for junction=yes.

When searching for a junction, you see in the results as object type “yes”. (http://nominatim.openstreetmap.org/search.php?q=Carrefour+Mouton)

It would be great to have something more descriptive. I would propose “road junction”.

**Comment by lonvia** [comment]
Was already fixed in fbc5ba13f8a28f8e5fc83675823efbaeea6dcb70 which is now live on nominatim.osm.org. Also fixed now for the main osm.org site, e.g. http://www.openstreetmap.org/search?query=carrefour mouton

**Comment by sommerluk** [comment]
Thanks a lot!
