### ISSUE TITLE
Street names in small villages

### ISSUE THREAD

**Issue by hope15** [twain47/Nominatim#230]
Most small villages in Austria have street names, but they don't match with the name of the street that corresponds with the house number.

E.g.

http://www.openstreetmap.org/#map=19/46.89243/10.50261
The name of the street is "Mittergasse" but the address for the building is "Nauders 61"

Things here in Austria are a bit different than in other countries. The house numbers were added later on and the street names (at least in smaller villages) aren't that important. To fix that problem the people decided to add one main street name, which is valid for the whole village and each building gets a house number. Basically there are just two street names which are used, the first one is the **name of the village as street name** and the second one is **Dorf** which translates into Village.

Unfortunately this happens quite often and most house numbers got added with the `addr:street` + `addr:housenumber` tag. As there is no street with this name in the immediate vicinity, the housenumber cannot be found using the search.

The `addr:street tag` is actually correct but it's not the name of the street that is in front of the building.

I wouldn't mind to add some `addr:place` tags to fix that issue, but that problem occurs in most of the villages here and I'm simply not able to change it for all of them.

Is there something you can do against this problem?

**Comment by lonvia** [comment]
You really should fix that in the data itself. Even if Nominatim had some special hack for this situation, there is lots of other software that may not know about the special situation. We cannot change all of it.
