### ISSUE TITLE
Help me with this error,

### ISSUE THREAD

**Issue by soulraven** [twain47/Nominatim#237]
i get sometimes, on random interval this error,
Fatal error: Cannot use object of type DB_Error as array in /opt/Nominatim/lib/PlaceLookup.php on line 54

any ideea how to manage that?

**Comment by mtmail** [comment]
See the pull request https://github.com/twain47/Nominatim/pull/238 on how to print an error message in that line. We simply forgot to add the check before.

**Comment by lonvia** [comment]
Merged @mtmail's pull request which should give you a better error message but only in debug mode (add debug=1 to the offending query). I don't manage to see from the code how this DB query could go wrong, so might just be a faulty database, especially if it appears randomly.

**Comment by lonvia** [comment]
Closing because no further information was provided.
