### ISSUE TITLE
Consider adding '[Pp]olice [Ss]tation' to Special Phrase for amenity=police

### ISSUE THREAD

**Issue by neiljp** [twain47/Nominatim#239]
I couldn't see this in the repository, so perhaps it is maintained separately, but I would suggest that when searching for 'police' then this may include 'station' too, at least for (some) english locales.

Please let me know if this is not the correct issue reporting location for these kinds of keywords/"translations".

**Comment by lonvia** [comment]
You should add such phrases in the wiki: http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/DE

Nominatim takes its phrases from there. Note however that reimport needs to be triggered manually and doesn't happen that often.

**Comment by neiljp** [comment]
Is there no review process for what goes in there? Or process for proposing a 'reimport' - or statistics on when that happens?
