### ISSUE TITLE
"Search for more results" link broken in new install

### ISSUE THREAD

**Issue by bdaroz** [twain47/Nominatim#241]
Was testing a new 2.3 install and noticed the link under the search results for "Search for more results" send the user to a non-existent page.

The trouble appears to be in website/search.php on line 120:
```php
$sMoreURL = CONST_Website_BaseURL.'search?format='.urlencode($sOutputFormat).'&exclude_place_ids='.join(',',$oGeocode->getExcludedPlaceIDs());
```

Shouldn't we be sending the user to 'search.php' not 'search'?

**Comment by lonvia** [comment]
Nominatim assumes that it is set up in a way that /search is an alias for /search.php. The method that is recommended in the installation docs is via MultiViews, on osm.org we use Rewrites. Nonetheless, having *.php links might be a good idea, so that you are not forced to do the aliasing.
