### ISSUE TITLE
Server is version 9.4, library is version 9.1, different then issue #116

### ISSUE THREAD

**Issue by kfholbrook** [twain47/Nominatim#242]
I receive the same error referenced in issue #116. I've removed the mentioned library postgresql-server-dev-9.1, with apt-get remove --purge, the reconfigured. I'm running postgres 9.4. Is this a missing dependency or an software bug?

**Comment by lonvia** [comment]
This is a dependency problem. Make sure you have `postgresql-server-dev-9.4` installed and check which version is reported with `pg_config --version`. If it is still 9.1, check with `dpkg -l 'postgres*9.1'` which packages are still installed from 9.1, remove them and make sure the equivalent packages for 9.4 are there.

**Comment by lonvia** [comment]
Closing as no further information was provided.
