### ISSUE TITLE
Add "Standesamt" to the Nominatim/Special Phrases/DE

### ISSUE THREAD

**Issue by lintux** [twain47/Nominatim#243]
Hi,

I have added the German word "Standesamt" (amenity=register_office) to the Nominatim/Special Phrases/DE Wiki entry here:
https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/DE
Annd I would like it to be recognized by Nominatim. 
Could you please add it for the next scheduled release?

Thanks in advance
Stephan

**Comment by lonvia** [comment]
This will happen with the next reimport. There is no fixed schedule for those yet.
