### ISSUE TITLE
Issue with installation on CentOS 6.0

### ISSUE THREAD

**Issue by crookedcircle** [twain47/Nominatim#245]
I have followed all the options as mentioned on the wiki installation but it still does not work
This is what i get in the apache error log.
Tried various options on forums but no luck.

Can anyone help?
Symbolic link not allowed or link target not accessible: /usr/local/apache/htdocs/nominatim/index.php

Is nominatim not compatible with CentOS 6.0???

Please help

**Comment by mtmail** [comment]
Can you post the output of `httpd -V`? That will tell us which version of Apache you use, were your configuration and data directories are.

Does `httpd -t -D DUMP_MODULES` list the `php5_module` module?

Did the ` ./utils/setup.php --create-website /var/www/nominatim` command run without error? Did you use this or another path (for example `/usr/local/apache/htdocs/nominatim) ?

Can you post the Nominatim related parts of the Apache configuration?

You can go into the Nominatim `/website` directory and run `php -S localhost:8000`. This will start a webserver on port 8000. Do you see output in your browser at http://localhost:8000/ ?

**Comment by Edig** [comment]
I have a similar problem, I have this when I try to create the website

WARNING: Unable to access the website at 

I double check and the apache service its running perfectly. I can access the ip of my server

**Comment by lonvia** [comment]
Please provide the information @mtmail asked for or we can't help you.

**Comment by crookedcircle** [comment]
This is what i get when i run httpd - V

Server version: Apache/2.2.29 (Unix)
Server built:   Feb 25 2015 18:33:38
Cpanel::Easy::Apache v3.28.4 rev9999
Server's Module Magic Number: 20051115:36
Server loaded:  APR 1.5.1, APR-Util 1.5.4
Compiled using: APR 1.5.1, APR-Util 1.5.4
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses disabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/usr/local/apache"
 -D SUEXEC_BIN="/usr/local/apache/bin/suexec"
 -D DEFAULT_PIDLOG="logs/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="logs/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"


httpd -t -D DUMP_MODULES does not load php5 module

yes the nominatim folder is create on this path - /usr/local/apache/htdocs/nominatim
and also on this path /var/www/nominatim

This is what i get when i run the utils setup command

WARNING: Unable to access the website at http://localhost/nominatim/
You may want to update settings/local.php with @define('CONST_Website_BaseURL', 'http://[HOST]/[PATH]/');
Setup finished.

 
This is what i have in the httpd.conf for noiminatim
Earlier i had put 
<Directory "/var/www/nominatim/">
    Options FollowSymLinks MultiViews
    AddType text/html   .php     
 </Directory>

then again i put this

 <Directory "/usr/local/apache/htdocs/nominatim">
    Options FollowSymLinks MultiViews
    AddType text/html   .php
 </Directory>

Please help.. I don't know how to resolve this.. I have tried many things..
What should i do?

**Comment by mtmail** [comment]
Hi,

It's possible you have Apache installed twice.

1. using `yum install httpd`. Then your binary is in `/usr/sbin/httpd`
2. from source. Then your binary is in `/usr/local/apache2/bin/httpd`

Check with `ps -auxwww | grep httpd` which installation is running.

It is easier if you use the Apache installed by yum because it already has PHP enabled and the Nominatim installation instructions use it. See my comments in https://github.com/twain47/Nominatim/issues/248 how the configuration files would look.

To enable PHP in the Apache installed from source you will need to run something like

    cd /tmp
    wget http://ie1.php.net/get/php-5.6.6.tar.gz/from/this/mirror
    mv mirror php-5.6.6.tar.gz
    tar -xzf php-5.6.6.tar.gz
    cd php-5.6.6
    ./configure --with-pgsql=/usr/pgsql-9.3/ --prefix=/usr/local/apache2/php --with-config-file-path=/usr/local/apache/php --with-apxs2=/usr/local/apache2/bin/apxs --with-zlib
    make
    make test
    sudo cp -p .libs/libphp5.so /usr/local/apache2/modules/
    sudo mkdir /usr/local/apache2/php
    sudo cp -p php.ini-production /usr/local/apache2/php/php.ini

Then in `/usr/local/apache2/conf/httpd.conf` make sure you have the lines

    LoadModule php5_module  modules/libphp5.so
    AddHandler php5-script  .php

Restart Apache with `sudo /usr/local/apache2/bin/apachectl restart` and check with `httpd -t -D DUMP_MODULES` if the `php5` module is now loaded.
