### ISSUE TITLE
Cant fully install in CentOS 6.5

### ISSUE THREAD

**Issue by Edig** [twain47/Nominatim#248]
Hi, I try to install Nominatim in a new VPS with CentOS

I follow this instructions, http://wiki.openstreetmap.org/wiki/Nominatim/Installation but I can't fully install it.

First problem. If I download the code via github I get a error while ./configure that I need a library (that is not require) with osm2pg. I think is libboost-dev. I fI download the code from the link ism give me I can install it successful

After install it with that link version 2.3.1 in my apache the web data is in /var/www/html no in /var/www
and I can't run  ./utils/setup.php --create-website /var/www/nominatim
with and without html I get the same error

Unable to access the website at http://162.243.175.219/nominatim
You may want to update settings/local.php with @define('CONST_Website_BaseURL', 'http://[HOST]/[PATH]/');

If I check the file exist in the directory, but I can't access the web because I get forbidden access

Any ideas what I'm doing wrong?

**Comment by mtmail** [comment]
You're right: `osm2pgsql` needs `boostlib >= 1.48` and a standard `yum install boost-devel` on CentOS 6.5 will only install 1.41 so you need to install it from source and then run `BOOST_ROOT=/usr/local/include/boost/ ./configure --with-postgresql=/usr/pgsql-9.3/bin/pg_config`.

On CentOS 7.0 a `yum install boost-devel` installs 1.53 so that's easier.

On http://162.243.175.219/nominatim I see a `You don't have permission to access /nominatim/ on this server. Apache/2.2.15 (CentOS)` error. So we know there is no firewall and Apache knows about that path.

The commands I ran on a new CentOS 6.5 64bit installation were

    whoami
    # => this prints 'centuser' for me
    sudo mkdir -m 755 /var/www/html/nominatim
    sudo chown `whoami` /var/www/html/nominatim
    ./utils/setup.php --create-website /var/www/html/nominatim

In `/etc/httpd/conf/httpd.conf` I have

    Listen 80
    User apache
    Group apache
    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>
    <Directory "/var/www/html">
        Options Indexes FollowSymLinks
        AllowOverride None
        Order allow,deny
        Allow from all
    </Directory>
    <Directory "/var/www/html/nominatim/">
       Options FollowSymLinks MultiViews
       AddType text/html   .php
    </Directory>

and restarted using `sudo service httpd graceful`.

Can you check if user `apache` (or the user in your httpd.conf file) can read and execute (look for the `x`) the `index.php` file?

    sudo -u apache ls -la /var/www/html/nominatim/index.php
    lrwxrwxrwx 1 centuser centuser 43 Feb 28 21:30 /var/www/html/nominatim/index.php -> /home/centuser/Nominatim/website/search.php

    sudo -u apache ls -la /home/centuser/Nominatim/website/search.php
    -rwxrwxr-x 1 centuser centuser 4675 Feb 28 20:41 /home/centuser/Nominatim/website/search.php

Does `sudo tail /var/log/httpd/error_log` show any permission errors?

**Comment by Edig** [comment]
HI @mtmail 

I try it in a new fresh CentOS 7.0

But, While compiling, I got an error with osm2pgsql

with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [output.lo] Error 1
make[2]: Leaving directory `/root/Nominatim/osm2pgsql'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/Nominatim/osm2pgsql'
make: *** [all-recursive] Error 1

**Comment by mtmail** [comment]
That's weird. I use a VM with

    cat /etc/centos-release
    # => CentOS Linux release 7.0.1406 (Core)

as well and `make` finishes after 3 minutes without error.

    rm -rf Nominatim/
    git clone --recursive git://github.com/twain47/Nominatim.git
    # =>  Submodule path 'osm2pgsql': checked out '10c274f851b63547d8e1a194231a67f8f0f8aed6'
    cd Nominatim
    ./autogen.sh
     ./configure --with-postgresql=/usr/pgsql-9.3/bin/pg_config
    make

I also tried fixing to a specific release (tag) with `git checkout v2.3.0` but I see no error either.

**Comment by Edig** [comment]
Same error, I think the only thing different is that I have pgsql 9.4. no 9.3.

I will try it in a new CentOS with 9.3

**Comment by lonvia** [comment]
@Edig The error containing bugzilla, the actual error message is missing. There must have been more error message above the instruction to post the error to redhat,com.

**Comment by Edig** [comment]
@lonvia , @mtmail I think I solve it. The problem was "not enough ram" I was trying with a Digital Ocean VPS with 512MB of Ram. How much RAM do you recommend me, I will only upload 15GB of the full planet, just administrative areas

**Comment by lonvia** [comment]
The absolute minimum used to be 1GB but these days I wouldn't recommend importing a planet with less than 8GB, better 16GB for your reduced dataset and 32GB for a full planet.

Closing issue as solved.
