### ISSUE TITLE
Question: Install Wikipedia articles after initial import?

### ISSUE THREAD

**Issue by brainformatik** [twain47/Nominatim#254]
Hi everybody,

I'm new to the openstreetmap project and Nominatim. I followed the installation instructions and everything works perfectly. Because two steps are marked as optional I ignored them during initial import.

Now I want to know if it's possible to import
1. Wikipedia rankings
2. UK postcodes
without reindexing (and wait 10 days again)?

**Comment by lonvia** [comment]
You can install the UK postcodes after the import, just run:
~~~
wget -O data/gb_postcode_data.sql.gz http://www.nominatim.org/data/gb_postcode_data.sql.gz
zcat data/gb_postcode_data.sql.gz | psql -d nominatim
~~~

The WIkipedia rankings cannot be added after the import. Or to be precise: they can be added (with `./utils/setup.php --import-wikipedia-articles`) but will only have an effect on data that is updated afterwards. It would be nice to have a function that updates importances, though. I've opened a new issue (#255) for that.

**Comment by brainformatik** [comment]
Thanks for your answer, will try this next few days.

Function to update importances after import would be great.
