### ISSUE TITLE
Error in reverse geoding on local region only nominatim stacks

### ISSUE THREAD

**Issue by IrlJidel** [twain47/Nominatim#256]
I've noticed a number of times on my ireland-only nominatim instance that locations in UK are sometimes reported as being in Northern Ireland

Global:
http://nominatim.openstreetmap.org/reverse?format=json&lat=55.2423568&lon=-4.8495695 

Ireland:
http://nominatim.openstreetmap.ie/reverse?format=json&lat=55.2423568&lon=-4.8495695

To try to remedy the situation, I imported the England,Scotland,Wales,Isle of Man  state relations.

eg Scotland relation http://nominatim.openstreetmap.ie/details.php?place_id=781803 

Is there anything I can do to help debug or remedy this error?

I executed all queries returned by 

http://nominatim.openstreetmap.ie/reverse?format=json&&lat=55.2423568&lon=-4.8495695&debug=1

nominatim=# select place_id,parent_place_id,rank_search from placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), geometry, 0.0008) and rank_search != 28 and rank_search >= 28 and (name is not null or housenumber is not null) and class not in ('waterway','railway','tunnel','bridge') and indexed_status = 0 and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), centroid, 0.0008)) ORDER BY ST_distance(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), geometry) ASC limit 1;
 place_id | parent_place_id | rank_search
----------+-----------------+-------------
(0 rows)

... All return 0 rows except for  last one for  rank_search >= 8 ...

nominatim=# select place_id,parent_place_id,rank_search from placex WHERE ST_DWithin(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), geometry, 1.6384) and rank_search != 28 and rank_search >= 8 and (name is not null or housenumber is not null) and class not in ('waterway','railway','tunnel','bridge') and indexed_status = 0 and (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon') OR ST_DWithin(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), centroid, 1.6384)) ORDER BY ST_distance(ST_SetSRID(ST_Point(-4.8495695,55.2423568),4326), geometry) ASC limit 1
nominatim-# ;
 place_id | parent_place_id | rank_search
----------+-----------------+-------------
   721455 |          718939 |          12

http://nominatim.openstreetmap.ie/details.php?place_id=721455
County Down, Northern Ireland

http://nominatim.openstreetmap.ie/details.php?place_id=718939
Northern Ireland

**Comment by lonvia** [comment]
There are two problems here: on one hand, reverse geocoding only takes into account objects of rank 8 or higher. That's why Scotland is ignored. On the other hand, the County in Northern Ireland should be ignored because the point you are geocoding is outside the polygon of the county.

There is a similar problem with reverse geocoding points in the middle of the sea.

**Comment by lonvia** [comment]
Correction: Scotland it ignored because the center of Scotland is too far away from the point being reverse geocoded. I'm not quite sure why this additional restriction regarding distance to polygon centroid is in there.

**Comment by lonvia** [comment]
Closing in favour of #79.
