### ISSUE TITLE
Geocoding sometimes results street-level accuracy, when removing postcode returns housenumber-level accuracy?

### ISSUE THREAD

**Issue by laura-me** [twain47/Nominatim#258]
Hello,

for some addresses I have the problem that querying an address with postcode returns street-level accuracy but removing that postcode returns housenumber-level accuracy.

Example:
* http://nominatim.openstreetmap.org/search.php?q=rotbuchstrasse+34%2C+zürich
returns housenumber-level accuracy

* http://nominatim.openstreetmap.org/search.php?q=rotbuchstrasse+34%2C+8037+zürich
returns only street-level accuracy

Other streets in that area return housenumber-level accuracy also when using postcode.

Why is that so? Or am I doing something wrong?

Thanks, Laura

**Comment by lonvia** [comment]
The postcode is not in the search index because the postcode appears only on the building while search works on street level. A more detailed explanation of the issue can be found in https://trac.openstreetmap.org/ticket/2497

Closing as a duplicate here.
