### ISSUE TITLE
Don't  overwrite --osm2pgsql-cache option given by user

### ISSUE THREAD

**Issue by chessplayer60** [twain47/Nominatim#260]
Background: I am having trouble importing europe_latest.pbf for Nominatim, as the ways only trickle in. Therefore, I tried a high value for the osm2pgsl cache (10 GB), which would amount to more than total memory, but less than total memory plus swap. Before, I had 4GB (which is 2/3 of total memory).

Then, with 10GB cache, I got a warning that cache was reset to some (very small) value, much lower than the 4GB I used before, which did not result in such a warning.

That made me look at https://github.com/twain47/Nominatim/blob/master/utils/setup.php first to see where the reset takes place and then at https://github.com/twain47/Nominatim/blob/master/lib/lib.php to see how the resulting value was arrived at.

Problem: It makes absolutely no sense at all to reset cache memory to the amount of memory ALREADY cached, which is what is happening in line 85 of setup.php. One could think about going for TOTAL - CACHED, if really necessary, but certainly not cached. Also, Swap is not taken into account in the computation of total memory, which is at least questionable.

My suggestion would be to use MemFree + SwapFree and compare that with the value specified on the command line, but in any case something must be done about this.

Cheers,

chessplayer

**Comment by lonvia** [comment]
Agreed that the default isn't very sensible.

My preference would be: do not do any resets if the value was given by the user (it's your own foot for shooting after all) and make the default depend on total ram only (something like 2/3).

Side-node: swapping tends to make matters worse, so it is a good idea to keep the cache value below your available main memory. Try the flatnode option to speed up things instead.
