### ISSUE TITLE
Different results depending on limit value

### ISSUE THREAD

**Issue by amnesia7** [twain47/Nominatim#263]
`limit=1` 
http://nominatim.openstreetmap.org/search?format=json&addressdetails=0&limit=1&q=new+york&viewbox=-6.4%2C54.6%2C1.6%2C46.6
shows `New York, Lincolnshire, East Midlands, England, United Kingdom`

`limit=2` 
http://nominatim.openstreetmap.org/search?format=json&addressdetails=0&limit=2&q=new+york&viewbox=-6.4%2C54.6%2C1.6%2C46.6
shows `New York City, New York, United States of America` as the first result and `New York, Lincolnshire, East Midlands, England, United Kingdom` as the second result.

`limit=3` 
http://nominatim.openstreetmap.org/search?format=json&addressdetails=0&limit=3&q=new+york&viewbox=-6.4%2C54.6%2C1.6%2C46.6
shows `New York City, New York, United States of America` as the first result, `New York, United States of America` as the second result and `New York, Lincolnshire, East Midlands, England, United Kingdom` as the third result.

Is this behaviour correct that, in this case, the Lincolnshire result gets pushed further down the results list as the limit is increased and more important results are returned?

I can see that the Lincolnshire result is within the view box so is an exact match if `limit=1` but I just wanted to check.

**Comment by lonvia** [comment]
The viewbox is only taken into account when searching for matching objects. Afterwards they are reordered purely by importance and how well the address fits the query. Insofar your results are not unexpected. It might be a good idea to take the viewbox into account for the reranking as well. It's just tricky to say by how much. In the example case of New York, I'd say that it is much more likely that the user actually meant the one in the US, at least with a bounding box that large.

**Comment by amnesia7** [comment]
The reason for the large bounding box is to allow for the accuracy of the free geo ip lookup which can be quite a distance out. I wanted to bias the search call using the user's location.
This question came about because a UK user searching for `Lancaster` would return the one in USA without using `viewbox` whereas, with it being a city, they would likely want the one in the UK. I therefore used `viewbox` to try to bias the result returned. This did work but I also found that, with `limit=1`, sometimes it was preferring a small village with a name match over what would be the more likely match outside the viewbox (eg `New York` in this case).

Using `limit=2` seems to suit because it seems to be finding more appropriate results but also biases towards the more suitable results in the viewbox if possible. If that's correct then feel free to close this issue.

**Comment by lonvia** [comment]
Yes, in that case the viewbox parameter gives you approximately what you need.

**Comment by amnesia7** [comment]
@lonvia thanks for the confirmation.
