### ISSUE TITLE
Addressparts is missing a part of result

### ISSUE THREAD

**Issue by Stalfur** [twain47/Nominatim#272]
Doing a lookup for the lat/lon of Limbourg, Belgium the addressparts at the bottom don't give me the same values as the result at the top.

result: (partial) Limbourg, Verviers, Liège, Wallonia
addressparts omits Liège altogether although that is the district.

http://nominatim.openstreetmap.org/reverse?format=xml&lat=50.6121532&lon=5.9400907&zoom=18&addressdetails=1&accept-language=en

**Comment by lonvia** [comment]
This is another effect of non-standard admin-level use in Belgium, see also https://trac.openstreetmap.org/ticket/5271

**Comment by Stalfur** [comment]
Looking at the admin levels I see 
admin_level 4 = state (Wallonia)
admin_level 6 =  (Liège)
admin_level 7 = county (Verviers)
admin_level 8 = village (Limbourg)

Is admin_level 6 unnamed?

**Comment by Stalfur** [comment]
I've added to the wiki page: https://wiki.openstreetmap.org/wiki/Nominatim#Hierarcy

**Comment by lonvia** [comment]
Essentially needs to be fixed via #213.
