### ISSUE TITLE
Nominatim shifts lat/lon query by some distance to another country

### ISSUE THREAD

**Issue by Stalfur** [twain47/Nominatim#275]
I was still using lat/lon because of issue now fixed in #269 and discovered this error:

**Ha Seeiso Letsosa** in Lesotho is at -29.6616392, 27.0316199 but [that lat/lon query](http://nominatim.openstreetmap.org/reverse?format=xml&lat=-29.6616392&lon=27.0316199&zoom=18&addressdetails=1&accept-language=en) returns South Africa and the location in reply moves to -29.6**256899**, 2**6.8426522896152**.
Doing a [osm_id query returns](http://nominatim.openstreetmap.org/reverse?format=xml&osm_id=1567116620&osm_type=N&zoom=18&addressdetails=1&accept-language=en) Lesotho as it should

Very strange, finding nearest relation?

**Comment by mtmail** [comment]
I can shine some light on what Nominatim is doing:

The request includes `&zoom=18` so a very small search radius around the lon/lat is used and it's looking for buildings. To precise named buildings or those with addresses. There isn't one so the search radius gets increased in the next step. And again and again. With larger search radius it's now unrealistic to find buildings so it looks for larger features.

The first match is the suburb Naledi Ward 1(http://nominatim.openstreetmap.org/details.php?place_id=167722629). At that point the search radius about 20km so the loop ran 15 times and got desperate to find anything important. In this case importance is derived from admin_level and Naledi Ward 1 with ad admin_level of 15 is deemed a better result than a village without. So it's unrelated to node vs relation.

I think the logic which features to look for at what zoom levels works well for dense populated areas but fails here in an area were only few features have names. A solution could be to reset the search radius more often.

The work-around is to use `&zoom=13` which returns the village
http://nominatim.openstreetmap.org/reverse?format=xml&lat=-29.6616392&lon=27.0316199&zoom=13&addressdetails=1&accept-language=en

**Comment by Stalfur** [comment]
Thank you for the explanation @mtmail . Using &zoom=13 might be my best bet for how I am using Nominatim.
