### ISSUE TITLE
Why some address doesn't exisit ?

### ISSUE THREAD

**Issue by RZhou94** [twain47/Nominatim#278]
Hello

I am looking for an address in France, 

street name : rue des lilas 
village name : Sillé le guillaume
I can find this street here, in the Open Streep Map
http://www.openstreetmap.org/#map=18/48.18036/-0.13147

And i can find this street with nominatim reverse to find this
http://nominatim.openstreetmap.org/reverse?format=xml&lat=48.18072&lon=-0.13074&zoom=18&addressdetails=1

But when i try with nominatim query, 
http://nominatim.openstreetmap.org/search?q=Rue+des+Lilas&format=json&addressdetails=1
I can't find this street in this village.

Can someone explain this? 
Maybe i have not the right query?

**Comment by lonvia** [comment]
There are too many streets named 'Rue des Lilas' in OSM and by default you'll only get the the fist couple of results. Add the village to the search and all will be good:
http://nominatim.openstreetmap.org/search.php?q=Rue+des+Lilas%2C+sille-le-guillaume&format=json&addressdetails=1
