### ISSUE TITLE
Issue with name:ca and name:es at relation 340193

### ISSUE THREAD

**Issue by jmontane** [twain47/Nominatim#279]
I've an issue finding "el Vendrell" town name.

My browser has accept-lang="ca,en;q=0.5". If I search at Nominatim [1], first item (relation 340193) has display_name="el Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya". That's right.

Forcing accept-lang to "ca" [2], same relation has display_name="el Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya". That's right.

Setting accept-lang to Spanish "es" [3], Spanish names are used. Same relation 340193 has display_name="Vendrell, Bajo Panadés, Tarragona, Cataluña, España" now. That's right.

Now, the issue. If I search in Catalan *and* Spanish, with accept-lang="ca,es" [4], there is a weird effect. Same relation 340193 has display_name="Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya". Please, note Spanish "Vendrell" is used in starting part of display_name, instead Catalan "el Vendrell". Does it works as excepted? What is the logic behind this result? Expected result (IMHO) should be "el Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya".

Note, I found this issue searching "el Vendrell" at OSM website. There is something in OSM Nominatim setup.

Searching in www.openstreetmap.org returns "Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya" using a web-browser with accept-lang "ca,en;q=0.5". That's wrong.
Nominatim returns [5] "el Vendrell, Baix Penedès, Tarragona, Catalunya, Espanya" using the same web-browser. That's right.

Note, OSM relation 340193 was edited 5 months ago. So I thinks it isn't a problem about updating data.

Any hint where is the issue?

[1] https://nominatim.openstreetmap.org/search.php?format=xml&accept-language=%22ca,en;q=0.5%22&q=el+vendrell
[2] https://nominatim.openstreetmap.org/search.php?format=xml&accept-language=ca&q=el+vendrell
[3] https://nominatim.openstreetmap.org/search.php?format=xml&accept-language=es&q=el+vendrell
[4] https://nominatim.openstreetmap.org/search.php?format=xml&accept-language=%22ca,es%22&q=el+vendrell
[5] https://nominatim.openstreetmap.org/search.php?q=el+vendrell

**Comment by lonvia** [comment]
Nominatim can only choose translations of names when it knows the language. If you look at the [place in OSM](http://www.openstreetmap.org/relation/340193), you'll notice that there is only a name tag and a name:es tag. With Spain being multilingual, there is no way for Nominatim to know which language the name tag has. It only has a Spanish translation. If you know ask for responses in 'ca,es', then it will first look for a name in Catalan (not there), then for a name in Spanish, which it finds. So it returns the name in Spanish.

To make a long story short: in bilingual regions like Catalunya it helps to add language-specific tags for all languages.

**Comment by jmontane** [comment]
Ok, I see the cause there. We (Catalan contributors) will check missing name:ca tags. This explains nominatim behaviour.

Thanks for your quick support. This issue can be safely closed, :)
