### ISSUE TITLE
Got some 503s earlier today

### ISSUE THREAD

**Issue by jadatkins** [twain47/Nominatim#281]
Between 11:15 and 11:19 am, British Summer Time (GMT+1) today (that is, about 90 minutes ago) I was seeing a lot of 503s on Nominatim. A user of our web application reported to me that some of the geo-lookup stuff wasn't working, so I did what I always do first, which is to navigate to http://nominatim.openstreetmap.org/ and try the same queries manually in my web browser. The first time I tried this, the home page loaded fine, but when I tried a search, I got a 503 error. Without thinking too much about what 503 means, and thinking vaguely that there might be a problem with requests coming from our IP address (although, now that I think about it, the office and the web application are in very different locations) I went to https://proxy-nl.hide.me in my browser to try the same thing from there. That time, not even the homepage loaded, again returning a 503 instead. At that point I stopped investigating, and sent an email to the user and some of my colleagues telling them that Nominatim was down.

Our web application is configured to pass the email address `admin@tutorfair.com` along with all requests.

**Comment by lonvia** [comment]
I understood that this failure is permanent. If it is just an intermittent issue then it is simply due to server overload caused by abusive clients. Unfortunately, there is only so much we can do about those.
