### ISSUE TITLE
Nominatim installation result

### ISSUE THREAD

**Issue by webmap2015** [twain47/Nominatim#282]
![nominatim](https://cloud.githubusercontent.com/assets/10267317/8124480/8ae51fc6-10e4-11e5-96c9-3d68c362ae9a.png)

After installation osmosis

![nominatim2](https://cloud.githubusercontent.com/assets/10267317/8130676/4f372c2e-111d-11e5-9c9f-73781526537a.png)

**Comment by mtmail** [comment]
Is the `osmosis` binary readable and executable by the current logged in user? For example in one of my installations I see

    $ ls -la /usr/bin/osmosis
    -rwxr-xr-x 1 root root 3374 Aug  8  2012 /usr/bin/osmosis

If not try `sudo chmod 755 osmosis`.

Your file size might differ, I'm using an older version `0.40.1`

    $ /usr/bin/osmosis --version 2<&1 | grep Version
    INFO: Osmosis Version 0.40.1

**Comment by lonvia** [comment]
Closing because no further information was provided.
