### ISSUE TITLE
Country search should respect bounded=1

### ISSUE THREAD

**Issue by steven-qi** [twain47/Nominatim#285]
Look at this query:

https://nominatim.openstreetmap.org/search?q=1&viewbox=121.46120881275779%2C31.191112999955877%2C121.5710631872422%2C31.257170983698707&bounded=1&format=json

Viewbox: [121.46120881275779, 31.191112999955877, 121.5710631872422, 31.257170983698707]

As both viewbox and bounded=1 are specified, if there is no match result in given viewbox, i would expect that an empty array is returned (as implicated with "bounded=1"). But actually irrelevant out-of-bounds results are returned instead (viewbox and bounded=1 are all ignored), e.g., 

```json
[
    {
        "place_id":"127735029",
        "osm_id":"304716",
        "boundingbox":["6.5546079", "35.6745457", "68.1113787", "97.395561"],
        "lat":"22.3511148",
        "lon":"78.6677428",
        "display_name":"India",
    }
]
```

In case there is any match, it seemed that "bounded=1" is obeyed well, e.g.,

https://nominatim.openstreetmap.org/search?q=浦电路&viewbox=121.46120881275779%2C31.191112999955877%2C121.5710631872422%2C31.257170983698707&bounded=1&format=json

The behavior is inconsistent.

**Comment by lonvia** [comment]
The tricky thing here is that "1" actually matches India (don't ask why, currently actively working on fixing that issue), so that Nominatim interprets the whole thing as a country search which ignores viewbox and bounded parameters. The latter obviously needs fixing.

**Comment by guiruiz** [comment]
@lonvia Sorry for the off topic but I need talk to you about a work opportunity, could you email me?
<guilhermeruiz@apeiara.com>

Thanks!

**Comment by lonvia** [comment]
This was actually a glitch on the osm.org installation which has been sorted out in the meantime.
