### ISSUE TITLE
Looking for 2.4.0 release notes

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#286]
The official announcement on the geocoding mailing list included a link
"If you cannot reimport, then detailed instructions for updating can be found in the release notes:
https://github.com/twain47/Nominatim/wiki/Release-Notes-2.4.0"

That wiki page doesn't exist though. Is there another place I can look or can you recreate it (hopefully you have a copy!)

thanks!

**Comment by mtmail** [comment]
found it
https://github.com/twain47/Nominatim/releases/tag/v2.4.0

**Comment by lonvia** [comment]
That was a stupid copy&paste error, thanks for creating the wiki page.
