### ISSUE TITLE
Abbreviations...in Indonesian

### ISSUE THREAD

**Issue by serpico** [twain47/Nominatim#287]
Hi,

What about abbreviations used by Nominatim?
I found this https://github.com/twain47/Nominatim/blob/master/module/tokenstringreplacements.inc Looks pretty old.

I'd be interested to add abbreviations for Indonesian such as Jl. ; Jln.  which are used instead of Jalan/jalan. currently if you send the query  :

For example : 
* http://nominatim.openstreetmap.org/search.php?q=Jalan+Soekarno-Hatta%2C+Indonesia&viewbox=&polygon=1 won't give the same results as 
* http://nominatim.openstreetmap.org/search.php?q=Jl.+Soekarno-Hatta%2C+Indonesia&viewbox=&polygon=1 or 
* http://nominatim.openstreetmap.org/search.php?q=Jln.+Soekarno-Hatta%2C+Indonesia&viewbox=&polygon=1  

While it's in fact the same street name, so depending how you type your query sometimes you can't get any results at all.

Same goes for Gg instead of Gang.

How can I help out to resolve the issue?

Thanks

**Comment by lonvia** [comment]
Please add a list of abbreviations for Indonesian on the [wiki page of abbreviations](http://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations). It is currently not possible to directly integrate new abbreviations into Nominatim but we are working on this issue.
