### ISSUE TITLE
MapQuest Nominatim services not working

### ISSUE THREAD

**Issue by pashtika** [twain47/Nominatim#288]
It appear that MapQuests API services not working properly for some address.
For below address, why I can't see any data are coming? Please help  me asap

http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=7584 E Big Cannon Drive,California,92808,US

**Comment by mtmail** [comment]
Hi,
The street you entered is slightly misspelled. It is named `East Big Canyon Drive`. http://www.openstreetmap.org/way/13352914 Unlike other geocoders Nominatim does not feature spellchecking (frustrating, I know).

**Comment by pashtika** [comment]
Thanks, Now I don't understand problem in below: http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=12 Queen Street, Worcester, MA 01610, USA

**Comment by pashtika** [comment]
Thank you. This is also pulling records
http://open.mapquestapi.com/nominatim/v1/search.php?format=json&q=East Big Canyon Drive,California,92808

**Comment by mtmail** [comment]
Thanks for the feedback.

You're right, the address is correct and should match. It matches without the zip code
http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=12+Queen+Street,+Worcester,+MA,+USA

In Nominatim we know where zipcode 01610 is but it's somewhat special, calculated from other data and doesn't cover this street. So it's the same bug/issue as https://github.com/twain47/Nominatim/issues/179

**Comment by pashtika** [comment]
Why MapQuest nominatim not pulling details for following address? Could you please help asap?
"PO BOX 814 ADDISON IL 601010814"

**Comment by mtmail** [comment]
Thanks for your feedback.

Some address formats don't work with Nominatim. And not all address data exists in the OpenStreetMap database. That doesn't mean Nominatim doesn't work, it just doesn't work in all use cases.

Why do you need help. Why do you need help as soon as possible?

**Comment by pashtika** [comment]
Thanks for your great inputs. 
I don't think OpenStreetMap will be much useful for getting GeoCoding details for any addresses. I am not sure any specific reason why it doesn't accept most addresses?
