### ISSUE TITLE
Issue with index.c

### ISSUE THREAD

**Issue by mwethington** [twain47/Nominatim#296]
nominatim_index()

https://help.openstreetmap.org/questions/44155/nominatim-slow-stuck-at-functions

The function is dying at:

update placex set indexed_status = 0 where place_id = $1

With 3 of these running on a 4 core box.

**Comment by lonvia** [comment]
Looks like this was solved in the meantime as an issue of missing log output. What you should see at this stage is something like that:

```
  Done 66650730 in 65531 @ 1017.086975 per second - Rank 30 ETA (seconds): 5523.384277
  Done 66652085 in 65532 @ 1017.092163 per second - Rank 30 ETA (seconds): 5522.023438
  Done 66652435 in 65532 @ 1017.097473 per second - Rank 30 ETA (seconds): 5521.650879

```

It's normal that this stage takes very long.
