### ISSUE TITLE
nominatim produces wrong hierarchy on extracts

### ISSUE THREAD

**Issue by arahut** [twain47/Nominatim#300]
i am working on India extracts.

here is an example - 
https://nominatim.openstreetmap.org/
Search for "Sushant Lok I"
The hierarchy comes correct - which is 

https://nominatim.openstreetmap.org/details.php?place_id=128121569

Sushant Lok I -> Gurgaon -> Gurgaon District -> Haryana -> India.  [ seems correct ].

Gurgaon city is adjacent to New Delhi and lets assume I am working on the New Delhi extract.
which I have gotten from - http://metro.teczno.com/#new-delhi

When I search for the same string on my nominatim server, it gives 

Address

Sushant Lok I (Type: boundary:administrative, relation 3594659, 10, 0 GOTO)
Sector 27 (Type: place:suburb, relation 3579539, 9, 0.00639822177886205 GOTO)
Gurgaon (Type: place:city, relation 3577685, 8, 0.06254429047442 GOTO)
>> this is wrong.
Ghāziābād (Type: place:county, node 316417276, 15, 0.623710102507573 GOTO)
Meerut (Type: place:county, node 316416983, 15, 0.756753280536007 GOTO)
>> this is wrong.
Delhi (Type: place:state, node 316416994, 15, 0.188791733868306 GOTO)
India (Type: place:country, 0 GOTO)
in (Type: place:country_code, 0 GOTO)

There is no way "Ghaziabad" or "Delhi" could be the parents of Gurgaon, because they are in totally
different states. This is likely happening because nominatim is opportunistically generating 
hierarchy for a place, based on proximity or something like that.

I would like to use nominatim in a way where it only generates hierarchy based on fully enclosing 
polygons. In this case since the state of Haryana was not in the extract, the hierarchy generation should have stopped at "Guragon District" or "Gurgaon city".

Is this possible?

thanks a lot for your help.

**Comment by lonvia** [comment]
To achieve that, you need to exclude place nodes for state, county etc. Unfortunately there is no configuration option for that, so it means hacking the code. Probably easiest is to change the source code around [here](https://github.com/twain47/Nominatim/blob/master/sql/functions.sql#L899). For each type you want to exclude, replace the statement where `rank_search` is set with `return null;` This will drop the place objects from the search index.

**Comment by mtmail** [comment]
Almost forgot: for Ghāziābād and Meerut I fixed two tag issues (invalid key) and linked the node (representing a state) to the relation (representing the boundary of the state).
