### ISSUE TITLE
Missing library during installation

### ISSUE THREAD

**Issue by henryseron** [twain47/Nominatim#302]
Hi, I'm installing nominatim 2.3 over Centos 6.6. I can execute ./autogen.sh correctly, but when I run ./configure, this stops with the next error:

root@testserver [~]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
configure: error: required library not found

According to this, I think that the missing library is pthread, but searching on internet I found that pthread is in GLIBC, and I already have installed glibc 2.12

I know that there is a newest version of nominatim which I can install on Centos 7, but my client has this old versions.

I have next software installed:

CentOS 6.6
Apache: 2.4.14
PHP: 5.4.43
PostgreSQL: 9.3
Postgis: 1.5.3-1.el6

I hope someone can help me.

Thanks a lot.

**Comment by mtmail** [comment]
I just tested a fresh install of CentOS 6.5 x64 on digitalocean ($0.10/h). Then repeated on x32.

Nominatim release 2.3, Postgres 8 though.

glib is glibc-2.12-1.149.el6_6.9.x86_64 and glibc-common-2.12-1.149.el6_6.7.i686 on x32

The `./configure` and `make` ran fine. In other words no idea really what is going on with pthreads.

```
checking for pg_config... /usr/bin/pg_config
checking for PostgreSQL libraries... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for a Lua interpreter with version >= 5.0... lua
checking for lua... /usr/bin/lua
checking for lua version... 5.1
```

**Comment by henryseron** [comment]
I installed on CentOS 6.6, not 6.5, maybe it has some differences. My installation is clean too.

**Comment by mtmail** [comment]
I get no errors on CentOS 6.6, Nominatim 2.3, Postgres 9.3 either.


```
$uname -a
Linux localhost.localdomain 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

(image from http://mirror.netcologne.de/centos/6.6/isos/x86_64/CentOS-6.6-x86_64-netinstall.iso)

**Comment by henryseron** [comment]
Did you download Nominatim from Github as zip file or using git command? I downloaded it as zip.

(my centos image from http://mirror.web-ster.com/centos/6.6/isos/x86_64/CentOS-6.6-x86_64-minimal.iso)

**Comment by mtmail** [comment]
downloaded ` wget http://www.nominatim.org/release/Nominatim-2.3.0.tar.bz2`

**Comment by henryseron** [comment]
I already downloaded the package from http://www.nominatim.org, same as you, and it worked perfectly.

Thanks for your help @mtmail 

Regards.
