### ISSUE TITLE
Formatting reverse geocode output

### ISSUE THREAD

**Issue by adam21** [twain47/Nominatim#303]
Hello everybody,

We spent weeks to install Nominatim with the whole planet OSM database, now it works perfectly.
But we are not too happy with the reverse geocoding format, we want something more readable because our clients are normal users.

Is there any solution to format the output of reverse geocoding ?? we tried with PHP files (reverse.php, search.php) and SQL queries and it was not easy to edit.

we will appreciate your help !

**Comment by lonvia** [comment]
Not really, the formatting is currently well hidden in the SQL code. I would recommend to use the `addressdetails` option and then try to produce a better formatting from the output you get there.

There is also #213 which at some point should improve the output and make it more configurable but that is quite a bit down the road.
