### ISSUE TITLE
Nominatim installation error: Out of memory for node cache dense index

### ISSUE THREAD

**Issue by rakeshsukla53** [twain47/Nominatim#306]
I am installing Nominatim on my Ubuntu server 14.04 through this [link](http://wiki.openstreetmap.org/wiki/Nominatim/Installation) and trying to load OSM data into my postgreSQL database. For loading into my database I am using this command as given in the link:

    ~/Nominatim/utils/setup.php   --osm-file data/latest.osm.pbf   --all --osm2pgsql-cache 1024 2>&1   | tee setup.log 

But it is throwing an error

    Using projection SRS 4326 (Latlong)
    NOTICE:  table "place" does not exist, skipping
    NOTICE:  type "keyvalue" does not exist, skipping
    NOTICE:  type "wordscore" does not exist, skipping
    NOTICE:  type "stringlanguagetype" does not exist, skipping
    NOTICE:  type "keyvaluetype" does not exist, skipping
    NOTICE:  function get_connected_ways(pg_catalog.int4[]) does not exist,  skipping
    Allocating memory for dense node cache
    Out of memory for node cache dense index, try using "--cache-strategy  sparse" instead
    Error occurred, cleaning up
    ERROR: Error executing external command: /home/nominatim/Nominatim /osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 256 -P 5432 -d nominatim /home/nominatim/data/latest.osm.pbf
    Error executing external command: /home/nominatim/Nominatim/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 256 -P 5432 -d nominatim /home/nominatim/data/latest.osm.pbf
   
My ubuntu has 7GB of RAM and I am not sure why this error is coming. I ran the above command by reducing the cache size to 512 and then 256 but it is running into same error. I am not sure how to use `--cache-strategy  sparse` in the given command. 

Screenshot of my Error:
[![enter image description here][1]][1]

Could anybody help with the setup? 
    

  [1]: http://i.stack.imgur.com/wjE2n.jpg

**Comment by rakeshsukla53** [comment]
I have tried increasing/decreasing the cache size it does not work.

**Comment by rakeshsukla53** [comment]
I am not sure how to use `--cache-strategy sparse` with my command above. Any combination with it is resulting into error :/

**Comment by mtmail** [comment]
Which data (country, countries) are you trying to load? How big is the input file (*.pbf)? 7GB is your total RAM, how much is free before you start the script (since other running processes like the database are in memory).

**Comment by rakeshsukla53** [comment]
I am trying to use finland country data which is very small dataset(207 MB). I have a server completely dedicated to nominatim map and there is no other process running

**Comment by rakeshsukla53** [comment]
![capture9](https://cloud.githubusercontent.com/assets/9192661/9232555/55a8b5a0-40fc-11e5-90c8-959299af5d8d.JPG) my memory details

**Comment by rakeshsukla53** [comment]
Any tip on how to use `--cache-strategy sparse' with my command? I tried different combination but none is working.

**Comment by mtmail** [comment]
You'd have to edit `utils/setup.php` to try the other cache strategy.

I'm surprised. The input data is indeed small and should work with 4GB RAM. Anything below 2GB doesn't work these days, not even Lichtenstein or Monaco (very very small countries).

Is you osm2pgsql compiled to use 64bits? https://github.com/openstreetmap/osm2pgsql/issues/23

**Comment by rakeshsukla53** [comment]
I am installation Nominatim from this [link](http://wiki.openstreetmap.org/wiki/Nominatim/Installation#Compiling_the_Required_Software) and there is no information to install osm2pgsql here. For importing osm data into database we are just using this command as given in the link. Do I need to compile osm2pgsql first? 

    ./utils/setup.php --osm-file <your planet file> --all [--osm2pgsql-cache 18000] 2>&1 | tee setup.log

**Comment by rakeshsukla53** [comment]
@mtmail Any suggestion how should make it work ? osm2pgsql is compatible with 64bit
![capture10](https://cloud.githubusercontent.com/assets/9192661/9234517/4d034b1c-4107-11e5-9c66-5e961f1e2c82.JPG)

**Comment by lonvia** [comment]
Could you please check that you are using the latest Nominatim version 2.4? The initial screen shot seems to come from an older Nominatim version.

**Comment by rakeshsukla53** [comment]
I am using 2.3 right now, but will update and try again

**Comment by rakeshsukla53** [comment]
@lonvia It is giving me the same error :( 
![capture11](https://cloud.githubusercontent.com/assets/9192661/9235494/0d07732a-410d-11e5-8989-b43721edfd1a.JPG)

**Comment by mtmail** [comment]
I will install Finland on a virtual machine with swap=0 (https://www.digitalocean.com/pricing/) in a couple of hours to rule out low memory. Thanks for posting the operating system you use and postgres parameter, that's helpful.

**Comment by rakeshsukla53** [comment]
@mtmail  @lonvia  I tried with a very small dataset (8MB) when I try to run it through setup.php, the same error comes up.

**Comment by rakeshsukla53** [comment]
My kernal tunning parameters : 

    sysctl -w kernel.shmmax=4404019200
    sysctl -w kernel.shmall=1075200
    sysctl vm.overcommit_memory=2
    sysctl vm.swappiness=10
    
    echo "kernel.shmmax=4404019200" >> /etc/sysctl.conf
    echo "kernel.shmall=1075200" >> /etc/sysctl.conf
    echo "vm.overcommit_memory=2" >> /etc/sysctl.conf
    echo "vm.swappiness=10" >> /etc/sysctl.conf   

Do you think they are correct?

**Comment by rakeshsukla53** [comment]
@mtmail @lonvia  My kernal tunning parameters
![capture12](https://cloud.githubusercontent.com/assets/9192661/9236540/7578bc06-4113-11e5-9373-376702d54a4c.JPG)

**Comment by rakeshsukla53** [comment]
@mtmail @lonvia  Could you help me to include '--cache-strategy sparse` parameter in my file. I am not sure how to include this in the setup.php file and how to include in the command then? Any help will be appreciated. Thanks
![capture13](https://cloud.githubusercontent.com/assets/9192661/9236732/84ce6e8e-4114-11e5-96cd-c23243005933.JPG)

**Comment by rakeshsukla53** [comment]
Okay I fixed `--cache-strategy sparse` and used this command 

     ~/Nom1/Nominatim/utils/setup.php   --osm-file data/latest.osm.pbf   --all --osm2pgsql--cache-strategy sparse --osm2pgsql-cache 1024
but sadly same error :|

**Comment by mtmail** [comment]
I've setup a virtual machine on DigitalOcean.com with 2 cores, 2 GB RAM, 40GB SSD on Ubuntu 14.04 LTE 64bit. By default it has no swap partition.

Then I installed Nominatim 2.4.0 from http://www.nominatim.org/ and imported Finland data. I will copy&paste the full script including comments.

The setup runs fine, even with `--osm2pgsql-cache 512` (0.5GB).

I think in your installation you might have over-optimized the kernel or Postgres. You will see I didn't change any default settings, not even recommended ones. Did you take the optimization settings from http://koo.fi/blog/2015/03/19/openstreetmap-nominatim-server-for-geocoding/?

Anyway, I think it's best if you try to remove the optimization settings first and try again.

**Comment by mtmail** [comment]
## Digital Ocean
## Ubuntu 14.04 LTE, 64 bit
## 2GB RAM, 20GB SSD, no swap
## Linux 8gb 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

USERNAME=ubuntu

### 
### create ubuntu user
### 

if [[ ! `id -u $USERNAME` ]]; then
  useradd $USERNAME --create-home --shell /bin/bash
  
  # give sudo power
  echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99-$USERNAME-user
  chmod 0440 /etc/sudoers.d/99-$USERNAME-user
  service sudo restart
  
  # add basic .profile
  cp -r .ssh .profile .bashrc /home/$USERNAME/
  chown -R $USERNAME /home/$USERNAME/.*
  chgrp -R $USERNAME /home/$USERNAME/.*
  
  # now ideally login as $USERNAME and continue
  su $USERNAME -l
fi


USERNAME=ubuntu


sudo apt-get update -qq
sudo apt-get upgrade -y
sudo apt-get install -y build-essential libxml2-dev libgeos-dev libpq-dev libbz2-dev \
                        libtool automake libproj-dev libboost-dev  libboost-system-dev \
                        libboost-filesystem-dev libboost-thread-dev

###
### PostgreSQL 9.3 + PostGIS 2.1
###

sudo apt-get install -y postgresql-9.3-postgis-2.1 postgresql-contrib-9.3 postgresql-server-dev-9.3 

sudo sed -i "s/ident/trust/" /etc/postgresql/9.3/main/pg_hba.conf
sudo sed -i "s/md5/trust/"   /etc/postgresql/9.3/main/pg_hba.conf
sudo sed -i "s/peer/trust/"  /etc/postgresql/9.3/main/pg_hba.conf
sudo /etc/init.d/postgresql restart
sudo -u postgres createuser -s $USERNAME



###
### PHP for frontend
###
sudo apt-get install -y php5 php5-pgsql php-pear 
sudo pear install DB


IP=`curl -s http://bot.whatismyipaddress.com`
echo "<?php
   // General settings
   @define('CONST_Database_DSN', 'pgsql://@/nominatim');
   // Paths
   @define('CONST_Postgresql_Version', '9.3');
   @define('CONST_Postgis_Version', '2.1');
   // Website settings
   @define('CONST_Website_BaseURL', 'http://$IP:8089/nominatim/');
" > settings/local.php





###
### download Nominatim
###

wget http://www.nominatim.org/release/Nominatim-2.4.0.tar.bz2
bunzip2 Nominatim-2.4.0.tar.bz2
tar xf Nominatim-2.4.0.tar
mv Nominatim-2.4.0 Nominatim
cd Nominatim/


###
### compile Nominatim and osm2pgsql
###

./configure
make

cd osm2pgsql/
./autogen.sh
./configure && make && make install
cd ..


###
### download OpenStreetMap data
### 

wget http://download.geofabrik.de/europe/finland-latest.osm.pbf


###
### run setup
###

## memory usage according to 'top' before
##
KiB Mem:   2049956 total,   579964 used,  1469992 free,    16356 buffers
KiB Swap:        0 total,        0 used,        0 free.   463120 cached Mem

# 1GB is enough for Finland
./utils/setup.php --osm-file finland-latest.osm.pbf --all --osm2pgsql-cache 1000 2>&1 | tee setup.log

# [...]
# osm2pgsql SVN version 0.87.3-dev (64bit id space)
# 
# Using projection SRS 4326 (Latlong)
# NOTICE:  table "place" does not exist, skipping
# Allocating memory for dense node cache
# Allocating dense node cache in one big chunk
# Allocating memory for sparse node cache
# Sharing dense sparse
# Node-cache: cache=1000MB, maxblocks=128000*8192, allocation method=11
# Mid: pgsql, scale=10000000 cache=1000
# [...]
# Reading in file: /home/ubuntu/Nominatim/finland-latest.osm.pbf
# Processing: Node(23335k 191.3k/s) Way(2089k 16.58k/s) Relation(21720 1143.16/s)  parse time: 267s
# Node stats: total(23335376), max(3692192210) in 122s
# Way stats: total(2089210), max(365178527) in 126s
# Relation stats: total(21726), max(5428640) in 19s
# [...]
# node cache: stored: 23335376(100.00%), storage efficiency: 52.98% (dense blocks: 6936, sparse nodes: 18469650), hit rate: 100.00%
6 minutes

## Top when osm2pgsql is still running (about 80% finished)
KiB Mem:   2049956 total,  1976780 used,    73176 free,      552 buffers
KiB Swap:        0 total,        0 used,        0 free.  1387872 cached Mem

**Comment by pnorman** [comment]
fyi, with default settings, osm2pgsql has about a 1GB overhead for tracking the cache.

More precisely, it has NUM_BLOCKS*sizeof(ramNodeBlock) for the dense cache tracking, which on my 64-bit machine is 16 bytes * 2^(36-10) = 1024MB, plus <30 MB for sparse tracking.

**Comment by rakeshsukla53** [comment]
I did try the optimization techniques from the blog you shared, actually I followed the whole blog to install. I am going to try your steps and keep you updated. I totally agree with your point that there is some issue with the optimization steps which I have taken earlier because I have tried at least 50 different suggestion and not able to resolve it issue.

**Comment by mtmail** [comment]
Those optimizations might assume you have swap space and thus overcommit memory. Virtual machines on SSDs often no longer have swap space configured. Good luck!

**Comment by rakeshsukla53** [comment]
Hell yeah!! This is working now :) @mtmail @lonvia Thank you so much :) :)

**Comment by rakeshsukla53** [comment]
You saved my day time is 11:40pm now :D

**Comment by hackerunet** [comment]
Hi there I'm also trying to get this done but I'm having the memory allocated issue, how do I have to change setup.php to use the spare cache option? Can you please be more specific?
thanks

**Comment by lonvia** [comment]
After reading that blog post, i would say the culprit here is:

    sysctl vm.overcommit_memory=2

osm2pgsql needs to be able to overcommit. If you don't have tons of swap configured, it will bail out no matter what the cache setting is. Also, with less than 10GB of memory I would recommend to use no more than 10% of available RAM for postgresql's shared_buffers.

**Comment by tschoffelen** [comment]
For others experiencing this issue, this is the way to create a swap file:

    dd if=/dev/zero of=/root/myswapfile bs=1M count=8000
    chmod 600 /root/myswapfile
    mkswap /root/myswapfile
    swapon /root/myswapfile

**Comment by sofgarya** [comment]
..Just adding..
Also you can solve it adding AN EXTRA DISK only for swap. If you are able to attach a new volume to your server, it will help a lot, I added a volume of 30GB for swap and it worked for me.

**Comment by zheis2** [comment]
@rakeshsukla53 i have the same problem!. can you help me please?, just tell me what did you do.
 Im using ubuntu server 14.04 too.

**Comment by lonvia** [comment]
If you have been following the koo.fi blog post, the following command will fix the memory issues:

    sysctl vm.overcommit_memory=0
    echo "vm.overcommit_memory=0" >> /etc/sysctl.conf

If you still have the same error after that, get more RAM or swap.

**Comment by zheis2** [comment]
@lonvia  Just needed get more RAM, Thank you so much :3 !!

**Comment by wolfdat** [comment]
Hello guys,

I have the same problem even wen I run osm2pgsql for liechtenstein (small data). I have a VM running Ubuntu (64-bit) with 5GB of RAM. This is the error I get:

osm2pgsql --create --slim \--cache 512 --number-processes 2 --hstore \--style ~/osm/openstreetmap-carto/openstreetmap-carto.style --multi-geometry \~/osm/liechtenstein-latest.osm.pbf
osm2pgsql SVN version 0.88.1 (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=512MB, maxblocks=65536*8192, allocation method=11
Mid: pgsql, scale=100 cache=512
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: ~/osm/liechtenstein-latest.osm.pbf
Unable to open ~/osm/liechtenstein-latest.osm.pbf
Error occurred, cleaning up

---------------------------------------------------------------------
Here is some info about the performance of my machine
#memory usage according to top
KiB Mem:   5208300 total,  1586372 used,  3621928 free,    43784 buffers
KiB Swap:  2096124 total,        0 used,  2096124 free.   532136 cached Mem

My kernel parameters are
kernel.shmall = 18446744073692774399
kernel.shmmax = 18446744073692774399
vm.overcommit_memory = 0

Could you please help me. Thanks.

**Comment by lonvia** [comment]
@wolfdat The error message says it all.

We have now moved far away from the topic of this issue tracker (Nominatim) and this issue (memory issues). Not to mention that this issue has been marked as closed. Blocking this issue for going off-topic.

**Comment by mtmail** [comment]
Oh, wow, I missed the error message, too. @wolfdat, the important line is
`Unable to open ~/osm/liechtenstein-latest.osm.pbf`
