### ISSUE TITLE
Nominatim Data: DB Error : insufficient permission

### ISSUE THREAD

**Issue by rakeshsukla53** [twain47/Nominatim#308]
I followed all the instructions from this [link](https://github.com/twain47/Nominatim/issues/306) and [installation] (http://wiki.openstreetmap.org/wiki/Nominatim/Installation) to start a nominatim server as you can see in the image below. But it is showing Data: DB Error : insufficient permission at the top 

![capture16](https://cloud.githubusercontent.com/assets/9192661/9263337/314068c2-41ea-11e5-8a85-893112c90e8b.JPG)

and when I pass any query it is giving me an error as shown below. I have loaded only the finland data here right now and wondering why the insufficient error is coming. Could anyone provide me some help?

![capture17](https://cloud.githubusercontent.com/assets/9192661/9263356/581eabfc-41ea-11e5-8e39-4790d4a2d80a.JPG)

**Comment by rakeshsukla53** [comment]
@mtmail  @lonvia  Any suggestion?

**Comment by mtmail** [comment]
try http://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting#The_browser_shows_Could_not_get_word_tokens

**Comment by rakeshsukla53** [comment]
my username is azureuser and this configuration is same CentOS. Will it work for Ubuntu 14.04 as well ?

**Comment by rakeshsukla53** [comment]
My error is more on this side 
![capture20](https://cloud.githubusercontent.com/assets/9192661/9263535/0ab01912-41ec-11e5-977f-9b8c9dae1eb1.JPG)

**Comment by mtmail** [comment]
Which username is the Apache webserver using to handle requests? `top` should show that. On Ubuntu 14.04 the default is `www-data`.

If that user doesn't have permission inside the nominatim database you can try

```
sudo -u postgres psql nominatim

GRANT usage ON SCHEMA public TO "www-data";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "www-data";
```

**Comment by rakeshsukla53** [comment]
azureuser is my username which is currently handling the request as I can see my top

**Comment by rakeshsukla53** [comment]
Error removed :)

**Comment by rakeshsukla53** [comment]
You helped me so much @mtmail  thanks brother :) 
![capture20](https://cloud.githubusercontent.com/assets/9192661/9263972/db026cb6-41ef-11e5-979d-bba79abdfeff.JPG)

**Comment by rakeshsukla53** [comment]
@mtmail  now if i want to add California data using the same command `./utils/setup.php --osm-file california-latest.osm.pbf --all --osm2pgsql-cache 1000 2>&1 | tee setup.log ` it is showing me database already exists. Can I add the California data in the same database?

**Comment by mtmail** [comment]
Do you really need the Finland data? If not then just delete the database `sudo -u postgres dropdb nominatim` (or rename it, see Postgres documentation) and start the California import.

The next best option is to edit `settings/local.php` and change the database name (connection string) from `nominatim` to e.g. `nominatim_california` and start the import. Now you have two databases and would need to change your settings to switch between them. Both import (setup.php) and website read the same settings file.

The third option is to combine the two `*.pbf` files before an import with http://wiki.openstreetmap.org/wiki/Osmosis/. I think Finland and California are an odd combination so have doubts if that's what you want.

**Comment by rakeshsukla53** [comment]
I have removed the Finland database and downloading now for California. Next time I will modify the local.php file as you have mentioned.
