### ISSUE TITLE
issues with nominatim 2.4

### ISSUE THREAD

**Issue by chantalokh** [twain47/Nominatim#309]
hello everyone,
I am installing Nominatim 2.4 i've installed postgis and postgre and everything seems fine,
i've configured nominatim with the required libraries but when i run:
./utils/setup.php --all --osm-file /users3/osm00/data/franche-comte-latest.osm
it does not works, it only returns
Create DB
but when i run: ./utils/setup.php --create-functions it returns:
CREATE FUNCTION
...
NOTICE:  type "addressline" does not exist, skipping
...
ERROR:  type "wikipedia_article_match" does not exist
ERROR: pgsql returned with error code (3)

or ./utils/setup.php  --create-tables
NOTICE:  table "import_status" does not exist, skipping
DROP TABLE
CREATE TABLE
GRANT
NOTICE:  table "import_osmosis_log" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "import_npi_log" does not exist, skipping
DROP TABLE
...
ERROR:  relation "country_name" does not exist
ERROR:  relation "gb_postcode" does not exist
CREATE VIEW
NOTICE:  table "word" does not exist, skipping
...

Have you any idea about this?
Thanks in advance

**Comment by lonvia** [comment]
You need to find out where exactly the installation gets stuck. Drop the database and rerun the full installation command. Then check with `ps` or `top` which command is currently being executed.

**Comment by chantalokh** [comment]
hello @lonvia,
It was pear's db extention that was not found, i corrected the problem and everything works fine, but now i have another problem, the createsite works fine but when i try to query the page it returns 
Strict Standards: Only variables should be assigned by reference in /users3/osm00/source/Nominatim/lib/db.php on line 7

Strict Standards: Non-static method PEAR::isError() should not be called statically in /users3/osm00/source/Nominatim/lib/db.php on line 8
failedstring(19) "pgsql://@/nominatim" object(DB_Error)#2 (8) { ["error_message_prefix"]=> string(0)....
can it be an error with pear's extentions?
Thank you

**Comment by chantalokh** [comment]
for the blank page it was just a problem with the CONST_Website_BaseURL that was set to localhost in local.php and on another address in vhost.
i think now that everything works fine so i'll close this issue
thanks @lonvia
