### ISSUE TITLE
multiword objects not always found depending on search word

### ISSUE THREAD

**Issue by farfromrefug** [twain47/Nominatim#310]
If i do this
```
http://nominatim.openstreetmap.org/search?limit=100&q=Chavant&format=json&viewbox=5.727261565625668,45.18994227275281,5.735818482935429,45.18189747186374&bounded=1&addressdetails=1
```
i get no result

if i do this
```
http://nominatim.openstreetmap.org/search?limit=100&q=Pathe&format=json&viewbox=5.727261565625668,45.18994227275281,5.735818482935429,45.18189747186374&bounded=1&addressdetails=1
```
i get the cinema "Pathé Chavant"
I think both should return the cinema

**Comment by lonvia** [comment]
That is a know issue with partial searches. There are lots of places that exactly match your query in the given bounding box, so those are preferred. There is no way for Nominatim to know that the 'Pathe' part in the cinema can be left out, so there is no way to fix that issue unless we add a lot of world knowledge to Nominatim.

**Comment by farfromrefug** [comment]
I am not sure i get what you mean. I dont want "Pathe" to be left out. I am wondering how the search is actually done:
- when searching for "Chavant", is "Pathe Chavant" actuallly found but filtered out?
- how is the search actually done? Is it a query? Or is a mapping already stored in the db to make the search faster?
- is it related to the viewbox? Would it work if i had a smaller viewbox? (the last questions might answer this).

Thanks

**Comment by lonvia** [comment]
Nominatim first tries to find a perfect match for your query, only if that fails it will resort to partial matches. There are plenty of bus stops called 'Chevant' in that area which happen to be perfect matches, so the partial match with the cinema will never be returned in the first round of results. Even when it eventually does resort to partial match, there are so many names that have 'Chavant' somewhere in their name that there is no guarantee that the cinema will show up very high on that list.

**Comment by farfromrefug** [comment]
Ok so i get what you mean by too many results. But just so i understand you mean osm results? and not nominatim results?
I am asking because when i do this (removed the limit):
```
http://nominatim.openstreetmap.org/search?q=Chavant&format=json&viewbox=5.727261565625668,45.18994227275281,5.735818482935429,45.18189747186374&bounded=1&addressdetails=1
```
I don't get so many results, just around ten.
And you are right those are bus, tram, stop ...

So seeing that few results, i am guessing nominatim first find a lot of matching osm results (maybe ways, rel, ...) and then filters them with the bounding box and maybe class/subtype?

If that s the case then i understand everything, and it will come to a feature request for filtering possible results ;)
If that s NOT the case then i don't get where the "filter" is done and why i get so few results with the above request

**Comment by lonvia** [comment]
Omitting the limit parameter doesn't mean that you get all results (we need to protect our servers from crazy requests after all). The default for limit is 10, so you just got what you ask for. And before you try a higher limit there is a maximum for the limit as well. Asking for 'all' objects is not possible.

Furthermore, Nominatim works so that if there are any prefect matches for the result, it will not even look for partial matches. So even with a limit=100 you would get only one result if there is exactly one object with name 'Chevant' (yes, that's a OSM object) in your bbox, even if there are tons of partial matches at the same time.

The search for the name and the filtering by bbox happen at the same time, i.e. the query is "look for all Chevants in this area".

**Comment by farfromrefug** [comment]
For the limit i was not trying to get more results. Actually i thought the default limit was a lot higher and i wanted to protect my app ;) So i will put it to 10!
Now i get the perfect match first, it makes total sense for the search feature.

I guess what i am looking for is a "around" feature with a query parameter. Then i suppose getting partial matches as well as perfect matches would make sense.

Thanks a lot Sarah for taking the time to answer and explain everything.
Best

**Comment by cascafico** [comment]
Two apparently similar searches, none of them submitted exactly: 

actual street name "Largo Beata Benvenuta Boiani"
search: "largo boiani 11, cividale del friuli"
no matches

actual street name "Stretta Giacomo Matteotti"
"stretta matteotti 11, cividale del friuli":
matches

**Comment by tanzeelrana** [comment]
Is it possible to query for all the possible results ?
