### ISSUE TITLE
Lack of CORS policy in HTTP header renders routing on openstreetmap.org unusable.

### ISSUE THREAD

**Issue by yhoyhoj** [twain47/Nominatim#314]
I can't use routing on Openstreetmap.org because Firefox disallows the "cross-origin request" to nominatim.openstreetmap.org. The message below appears in the console when I type in the form.
Firefox error message (translated):
```
Blocking of a Cross-Origin Request : the « Same Origin » policy doesn't allow to consult content at http://nominatim.openstreetmap.org/search?q=A%C3%A9roport%20Roissy%20Charles%20de%20Gaulle&format=json. Reason: the CORS header « Access-Control-Allow-Origin » is missing.
```
If, as I understand it, nominatim has a public search API, wouldn't a `Access-Control-Allow-Origin: *`  in the header correct this without drawbacks ?

**Comment by lonvia** [comment]
Works fine for me:

~~~
me@machine:~$ wget -S -O /dev/null 'http://nominatim.openstreetmap.org/search?q=foo&format=json'
--2015-08-25 15:06:35--  http://nominatim.openstreetmap.org/search?q=foo&format=json
Resolving nominatim.openstreetmap.org (nominatim.openstreetmap.org)... 128.40.45.204
Connecting to nominatim.openstreetmap.org (nominatim.openstreetmap.org)|128.40.45.204|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Tue, 25 Aug 2015 13:06:35 GMT
  Server: Apache/2.4.7 (Ubuntu)
  X-Powered-By: PHP/5.5.9-1ubuntu4.11
  Access-Control-Allow-Methods: OPTIONS,GET
  Access-Control-Max-Age: 8640000
  Access-Control-Allow-Origin: *
  Connection: close
  Transfer-Encoding: chunked
  Content-Type: application/json; charset=UTF-8
Length: unspecified [application/json]
Saving to: ‘/dev/null’
~~~

Note that we had server issues this morning, so you might have received a 503 error from the server. They indeed don't come with a CORS header but I don't think that should be a problem.

**Comment by yhoyhoj** [comment]
I thought Firefox was stricter than my other browsers and that something was actually missing in the header but the cause was a Firefox add-on : HTTPS Everywhere. Apparently it's breaking CORS.
So, my mistake, not enough troubleshooting on my side. Thank you !
