### ISSUE TITLE
geocoding fails for part of street name

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#316]
I am trying to geocode some addresses and I encountered in my opinion wrong behavior of Nominatim.

I am trying to geocode address: Poland, Olsztyn, Wyszyńskiego 16. The request I am making looks like this:

http://nominatim.openstreetmap.org/search?format=json&street=wyszynskiego%2016&city=olsztyn&country=pl

It does not return exact location. But when I provide detailed name of street:

http://nominatim.openstreetmap.org/search?format=json&street=kardynala%20stefana%20wyszynskiego%2016&city=olsztyn&country=pl

it works fine. 

By detailed name of street I mean "Kardynała Stefana Wyszyńskiego" instead of "Wyszyńskiego". "Kardynała" means cardinal (and is often omitted), "Stefana" is first name (which is often omitted).   

Is it how the geocoding is supposed to work?

**Comment by lonvia** [comment]
That's another variation of issue #94.

**Comment by sanitas2** [comment]
Correct me if I am wrong. Mappers sometimes provide full names of street, sometimes not. That means that if you want to search for an address you have to make at least two queries to Nominatim: one with surename of street's patron, second with full name. That basically means to reliably use Nominatim I need to have database of street names, match each query to street from database and query Nominatim with each variant of street name. That's right?

This issue is known at least since Nov 9, 2013 and it doesn't look like it is going to be fixed soon. If that's correct I would at least update documentation how badly Nominatim works.

**Comment by mtmail** [comment]
You're right. There is currently no feature inside Nominatim that does a retry query based on this (Polish/Western European) rule, either by country or language. The next best approach for you is to query Nominatim multiple times while removing words. We have plans to make developing country/language specific features easier but there is no timeline. I'd say it's far from 'soon'.

The limit on Nominatim development is the time volunteers can spedt. Some feature requests are years old, older than 2013, and not easy to develop. We also need to spend time just keeping the system running under ever-increasing data and query volume.

> at least update documentation how badly Nominatim works

Sorry, that Nominatim doesn't work for your use-case. We value all feedback and bug reporst, even though it may currently seem we just add it to a long list of known issues.

**Comment by sanitas2** [comment]
Sorry for harsh words. I had wrong expectations. I thought that locating addresses would be the most important feature of Nominatim and that it would work flawlessly. I did not take into account that it's work in progress.

Your suggestion about querying Nominatim multiple times while removing words solves only half of the problem. In cases when user provides short street name version I would have to do opposite: query Nominatim while adding words. But I have no knowledge which words to add...

The speed of development surprises me. That's probably not my business, but I think something should be done to fix this. People probably would like to contribute somehow, but there's no guide to the project. Also Nominatim is quite important for OSM, even within OSM community there might be people who could help, but they probably don't even know in what state project is. Apart from that there are some projects like Google Summer of Code or hacktoberfest which could attract contributors from outside of OSM.

**Comment by manusoftar** [comment]
> 
> 
> You're right. There is currently no feature inside Nominatim that does a retry query based on this (Polish/Western European) rule, either by country or language. The next best approach for you is to query Nominatim multiple times while removing words. We have plans to make developing country/language specific features easier but there is no timeline. I'd say it's far from 'soon'.
> 
> The limit on Nominatim development is the time volunteers can spedt. Some feature requests are years old, older than 2013, and not easy to develop. We also need to spend time just keeping the system running under ever-increasing data and query volume.
> 
> > at least update documentation how badly Nominatim works
> 
> Sorry, that Nominatim doesn't work for your use-case. We value all feedback and bug reporst, even though it may currently seem we just add it to a long list of known issues.

I'm afraid it is not just that Nominatim doesn't work for his use-case, the real thing is that it is just not usefull if you are forced to use full street names, if it, at least had someway of querying by part of the name and get all the posible names and then let the user indicate which one is the correct street it could be useful, but as it is it defeats the porpous of geocoding at all.
