### ISSUE TITLE
geocoding fails for numerals in street name

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#317]
I am looking for:
http://nominatim.openstreetmap.org/?country=pl&city=ulanow&street=3-go%20maja%2019&format=json&state=podkarpackie
and there's nothing. 

When I look for:
http://nominatim.openstreetmap.org/?country=pl&city=ulanow&street=3%20%20maja%2019&format=json&state=podkarpackie
it works.

In second search I changed "3-go maja" to "3 maja" (which is basically the same). In English the difference between those two streets would be like "1 May" vs "1st of May".

**Comment by lonvia** [comment]
Polish variant of issue #298, closing here.
