### ISSUE TITLE
Nominatim installation 

### ISSUE THREAD

**Issue by crookedcircle** [twain47/Nominatim#321]
Is there anyone who can help in installing nominatim.. I have tried it couple of times and haven't been successful.. 

I can share my server access if need be.. the problem when i try to browse the same it gives error.. forbidden access..is although all the steps were successful while installation, 
I am not sure if anything is missing or what is wrong with installation. I have followed the steps as per the wiki link.. but unsuccessful.. 

please help..

**Comment by lonvia** [comment]
Best is probably to ask on the #osm-nominatim channel on [IRC](http://wiki.openstreetmap.org/wiki/IRC).
