### ISSUE TITLE
ltmain.sh not found

### ISSUE THREAD

**Issue by crookedcircle** [twain47/Nominatim#324]
Thanks for the previous answer.. this is a new issue which i am facing now.. here is the log

[/srv/Nominatim/Nominatim]# sudo ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I osm2pgsql/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory osm2pgsql to autoreconf
autoreconf: Entering directory `osm2pgsql'
autoreconf: running: aclocal --force -I m4
autoreconf: running: libtoolize --copy --force
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:34: required file `../../ltmain.sh' not found
autoreconf: automake failed with exit status: 1

**Comment by crookedcircle** [comment]
Posting it again for better understanding.. sorry for the previous one
[/srv/Nominatim/Nominatim]# sudo ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I osm2pgsql/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory osm2pgsql to autoreconf
autoreconf: Entering directory `osm2pgsql'
autoreconf: running: aclocal --force -I m4
autoreconf: running: libtoolize --copy --force
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:34: required file `../../ltmain.sh' not found
autoreconf: automake failed with exit status: 1

**Comment by crookedcircle** [comment]
where as libtool is already installed 

[/srv/Nominatim/Nominatim/osm2pgsql]# libtool --version
ltmain.sh (GNU libtool) 2.2.6b
Written by Gordon Matzigkeit <gord@gnu.ai.mit.edu>, 1996

Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by lonvia** [comment]
Looks like your autotools are too old.
