### ISSUE TITLE
Cannot compile - tagtrasform.cpp and lua lib

### ISSUE THREAD

**Issue by Freek07** [twain47/Nominatim#325]
I'm compiling on Debian with installed liblua 5.1, 5.2 and 5.3 and I get the error below. Any ideas?

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -pthread -I/usr/include/postgresql -I/usr/include/libxml2 -I/usr/include -I/usr/include -I/usr/include -DOSM2PGSQL_DATADIR=\"/usr/local/share/osm2pgsql\" -Igeos-fallback -I/usr/include/lua50 -I/usr/include -g -O2 -MT tagtransform.lo -MD -MP -MF .deps/tagtransform.Tpo -c tagtransform.cpp  -fPIC -DPIC -o .libs/tagtransform.o
tagtransform.cpp: In function 'unsigned int {anonymous}::lua_filter_rel_member_tags(lua_State*, const char*, keyval*, int, keyval*, const char* const*, int*, int*, int*, int*)':
tagtransform.cpp:372:33: error: 'lua_tointeger' was not declared in this scope
     *roads = lua_tointeger(L, -1);
                                 ^
tagtransform.cpp: In constructor 'tagtransform::tagtransform(const options_t*)':
tagtransform.cpp:430:21: error: 'luaL_newstate' was not declared in this scope
   L = luaL_newstate();
                     ^
tagtransform.cpp:431:18: error: 'luaL_openlibs' was not declared in this scope
   luaL_openlibs(L);
                  ^
tagtransform.cpp:432:56: error: 'luaL_dofile' was not declared in this scope
   luaL_dofile(L, options->tag_transform_script->c_str());
                                                        ^
tagtransform.cpp: In member function 'unsigned int tagtransform::lua_filter_basic_tags(OsmType, keyval*, int*, int*)':
tagtransform.cpp:534:29: error: 'lua_pushinteger' was not declared in this scope
     lua_pushinteger(L, count);
                             ^
tagtransform.cpp:543:37: error: 'lua_tointeger' was not declared in this scope
         *roads = lua_tointeger(L, -1);
                                     ^
tagtransform.cpp:557:33: error: 'lua_tointeger' was not declared in this scope
     filter = lua_tointeger(L, -2);
                                 ^
Makefile:1155: recipe for target 'tagtransform.lo' failed
make[2]: *** [tagtransform.lo] Error 1
make[2]: Leaving directory '/home/may/Downloads/Nominatim-2.4.0/osm2pgsql'
Makefile:827: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/may/Downloads/Nominatim-2.4.0/osm2pgsql'
Makefile:375: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by lonvia** [comment]
Looks like a you are using the wrong lua version. I see `-I/usr/include/lua50` in your compilation command which I suspect is for lua 5.0.

**Comment by lonvia** [comment]
Note to self on this: the lua tagtransform should be actively disabled during compilation as we don't need it for nominatim.

**Comment by lonvia** [comment]
lua will no longer be configured with cmake,

**Comment by VonTalavang** [comment]
how do i disable lua ????

**Comment by mtmail** [comment]
@VonTalavang Please don't comment on closed, possibly unrelated, issues from 6 months ago. If you have a current/new question please create a new issue and add relevant details, for example which operating system, version and Nominatim version you're using.
