### ISSUE TITLE
--osm2pgsql-cache X parameters

### ISSUE THREAD

**Issue by giacomone83** [twain47/Nominatim#327]
Hi guys, i have little doubt, I tried to find it out over google but I found conflicting opinions.
I'm installing nominatim 2.3.1 following the wiki guide. For the map import I use the command:

    ./utils/setup.php --osm-file <map> --all --osm2pgsql-cache <x> 2>&1 | tee setup.log

Now I would like to know how to set the 'x' parameter. Someone said that I have to set it with the amount value of my machine RAM, other said to set it with half of my machine RAM. Still others say to set it with '18000' regardless the amoun of my RAM.

Please help me because I wouldn't make mistakes beacuse the process is damned long and I don't want to restart it again.

Thanks a lot
Giacomo

**Comment by lonvia** [comment]
It depends on what you want to import. For the planet you would ideally use 24000 at the moment. With that all nodes would fit in the cache. If you have a smaller extract, you can reduce the amount according to the size. You should give no more than 3/4 of your available RAM and keep an eye on your memory usage. If your machine starts swapping heavily, reduce the number.

**Comment by giacomone83** [comment]
Oh God I have start indexing european map (15.8 gb) with that value fixed to 18000 but I have 16gb RAM on my virtual machine! The process was started on 21/10 and it keep running without errors (it seems..). What can happen if I set that parameters with a value greater than my RAM?? Can I reduce than while the import is running?? I use nominatim 2.3.1.

Thanks a lot

**Comment by lonvia** [comment]
osm2pgsql overcommits the memory but you will be fine as long as it doesn't actually touch the memory because it needs it. If it does need more than you have, it will start swapping. You cannot change the value after you have started the process.
