### ISSUE TITLE
Nominatim - not mobile friendly?

### ISSUE THREAD

**Issue by edent** [twain47/Nominatim#330]
Pointing a mobile browser to a search - e.g. https://nominatim.openstreetmap.org/search?q=5.71,-1.23 - results in a page which isn't very mobile friendly.
![14469374811770](https://cloud.githubusercontent.com/assets/837136/11017819/4c1b5d70-85a4-11e5-865b-83f134811ac9.jpg)

Compare to the normal OSM results
![14469374811941](https://cloud.githubusercontent.com/assets/837136/11017820/50c12ed6-85a4-11e5-8d90-d19e06f6545e.jpg)

Problem occurs on Android Lollipop. Tested on Opera, Firefox, Chrome.

**Comment by mtmail** [comment]
There's a new mobile-friendly frontend coming, it's 80% ready.

![brighton-search smallscreen](https://cloud.githubusercontent.com/assets/3727288/11017839/4909f71e-85ad-11e5-9268-8b87a5a79450.png)

**Comment by lonvia** [comment]
Fixed by #350.
