### ISSUE TITLE
Geocoding fails for Nędza

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#331]
I am looking for an address in city called Nędza:

http://nominatim.openstreetmap.org/?country=pl&accept-language=pl&city=N%C4%99dza&addressdetails=1&street=Kopernika%2010&format=json&state=%C5%9Al%C4%85skie

The result points in completely wrong place:
display_name: "10, Mikołaja Kopernika, Przyjaźń, Jastrzębie Górne, Jastrzębie-Zdrój, województwo śląskie, 44-335, Polska",
which has nothing to do with Nędza.

**Comment by lonvia** [comment]
There are a lot of place=hamlet around this address, among them http://www.openstreetmap.org/node/712995743 which Nominatim considers might be relevant for that address. Because the house number you are looking for is missing in OSM, the address is the closest direct match.

**Comment by sanitas2** [comment]
Is it supposed to work that way?

For me that's kind of strange. There is a point on the map, which is inside administrative border of Jastrzębie-Zdrój city, but Nominatim assumes its city is not "Jastrzębie-Zdrój" but takes it from hamlet node few kilometers away. It does no seem to be right.

Also, the Nędza I would expect to get results from is located here:
http://www.openstreetmap.org/#map=19/50.16138/18.31399&layers=N
it has Mikołaja Kopernika street, but buildings there don't have numbers filled. Nonetheless, if I were Nominatim I would consider this place to be a better match.

**Comment by lonvia** [comment]
No, I don't think it is supposed to work that way. That's why I didn't close this issue. Proper handling of place=hamlet is a really difficult issue because the data in OSM is really messy. It's just not clear at the moment how to improve the use of place=hamlet, so I can't tell you when it will be changed and if it will solve your particular issue.
