### ISSUE TITLE
There could be better matcher for house numbers with letters

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#334]
I am looking for address with house number "224 B". In OSM exist both "224" and "224B". I would consider the "224B" much better match. But Nominatim gives me "224".

E.g.:
http://nominatim.openstreetmap.org/?country=pl&accept-language=pl&city=%C5%81%C4%85ka&addressdetails=1&street=224%20B&format=json&state=podkarpackie

**Comment by lonvia** [comment]
See also https://trac.openstreetmap.org/ticket/5256
