### ISSUE TITLE
`countrycodes` param not using all of the listed country codes.

### ISSUE THREAD

**Issue by rory** [twain47/Nominatim#337]
The [documentation](http://wiki.openstreetmap.org/wiki/Nominatim#Parameters) implies that you can use the `countrycodes` parameter to only return results that are in one of the listed countries.

However requests to: http://nominatim.openstreetmap.org/search?q=sydney&format=json&countrycodes=ie%2Cgb or http://nominatim.openstreetmap.org/search?q=sydney&format=json&countrycodes=ie,gb only return results in the UK (i.e. `gb`). None of the results in http://nominatim.openstreetmap.org/search?q=sydney&format=json&countrycodes=ie are returned.

**Comment by mtmail** [comment]
So `ie` works, `gb` works, but the combination `ie,gb` doesn't. That's weird indeed.

When I try http://nominatim.openstreetmap.org/search?q=hard+rock+cafe&format=json&countrycodes=es,de,fr I see results from three countries, so the feature at least isn't completely broken.

**Comment by mtmail** [comment]
http://nominatim.openstreetmap.org/search?q=hard+rock+cafe&format=json&countrycodes=ie,gb
does show cafes in both countries so we can rule out it's Ireland specific.

I'd say
http://nominatim.openstreetmap.org/search?q=sydney&format=json&countrycodes=ie,gb
finds two exact matches and the engine returns that without looking any further. The matches happen to be in `gb`.

When setting just `ie`, no exact match is found and a second search for imprecise matches is started. In this case `Sydney Parade` and `Sydney Parade Avenue`. Such street names don't exist in `gb` so all results are in `ie`.

Looking at `hard rock cafe` again I think the behavior might look unexpected but the filter feature itself works.

**Comment by lonvia** [comment]
@mtmail got it right. The issue is with exact matches vs. partial matches. As long as there is any exact match, partial matches won't be returned. That's intended behavior. So you either need to run a second query, excluding the places just found, or run separate queries for the two countries.
