### ISSUE TITLE
Unknown Postgres Function reported in Postgres logs

### ISSUE THREAD

**Issue by bisoldi** [twain47/Nominatim#338]
While running the minutely update, I am seeing the following two lines repeated over and over in the Postgresql logs.

2015-12-03 13:11:42 UTC ERROR:  function get_tagpair(unknown, unknown) does not exist at character 8
2015-12-03 13:11:42 UTC HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

In other examples of this error in the log, the unknown, unknown are replaced by specific tags, e.g. ('place', 'county') or ('landuse', 'grass'), etc.  The log is about 190MB over the last 2 days.

It is a full planet import, running with 32GB memory, 1.5TB diskspace and 8 processors.

Is this a problem?  If so, how do I fix it?

**Comment by lonvia** [comment]
This issue has been fixed in 27753fb8dbce6bb595f95bad637078ab2106d794 already in the git repo. You can apply this commit to your code if you like. I.e. simply remove the offending code. It is not used.
