### ISSUE TITLE
Import osm.bz2 diff file

### ISSUE THREAD

**Issue by tpham812** [twain47/Nominatim#341]
Hi,

Is the update.php script able to import osm.bz2 diff files or does it only import osc file? And if it does only import osc diffs, what is the best way to update the database?

Thanks

**Comment by lonvia** [comment]
You can import an osm file with `./utils/update.php --import file foo.osm.bz2 --index`. 

Try `./utils/update.php --help` for a full list of possible import targets.

**Comment by tpham812** [comment]
I tried the import with what you mentioned and it threw an error "org.openstreetmap.osmosis.core.OsmosisRuntimeException: This does not appear to be an OSM XML file." But my file is an OSM XML file.
