### ISSUE TITLE
DB Error:extension not found during installation.

### ISSUE THREAD

**Issue by TroyGitHub** [twain47/Nominatim#343]
Hi,

When  I follow the Nominatim Installation and when I run at Import and Index OSM data section with command "./utils/setup.php --osm-file /home/troy/Desktop/dallas.osm.pbf --all  2>&1 | tee setup.log" I got an error message:

WARNING: resetting threads to 1
Create DB
Setup DB
string(19) "pgsql://@/nominatim"
object(DB_Error)#4 (8) {
  ["error_message_prefix"]=>
  string(0) ""
  ["mode"]=>
  int(1)
  ["level"]=>
  int(1024)
  ["code"]=>
  int(-25)
  ["message"]=>
  string(29) "DB Error: extension not found"
  ["userinfo"]=>
  string(55) " [DB Error: extension not found] ** pgsql://@/nominatim"
  ["backtrace"]=>
  array(7) {
...........

BTW, does anyone know where the table "place" is from? When i checked nominatim codes, I didn't found any places on the table.

I am an newbie on Linux and Postgre. 
Thanks advanced! 
Troy

**Comment by lonvia** [comment]
You have not installed either hstore or postgis. On Debian/Ubuntu, make sure the following packages are there: `postgresql-contrib` and  `postgresql-9.x-postgis-2.x`(version depends on the available Postgres).

The `place` table is created by the osm2pgsql software, which does the initial loading of the OSM data.

**Comment by mtmail** [comment]
I added an entry to http://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting

**Comment by TroyGitHub** [comment]
![capture](https://cloud.githubusercontent.com/assets/3301669/11776388/a3b7d99c-a281-11e5-9e9e-a7f7884ee19c.PNG)

I run the install command you mentioned and they show me those items have been installed (I remember I installed them already at the very beginning). But I do not have an hstore extension list in my postgre database.

When I run "./utils/setup.php --osm-file /...." again, it mentioned the nominatim database exits and block here. So, I try to delete the nominatim database but failed, the attached is what my database looks like. 

I spent the whole afternoon to get how to drop the database and postgre commands, also try to use PgAdmin to connect to my postgre database, but still unlucky. 

Would you please give me some guides on them? 

Thanks,

Troy

**Comment by TroyGitHub** [comment]
Thanks Lonvia, but I installed the above command by following the guide. (actually I installed it again and it show me they are latest version now). The version is 9.3.10

Then, I remove the nominatim database and run the "./utils/setup.php...." again, same error happens. 
I have some suspects on the "Nominatim module reading permissions" section in guide page(http://wiki.openstreetmap.org/wiki/Nominatim/Installation#Nominatim_module_reading_permissions), I didn't run the command as I got the source code by git, so the source code are located at my root path by default:

 chmod +x ~/src
 chmod +x ~/src/Nominatim
 chmod +x ~/src/Nominatim/module

but I run "chmod +x ~/nominatim/module" instead and I got nothing happens. I am not sure if it looks normal.

Do you have any insights?
Thanks,
Troy

**Comment by twain47** [comment]
I believe the error means you do not have the php psql module installed.

Check you ran the following line in the install guide:

apt-get install php5 php-pear php5-pgsql php5-json php-db

**Comment by TroyGitHub** [comment]
Excellent! Thanks Twain47! Now I can import the osm file into Postgre.

Thanks for all of your help.
