### ISSUE TITLE
address searching fails for saints' streets 

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#351]
When I search for street: "św. Józefa" I get reasonable [result](http://nominatim.openstreetmap.org/search?format=json&street=%C5%9Bw.%20J%C3%B3zefa%20&city=rybnik&country=pl) - street with name "świętego józefa" is returned.

When I want to find some address on that street e.g. "św. Józefa 12" the [result](http://nominatim.openstreetmap.org/search?format=json&street=%C5%9Bw.%20J%C3%B3zefa%2012&city=rybnik&country=pl) contains some streets which did not show up earlier. Also I would expect the first result would contain best matched street (i.e. świętego józefa for św. józefa).

**Comment by lonvia** [comment]
Nominatim currently doesn't know about the abbreviation świętego -> sw. It is already on the [list of abbreviations](http://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#Polski_-_Polish) and will be added the next time around.
