### ISSUE TITLE
Wrong search result maybe due to tags place:neighbourhood and place:suburb?

### ISSUE THREAD

**Issue by Mittaa** [twain47/Nominatim#352]
Hi
When searching for street: Knudsvej, Roskilde, Denmark (http://nominatim.openstreetmap.org/search.php? q=Knudsvej%2C+Roskilde%2C+Denmark&polygon=1&viewbox=), I get a result where place:neighbourhood and place:suburb are wrong (Knudsvej is not a part of "Himmelev" or "Sankt Jørgensbjerg").
Is this search result wrong due to an error with Nominatim? 
When inspecting OSM I found that nodes (place:suburb="Himmelev" and place:neighbourhood="Sankt Jørgensbjerg") have no boundaries. If that's the root cause to the this problem, I would like to know if tags suburb and neighbourhood should be avoided or Is some way should be delimited (area, radius)?
Thanks in advance,
MittaaDK (OSM user)

**Comment by lonvia** [comment]
The best way to resolve these issues is to add an (approximate if necessary) boundary. In absence of a boundary Nominatim has to guess which of the surrounding nodes should be assigned.
