### ISSUE TITLE
Inconsistent results in nomination search

### ISSUE THREAD

**Issue by wiwwo** [twain47/Nominatim#353]
Hi there!
The following query returns correct data
https://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=barcelona+sant+pere+mes&format=json&limit=1
but a more detailed query returns no data
https://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=barcelona+sant+pere+mes+baix&format=json&limit=1

What am i doing worng? :-)

**Comment by mtmail** [comment]
For queries without separation of phrases, e.g. by comma, slashes, dashes, Nominatim will try (almost) every combination of words. The number of combination grows exponentially with the number of words and at some point it needs to end the search early.
With your query it helps to add a comma behind Barcelona.

https://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=barcelona,+sant+pere+mes+baix&format=json&limit=1

**Comment by wiwwo** [comment]
Aaaand it worked!
Thanks, that makes perfect sense! :)
