### ISSUE TITLE
PostGIS version is not correct.  Expected 2.1 found 2.2

### ISSUE THREAD

**Issue by santosharjun** [twain47/Nominatim#356]
./utils/setup.php --osm-file ../india-latest.osm.pbf --all --osm2pgsql-cache 18000 2>&1 | tee setup.log
Create DB
Setup DB
createlang: language "plpgsql" is already installed in database "nominatim"
CREATE EXTENSION
CREATE EXTENSION
ERROR: PostGIS version is not correct.  Expected 2.1 found 2.2

**Comment by lonvia** [comment]
As per installation documentation, change the PostGIS version in your settings/local.php:

    @define('CONST_Postgis_Version', '2.2');

**Comment by santosharjun** [comment]
Thanks. 
for others, it is settings/settings.php

**Comment by lonvia** [comment]
No, it's not. See http://wiki.openstreetmap.org/wiki/Nominatim/Installation#Customization_of_the_Installation

**Comment by santosharjun** [comment]
got it. Thanks Sarah for the clarification
