### ISSUE TITLE
Server requirements for Nominatim

### ISSUE THREAD

**Issue by santosharjun** [twain47/Nominatim#357]
Hi, I see very high server requirements for Nominatim. I have a basic question, do we require high end configuration for installation only? and can revert back to lower configuration for regular usage?

To describe it more clearly, I am using Microsoft Azure server for installing Nominatim.
1) for installation, I am using 8 core- 56GB RAM server with SSDs
2) can I scale down the server to 4 core-14GB RAM server post installation and setup?

PS: i am installing OSM only for India.

Thanks in advance

**Comment by mtmail** [comment]
That's a good approach. Depending on the number of queries per day even a 2core, 8GB RAM machine might work. But try the 4core machine first.

**Comment by santosharjun** [comment]
Thank you. others can comment, if they have new points. 

< closing the issue for now >
