### ISSUE TITLE
 2 or more cities

### ISSUE THREAD

**Issue by maxicabanillas78** [twain47/Nominatim#365]
as it is done to put more of a city

./utils/setup.php --osm-file brazil-latest.osm.pbf angola-latest.osm.pbf --all

**Comment by lonvia** [comment]
This is outside the scope of Nominatim. Merge your osm files before importing, for example using osmosis or [osmupdate](http://wiki.openstreetmap.org/wiki/Osmconvert#Merging_two_or_more_Geographical_Areas).
