### ISSUE TITLE
import into the table africa

### ISSUE THREAD

**Issue by maxicabanillas78** [twain47/Nominatim#366]
Hello and import the data from South America
./utils/setup.php --osm-file south-america-latest.osm.pbf --all

Now I need to import into the table africa

./utils/update.php --osm-file angola-latest.osm.pbf --all
?????????????????????????????

I could explain how this is done

I could explain step by step how to make

**Comment by mtmail** [comment]
You can't. You have to merge the two files before the import. That means a complete reimport.

The tool you're looking for is https://github.com/osmcode/osmium-tool
http://docs.osmcode.org/osmium/latest/osmium-cat.html, osmium or
http://wiki.openstreetmap.org/wiki/Osmconvert#Merging_two_or_more_Geographical_Areas
