### ISSUE TITLE
Apache configuration issue

### ISSUE THREAD

**Issue by KeilSeba** [twain47/Nominatim#369]
I have installed a Nominatim server sticking to [this excellent walk through][1]. However, I am not able to get the apache configuration to work.

my default-conf is specified as follows:

        ServerName maps.example.org

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/

        <Directory "/var/www/html/nominatim">
         Options FollowSymLinks MultiViews
         AddType text/html .php
        </Directory>
 
In Nominatim I specify the BaseUrl as:

     @define('CONST_Website_ @define('CONST_Website_BaseURL', '46.101.185.214/html/nominatim/')

setting up the server via:

     ./utils/setup.php --create-website /var/www/html/nominatim
    Symlinks created

returns
    
    WARNING: Unable to access the website at 46.101.185.214/html/nominatim/
    You may want to update settings/local.php with @define('CONST_Website_BaseURL', 'http://[HOST]/[PATH]/');
    Setup finished.

However, the server is accessible [http://46.101.185.214/html/nominatim/index.php yet it looks somewhat awkward.

Trying the search returns:

    Not Found 404

I guess the problem is the apache configuration but i cannot find a working constellation. One hint might be the url after klicking "search":

    http://46.101.185.214/html/nominatim/46.101.185.214/html/nominatim/46.101.185.214/html/nominatim/search.php?q=test&viewbox=

Therefore my question: What do I have to change in my configuration files in order to get this working?

Thank you very much!

  [1]: http://koo.fi/blog/2015/03/19/openstreetmap-nominatim-server-for-geocoding/
  [2]: http://46.101.185.214/html/nominatim/index.php #

**Comment by mtmail** [comment]
In `settings/local.php` try setting

` @define('CONST_Website_ @define('CONST_Website_BaseURL', 'http://46.101.185.214/html/nominatim/')`

I think the it's just the missing `http://`

**Comment by KeilSeba** [comment]
Thank you so much for your excellent answer... I fell a little stupid though ;)
