### ISSUE TITLE
Error Encountered While Trying to Perform Indexing 

### ISSUE THREAD

**Issue by morehous** [twain47/Nominatim#373]
Thank you in advance for looking at this. I am trying to load a planet file. I get through the PBF import fine but when it gets to the indexing I get the following error message. It looks like a piece of data was corrupted along the way. Have you seen this before?

I am running Ubuntu 15.10 on a 16GB MacMini (1TB SSD drive). I am using Postgres 9.4.

WARNING:  placex_update N 869668322
NOTICE:  SRID value -757897 converted to the officially unknown SRID value 0
CONTEXT:  PL/pgSQL function placex_update() line 91 at assignment
index_placex: UPDATE failed: ERROR:  Unknown geometry type: -1820510576 - Invalid type
CONTEXT:  PL/pgSQL function placex_update() line 91 at assignment

**Comment by lonvia** [comment]
I haven't seen that before, sounds very much like a corrupted database. What is the output of the two SQL queries `select st_srid(geometry) from place where osm_type = 'N' and osm_id = 869668322` and `select st_srid(geometry) from placex where osm_type = 'N' and osm_id = 869668322`?

**Comment by morehous** [comment]
Unfortunately I restarted the load. If it happens this go around I will perform this query. Thank you for your help!

**Comment by lonvia** [comment]
Closing for now. Please reopen if that becomes a repeated issue.

**Comment by morehous** [comment]
Sorry about that Sarah. Have been away from my office. I will try and recreate the problem.

v/r,
Mike
