### ISSUE TITLE
Nominatim postgresql createuser problem?

### ISSUE THREAD

**Issue by astritzeqiri** [twain47/Nominatim#374]
When i want to sudo create:
sudo -u postgres createuser -s usernam

it creates the user than when i do:

createuser -SDR www-data 

i get this error:

createuser: could not connect to database postgres: FATAL:  role "root" does not exist

**Comment by lonvia** [comment]
As the docs say, you must not run the installation as root. The second createuser command (in fact, all commands) should be run from the same user you created an account for with the first createuser command.
