### ISSUE TITLE
Search Results incomplete

### ISSUE THREAD

**Issue by goddyale** [twain47/Nominatim#375]
Hello:
I think the application is awesome but i found a bug and would like to report it. When searching for "Lincoln" all suggestions displayed belong to United States of America:

- Lincoln, Lancaster Country, Nebraska, United States of America
- Lincoln, Logan Country, Illinois, United States of America
- Lincoln Country, Kansas, United States of America

the search results are missing the suggestion for United Kingdom. However if you search for "Linkoln " in additions of the United States results also appear the United Kingdom result.
Please advice,
Thanks,

**Comment by mtmail** [comment]
Where/how did you search?

In my browser, which is set to en-GB language, when I search on http://www.openstreetmap.org/ the first result is `Lincoln, Lincolnshire, East Midlands, England, United Kingdom`.

Nominatim (and openstreetmap.org) doesn't save your previous searches. It does bias results based on the current shown map boundaries (e.g. if you zoomed into the United States) and browser language though.

**Comment by goddyale** [comment]
Hello:

I apologize for the misunderstanding, i don't use a browser, i use an HTTP request as follows:

http://nominatim.openstreetmap.org/search?format=xml&addressdetails=1&accept-language=en-gb&q=Lincoln

and the results do not include the suggestion for United Kingdom. I also tried to use the country code to restrict the search only to United Kingdom "&countrycode=uk", but it seems to be also working incorrect. 

Please advice,
Thanks,

**Comment by mtmail** [comment]
Ah makes sense now.

You have several options:

1. add `&countrycode=gb` (based on the https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 standard)
2. add `, uk` to the end of the query
3. set `&viewbox=<left>,<top>,<right>,<bottom>&bounded=1`
4. set `&viewbox=<left>,<top>,<right>,<bottom>`

The first three are filters, e.g. a search for `Seattle` would return no results. The forth option sets a bias which ranks places inside the viewbox higher.

The default language is already `en` so you wouldn't have to set `&accept-language` in the API call.

**Comment by lonvia** [comment]
Tiny correction: the parameter is called `countrycodes=gb`.

If you want really all Lincolns in the world, you could also try increasing the number of results presented by adding `limit=20`. There are so many Lincolns in the US that Nominatim simply doesn't deem the UK one important enough to be shown in the first batch of results.

I'll ponder a bit if we should actually be increasing the default limit a bit. The hardware should be up to it these days.
