### ISSUE TITLE
$aPointPolygon can be uninitialized in lib/Geocode.php

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#382]
I need a second set of eyes here.

In this line the variable `$aPointPolygon` is used.
https://github.com/twain47/Nominatim/blob/78a29b5a876d0c7d4c8b9ccab9f45b15780b4a22/lib/Geocode.php#L1735

But the variable is only initialized in the `if (CONST_Search_AreaPolygons)` about 50 lines prior. So without that constant set it would fail. The constant is set to `true` during standard Nominatim installation.

Should the bounding box logic be dependent on the constant being `true` or independent?

**Comment by lonvia** [comment]
It is supposed to be an independent fallback for setting the bounding box.  You might as well set $aResult['aBoundingBox'] directly.

**Comment by mtmail** [comment]
Ok. I'm close to finish returning geometries for reverse search. It will be bigger pull request, tests already work.
