### ISSUE TITLE
Keyword list on details page wrong

### ISSUE THREAD

**Issue by lonvia** [twain47/Nominatim#383]
The details page can optionally show the search keywords for the place, e.g. http://nominatim.openstreetmap.org/details.php?place_id=143094835&keywords=1

Displaying these keywords has been broken since the move to the new layout. Note that for all keywords the word_id should be listed and if they are partial or not (i.e. if word_token starts with a space).

CC @mtmail

**Comment by mtmail** [comment]
fixed in https://github.com/twain47/Nominatim/commit/9fb413a1

screenshot:
![2](https://cloud.githubusercontent.com/assets/3727288/13395088/bcac38d8-deec-11e5-98a0-572835aa6026.png)

**Comment by lonvia** [comment]
I would prefer to have the layout of 'Address Keyword' for the 'Name Keyword' as well.

**Comment by mtmail** [comment]
added in https://github.com/twain47/Nominatim/pull/384
