### ISSUE TITLE
Does not find addresses containing comma

### ISSUE THREAD

**Issue by alchemyx** [twain47/Nominatim#386]
There is address in Świnoujście, Poland - wyb. Władysława IV 26, 27. 

When I do reverse search on Nominatim and click it I get:

```26, 27, Wybrzeże Władysława IV, Wyspiańskiego, Śródmieście, Świnoujście, województwo zachodniopomorskie, 72-600, Polska (House)
53.9075073,14.2492997```

Link to details - https://nominatim.openstreetmap.org/details.php?place_id=42452614

But If I do enter it that way into search box on Nominatim: "26, 27, Wybrzeże Władysława IV, Świnoujście" it does not find anything. I guess it is because extra comma in house number. Tried escaping it as ```\,``` but it did not help.

**Comment by lonvia** [comment]
The OSM tagging does not support house numbers with comma. A comma always means two separate numbers. Nominatim interprets it the same way. Only exception is when displaying the result. There the complete term with commas is shown. Supporting commas in house numbers for search is definitely not possible.
