### ISSUE TITLE
Searching fails for Jastrzębie-Zdrój

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#392]
I am looking for address: Jastrzębie-Zdrój, Turystyczna 7: 
http://nominatim.openstreetmap.org/search?format=json&street=turystyczna%207&city=Jastrz%C4%99bie-Zdr%C3%B3j&country=pl

It does not return proper address which is located at:
http://www.openstreetmap.org/node/2167668683

**Comment by mtmail** [comment]
Thanks!

Looks like at least 5 results have the `place:house_number` 7 attached although based on OpenStreetMap data it should only be one.

http://nominatim.openstreetmap.org/search?format=html&street=turystyczna%207&city=Jastrz%C4%99bie-Zdr%C3%B3j&country=pl

On my private world-wide installation I can't reproduce this issue.
