### ISSUE TITLE
Highway type information not returned 

### ISSUE THREAD

**Issue by borntoburnyo** [twain47/Nominatim#393]
Hi there,

When I use the Nominatim reverse geocoding service, the output does not contain highway classification information, like: "highway=primary". The only way as I could do now, is to parse the detail.php page and get the information. However huge amount of requests would pose heavy burden on server. In the mean time, I might be thrown into blacklist for the unwise behavior. 

I'm wondering if the next release could fix the issue.

Yours 
Respectively

**Comment by lonvia** [comment]
If you use jsonv2 format, the highway classification is already included.

For example http://nominatim.openstreetmap.org/reverse.php?format=jsonv2&lat=48.601598649000515&lon=2.250394821166992&zoom=17 yields:

    ...
    "category": "highway",
    "type": "residential",
    ...

**Comment by borntoburnyo** [comment]
That's awsome! Thank you so much for the information.

**Comment by mtmail** [comment]
The `json` and `jsonv2` output is generated from in two different (PHP) files. If something is missing in the `json` format we simply forgot to add it.

**Comment by borntoburnyo** [comment]
Hi,

Appreciate your explanation! Thanks so much. 

Tao
