### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by collmomo** [twain47/Nominatim#394]
Using php7. Did the regular installation process. status.php shows OK

`FastCGI: server "/usr/lib/cgi-bin/php7-fcgi" stderr: PHP message: PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /Nominatim/website/search.php on line 20`

Is this a config problem or an actual bug with php7

**Comment by mtmail** [comment]
Hi,
I think nobody tried running Nominatim on PHP7 before. The installation instructions list PHP5 as requirement.

**Comment by collmomo** [comment]
ya whatever, you can fix by removing the deprecated `=& new` since php 5.2. Objects are automatically assigned by reference, that `=& new` is not needed anymore, quick fix that will make php7 users like me happy.

**Comment by mtmail** [comment]
Thanks a lot @collmomo for looking into this. That's great news. It seems that was the only line needed changing. To be honest I expected more work, e.g. on error handling (http://php.net/manual/en/migration70.incompatible.php).

I created a pull request (https://github.com/twain47/Nominatim/pull/395). As usual most time was spent on testing.

The pull request will be merged shortly. For the next minor release we can announce PHP7 works but it will take a major release to endorse users to use PHP7 by default. For one I'd like to see PHP7 running on a large production system for a while just in case (and hopefully see performance gains http://www.zend.com/en/resources/php7_infographic). Please do let us know if you see bugs.

**Comment by mtmail** [comment]
fixed via https://github.com/twain47/Nominatim/commit/50f1766
thanks again
