### ISSUE TITLE
China-specific rules

### ISSUE THREAD

**Issue by d1g** [twain47/Nominatim#397]
From user story (http://forum.openstreetmap.org/viewtopic.php?id=52403): 

> Another point that I'm not satisfied with is the way I can search for addresses. Chinese addresses are sorted large to small (Province City District Road <nr> 弄 <nr> 号 or Province City District Road <nr> 号. But on openstreetmap I have to look for i.e. 81 鹤庆路358弄. If I look for 鹤庆路358弄81号, I can't find anything. Both the Chinese and the internationalized way should be allowed.

I just placed it here.

**Comment by lonvia** [comment]
This has nothing to do with order. 鹤庆路358弄 81 works just as well as 81 鹤庆路358弄. One issue is the number sign, the other that word splitting is not always reliable with Chinese.

#177 reports the same and has more info.
