### ISSUE TITLE
How to ignore default US and GB postcodes?

### ISSUE THREAD

**Issue by pbrugger** [twain47/Nominatim#399]
I set up a nominatim installation with data from one country only. I am also using the autocomplete service photon which is based on nominatim data. when there is a number in the request and the streetnme or city is not known i always get us or gb postcodes as result.
Is there any way to NOT include the default postcodes?
When i just comment out the postcode init files the import fails.

**Comment by mtmail** [comment]
After the initial import you can empty the Postgresql tables `gb_postcode` and `us_postcode` using `delete from '<tablename>';`. The incremental updates don't touch these tables. Then export the data to Photon.

Photon doesn't support filtering results by country or bounding box during import or search time. I know it's a feature request that came up before (https://github.com/komoot/photon/issues/175)
