### ISSUE TITLE
remove housenumber interpolation

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#402]
This is a medium size project for a 2.x release and will require Nominatim administrator to reindex data or run a migration script.

We want to move interpolated house numbers to a separate table. The main advantage is saving discspace. It requires more logic during search time but it is expected that total query execution time remains the same.

Currently in the placex table (200m records) house number are stored as

1. `class=place`, `type=house_number` (113m records)
2. `class=place`, `type=address` (13m records)

The first type of records get created out the second type during index/update time, see `create_interpolation` in `sql/functions.sql`.

An example OSM way is http://www.openstreetmap.org/way/388148765
   `addr:inclusion=potential`
   `addr:interpolation=even`

With a new database table, we can potentially half the placex table (200-113+10). The table is currently 60GB plus 95GB in indexes.

Plan:

0. come up with table schema and indices
1. add table schema to sql/tables.sql
2. setup.sh to create table
3. change PL/SQL function to write to new table during index/update
4. same for TIGER data
5. update tests
6. ?create migration script?
7. change search logic to look at new table
8. same for TIGER data
9. update tests

**Comment by lonvia** [comment]
On-the-fly interpolation of Tiger house numbers has been implemented now in #410.

**Comment by lonvia** [comment]
OSM interpolations now implemented in #437.

Big thanks to @markigail
