### ISSUE TITLE
search json return with dot

### ISSUE THREAD

**Issue by trymodel** [twain47/Nominatim#406]
Hi, i have trouble with search. When i use 

http://myserver/nominatim/search?format=json&q=Praha

i get 

.[{"place_id":"142321454","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"relation","osm_id":"438171","boun .......

start with DOT ( .[{"place_id" ). What i make bad, other works fine. Thank and sorry for stupid question

**Comment by trymodel** [comment]
Im newbee, but I think it is a bug in the function **function javascript_renderData($xVal, $iOptions = 0)**
in this part:

if (preg_match('**/^[$_\p{L}][$_\p{L}\p{Nd}.[\]]*$/u**',$_GET['json_callback']))
			{
				header("Content-Type: application/javascript; charset=UTF-8");
				echo $_GET['json_callback'].'('.$jsonout.')';
			}


Can anyone tell me that it is a problem? thx

**Comment by lonvia** [comment]
The query works fine on nominatim.osm.org, so this is most likely a problem with your server setup. Check your settings/local.php for any stray dots. Make sure it begins with '<?php' at the very first character of the file.

**Comment by trymodel** [comment]
So, the file settings/local.php begins with a dot. My inattention. Thanks ans sorry.
