### ISSUE TITLE
How to support the reverse geocoding of several points in a single request?

### ISSUE THREAD

**Issue by alessandrogurgel** [twain47/Nominatim#408]
I would like to ask you If there is any support for Nominatim to perform the reverse geocoding operation of several points instead of only one. My company maintains a transport system which generate reports from thousands of car and this feature is very important to us. but I am not sure about the limitations related to this feature. 

Does the main reason to not perform multiple reverse geocoding operations in a single request is related to the usage policy (for instance, for billing each request -> each reverse geocoding). Or, depending the number of points (lat, lng), would it be very complex or time-consuming to reverse geocoding them on the Nominatim/OpenStreetMap database?

**Comment by mtmail** [comment]
Nobody has built such a feature yet. There is the option to batch forward geocode and lookup by OSM ids but not for reverse search. Batching 50 requests would still run full 50 reverse lookups so the time spend searching would be about the same.

The nominatim.openstreetmap.org server doesn't charge for requests. For your transport system you might have to look for alternatives (http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) as you'd surely do more than 1 request per second.

**Comment by lonvia** [comment]
To extend on @mtmail's answer: the huge volume of requests that is generated by vehicle tracking software is certainly incompatible with the usage policy for nominatim.openstreetmap.org and very likely to be blocked without notice. You'll get the best throughput if you have your own installation of Nominatim and then cut out the middle man (HTTP) by adapting Nominatim's website/reverse.php script to return the answer locally.

On the more generic topic of geocoding large batches of GPS traces, also have a look at Frederiks's post on the geocoding mailing list: https://lists.openstreetmap.org/pipermail/geocoding/2016-March/001783.html

**Comment by alessandrogurgel** [comment]
Thanks @mtmail  and @lonvia  for the quick and complete answers.

**Comment by alessandrogurgel** [comment]
My idea is to adapt nominatim reverse geocoding script to accept several requests and use a local server as u suggested @lonvia . Thanks
