### ISSUE TITLE
County Road 26 Geocoding Does not work

### ISSUE THREAD

**Issue by willston77** [twain47/Nominatim#412]
The geocoding on County Road 26, Brighton, Ontario, Canada does not seem to be working, it always gives the same point which is the intersection of the 401 and County Road 26 (its a bridge not an intersection).

Thanks a bunch

**Comment by mtmail** [comment]
Thank you for your bug report!

In OpenStreetMap streets are made up of one or more segments (ways) with the same name, in this case 10 (well, two have name "Country 26 road"). This relation happens to combine them http://www.openstreetmap.org/relation/4258524

Nominatim treats each separate and returns one street segment only. http://nominatim.openstreetmap.org/search.php?q=County+Road+26%2C+Brighton%2C+Ontario%2C+Canada&polygon=1

We have a request to combine segments at search time in https://github.com/twain47/Nominatim/issues/332 so I'm marking this report as duplicate.

**Comment by willston77** [comment]
Okay, awesome thank you so much!
