### ISSUE TITLE
Partial search results

### ISSUE THREAD

**Issue by zstadler** [twain47/Nominatim#414]
[Searching for "City of David (Jerusalem Walls) National Park"](https://nominatim.openstreetmap.org/search.php?q=City+of+David+%28Jerusalem+Walls%29+National+Park&polygon=1&viewbox=) provides [one result](https://nominatim.openstreetmap.org/details.php?place_id=2601392443) - [way 395720782](http://www.openstreetmap.org/way/395720782).

However, it does not find [way 395720781](http://www.openstreetmap.org/way/395720781) that has the same set of tags, except the wikipedia tag. The way [has been loaded](http://nominatim.openstreetmap.org/details?osmtype=W&osmid=395720781) to the nominatim.openstreetmap.org server.

Both ways are, by the way, members of the relation of the National Park - [relation 5941143](http://www.openstreetmap.org/relation/5941143)

**Comment by lonvia** [comment]
Add dedupe=0 to your query parameters if you want duplicate results.

The relation is tagged badly. The name should go on the relation and the ways that make up the polygon rings should have no tags at all.
