### ISSUE TITLE
Inconsistent results for colleges in Cambridge, UK

### ISSUE THREAD

**Issue by mvl22** [twain47/Nominatim#417]
When I do a search for King's College, Cambridge:

http://www.openstreetmap.org/search?query=king%27s%20college%2C%20cambridge

I get a poor result: firstly the car park, then some set of buildings presumably owned by King's College.

However, if I do a similar search for another college, then I do get the correct result first:

http://www.openstreetmap.org/search?query=Pembroke%20college%2C%20cambridge

I can't see any reason for this inconsistency.

The data for Cambridge University is extremely high quality thanks to the work of @davidearl, so I think it's unlikely to be a data error, and I can't see any problem myself.

**Comment by davidearl** [comment]
Cambridge Colleges all have the format "name=_whatever college_ (University of Cambridge)". It finds some and not others. (Note, not all colleges have the word "College" in their name, but many do). See http://wiki.openstreetmap.org/wiki/Cambridge/University_of_Cambridge

I've just gone through systematically and get the following:

_Correct_

Christ's College
Clare College
Clare Hall
Corpus Christi College
Darwin College
Emmanuel College (though gets North Court first)
Gonville & Caius College
Hughes Hall
Lucy Cavendish College
Magdalene College
Murray Edwards College
Newnham College
Pembroke College
Selwyn College
Sidney Sussex College
St Catharine's College
St Edmund's College
St John's College
Trinity College
Trinity Hall
Wolfson College

_Not found_

Churchill College
Downing College
Fitzwilliam College
Girton College
Homerton College
Jesus College
King's College
Peterhouse
Queens' College
Robinson College

I can't see anything in common with the wrong ones. It's not the apostrophes or common words. All the colleges are tagged very consistently, so I can't see why Nominatim would catch some and not others. If it were the "(University of Cambridge)" bit in brackets, surely it would fail on all of them. However, if you do put "King's College (University of Cambridge)" as the search term, it does then find it, so it is in the index, so it's the search algorithm that is at fault. I could understand it might not get the first hit if there is a better match without the bit in brackets, but to omit it completely, and to get it right for e.g. Darwin College, seems really strange. I notice Imperial College, London is also not found (it has "name=Imperial College London"), but all the Oxford and Durham Colleges that I've tried are located (but I haven't tried them all).

Obviously it's to do with how the tagging is interpreted, but the way it varies doesn't make sense to me.

**Comment by lonvia** [comment]
The brackets are indeed at fault here. The car park has an exact match to your query, while the college is not. Try 'more results' and the college will show up.

See also #94 and #244 for more discussion on the subject.

**Comment by davidearl** [comment]
The bracketed text is not a fault, it is intentional. Prioritising exact matches on car parking or bus stops over loose match on university isn't helpful.

**Comment by davidearl** [comment]
Another example from a different domain, just so it's not parochial to University of Cambridge: "tilehouse street school, hitchin" gives a hit on a road, some way away, called Tilehouse Street (the school is actually on a different street called Upper Tilehouse Street, though that's only relevant in as much as the street is not a helpful result). The school fails to get an exact hit because it is "pre-school", but it only gives the road in the main set of results. I imagine the same would be true of "Somewhere C of E primary school" where a bus stop nearby is called "Somewhere school". Surely the school is more important than the bus stop even though its complete formal name is not spelled out?

**Comment by davidearl** [comment]
I think Sarah was meaning 'the bit in brackets' not the brackets per se. The reason some are shown is presumably because there isn't another object with an exact match, so it shows the best closest matches, which includes the intended one.
