### ISSUE TITLE
"berģi" and "bergi" constantly finds the wrong place

### ISSUE THREAD

**Issue by richlv** [twain47/Nominatim#418]
try searching for "berģi" - although there's a place in latvia with the exact same spelling, nominatim returns "berg, norway" as the first result.

"bergi", which also has exact matches in latvia, gets same "berg" as the first result.

this is even worse in places that just take the first result (like osrm demo page :) ) - one first searches for "berģi", gets the wrong result, then is forced to enter "berģi, latvia"...

**Comment by lonvia** [comment]
Looks like Nominatim has a wrong idea about the relative importance of both places. Try adding wikipedia links to the Norwegian county to fix it.

**Comment by richlv** [comment]
what wikipedia links/where should be added ?
also, maybe it's worth giving precedence to exact spelling matches, especially if diacritics are entered ? i don't think anybody would mistype "berg" as "berģi" :)

**Comment by lonvia** [comment]
No need to make complicated guesses about spelling and diacritics, the main issue is o get the importance right. I've changed [the problematic relation](http://www.openstreetmap.org/relation/407771) now myself and all is well again.

As a general rule: if the order of search result seems odd, make sure to add correct wikipedia tags to all objects involved. That will almost always fix the problem.

**Comment by richlv** [comment]
ah, thank you - is there a simple explanation on how wikipedia tags affect search results ?
