### ISSUE TITLE
Inconsistent, missing results

### ISSUE THREAD

**Issue by RM87** [twain47/Nominatim#419]
Reporting a problem that came up on OSM Help. Please see: https://help.openstreetmap.org/questions/48893/data-differs-between-planet-continent-databases 

Basically Nominatim does not return any results for "East Maple Lane Scottsdale" and probably a bunch of other places too, by using global data, but works correctly with an extract of data.

East Maple Lane: http://nominatim.openstreetmap.org/details.php?place_id=293858094
Scottsdale http://nominatim.openstreetmap.org/details.php?place_id=1993459

**Comment by lonvia** [comment]
East Maple Lane was still assigned a different city, possibly because of a OSM data error that has been fixed in the meantime. A forced update of all Scottsdale addresses has resolved the issue.
