### ISSUE TITLE
Geocoding fails for Lublin

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#421]
I am looking for address:
http://nominatim.openstreetmap.org/search.php?q=Warszawska+141a+Lublin&polygon=1&viewbox=

It does not return proper address which is located at:
http://www.openstreetmap.org/#map=19/51.27092/22.49256

**Comment by mtmail** [comment]
The house you want to find is on Aleja Warszawska street. Any reason you removed Aleja from the search?

http://nominatim.openstreetmap.org/search.php?q=Aleja+Warszawska+141a+Lublin&polygon=1 ?

![untitled3](https://cloud.githubusercontent.com/assets/3727288/14221427/048f87ac-f867-11e5-8f85-7df77138a48d.png)

**Comment by sanitas2** [comment]
"Aleja" means street (or maybe more like avenue). It is often dropped in searches.

**Comment by lonvia** [comment]
Duplicate of #316
