### ISSUE TITLE
update.php seems stuck

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#426]
Nominatim 2.5 stable, osm2pgsql 0.89.0-dev, planet-wide data.

It's the first time I used the flatnodes file during Nominatim setup. When running
`utils/update.php --import-osmosis-all --no-npi`
the process seems stuck at
    Setting up table: planet_osm_nodes
    Setting up table: planet_osm_ways
    Setting up table: planet_osm_rels

    Reading in file: /home/ubuntu/Nominatim/data/osmosischange.osc
    Using XML parser.

I've tried multiple restarts and increased `osm2pgsql-cache` to 30GB. The server has 12 cores, 64GB, enough discspace, all tables and indices on SSDs and no outside requests (Apache switched off). The flatnode file is 31GB on SSD. The `osmosischange.osc` file is 500MB (about 2 weeks of daily changes merged).

`top` shows `postgres` consuming 99.8% of one CPU core. `iotop` shows maximum 50kb/s being written, mostly to postgres. `SELECT pid,query,state,query_start FROM pg_stat_activity ORDER BY pid;` shows (I cleaned-up up the output a bit)

```
                                                                               query                    | state  |  query_start
   -----------------------------------------------------------------------------------------------------+--------+--------------- 
    SELECT pid,query,state,query_start FROM pg_stat_activity ORDER BY pid;                              | active | now
    COPY place (osm_type, osm_id, class, type, name, admin_level, housenumber, street, addr_place, ...  | active | 2 min earlier
    PREPARE get_classes (CHAR(1), int8) AS SELECT class FROM place WHERE osm_type = $1 and osm_id = $2  | idle   | 2 min earlier
    COPY planet_osm_nodes FROM STDIN;                                                                  +| active | 12h ago
    COPY planet_osm_ways FROM STDIN;                                                                   +| active | 12h ago
    COPY planet_osm_rels FROM STDIN;                                                                   +| active | 12h ago
```

Once it ran 4 days and it reached `Processing: Node(2010k 0.1k/s) Way(77k 0.00k/s) Relation(0 0.00/s)` at least.

On another server catching up 14 days would take only a couple of hours and the `Using XML parser.` only 10 minutes.

Is there an index I could be missing (I checked those on `planet_*` tables) or is it something special with a flatnodes files I'm not aware of?

**Comment by lonvia** [comment]
I've never tried update batches that large, so I'm not sure how well osm2pgsql does there. I really would recommend to do the catch-up in 3-6 hour batches. (Also means that you can already serve queries in parallel without any issues).

It's unlikely that the move to flatnode is the culprit for it being slower. The main difference is that osm2pgsql reserves more memory which might lead to a bit more IO on the postgres side (or rather on the Linux block cache to be precise).  Check the postgres config again to make sure you have increased all important buffer sizes.

During updates, data is already pushed through to placex via place in the osm2pgsql phase, so you should check that indexes for place and placex are correctly created as well. And try running an explicit ANALYSE. Sometimes it helps as well.

**Comment by mtmail** [comment]
Thanks for all the pointers. Every setting and database indexes looked good and I was unable to further debug the issue. 
Instead I dropped the database and reindexed everything from scratch. Now a daily update takes about 30 minutes with 10 minutes spent in the osm2pgsql COPY FROM STDIN step.
It remains a mystery. Closing.

**Comment by arvindkartik** [comment]
Almost similar thing is happening with my updates recently. Full plannet data newly imported on 1st-August-2019, ran for about 3 days. Started daily updates after 5 days. 

The updates keeps getting stalled at "Way" for hours. I kept restarting the updates again and again after waiting for at least 4 to 6 hours on each run, and it just keeps getting stuck at a higher count of Way.

1st Run: `Processing: Node(3620k 22.9k/s) Way(41k 1.41k/s) Relation(0 0.00/s)`
2nd Run: `Processing: Node(3620k 23.5k/s) Way(60k 1.58k/s) Relation(0 0.00/s)`
3rd Run: `Processing: Node(3620k 22.5k/s) Way(81k 1.45k/s) Relation(0 0.00/s)`
4th Run: `Processing: Node(3620k 22.9k/s) Way(85k 3.15k/s) Relation(0 0.00/s)`

On checking the Postgres activity, I noticed a similar pattern on every run when it gets stalled and that Postgres has entered into a lock

List of active queries:
```
nominatim=# SELECT pid,query,state,query_start,waiting FROM pg_stat_activity WHERE state='active' ORDER BY pid;                                                                                                                                                                 
                                                  query                                               | waiting 
-----------------------------------------------------------------------------------------------------+---------
  SELECT pid,query,state,query_start,waiting FROM pg_stat_activity WHERE state='active' ORDER BY pid; | f
  COPY planet_osm_ways FROM STDIN                                                                     | f
  COPY place FROM STDIN                                                                               | f
  PREPARE delete_place (CHAR(1), int8) AS DELETE FROM place WHERE osm_type = $1 and osm_id = $2       | t
(4 rows)
```


Blocked query:

```
                                      blocked_statement                                       | current_statement_in_blocking_process 
----------------------------------------------------------------------------------------------+---------------------------------------
PREPARE delete_place (CHAR(1), int8) AS DELETE FROM place WHERE osm_type = $1 and osm_id = $2 | COPY place FROM STDIN
(1 row)
```

During full plannet import, I did see a line `NOTICE:  table "place" does not exist, skipping`, if this has contributed for this issue in any way.

**Comment by karabakin** [comment]
same problem

` blocked_pid |                                         blocked_query                                         | blocking_pid |    blocking_query
-------------+-----------------------------------------------------------------------------------------------+--------------+-----------------------
       20757 | PREPARE delete_place (CHAR(1), int8) AS DELETE FROM place WHERE osm_type = $1 and osm_id = $2 |        20756 | COPY place FROM STDIN
(1 row)`

` osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -S import-full.style -d nominatim -P 5432 --flat-nodes flatnode.file osmosischange.osc`

**Comment by HardGlory** [comment]
The same problem.

From time to time update stacks on the Processing "Way" downloading. Sometimes helps restarting the command 2-5 times. Sometimes helps decreasing "Replication_Update_Interval" parameter.

```Nominatim version 3.30
./utils/update.php --import-osmosis-all 
osm2pgsql version 0.96.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: loading persistent node cache from /mnt/nominatim/flatnode/flatnode.file
Mid: pgsql, cache=2000
Parsing gazetteer style file '/mnt/nominatim/Nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /mnt/nominatim/Nominatim/build/osmosischange.osc
Using XML parser.
Processing: Node(187k 23.5k/s) Way(87k 7.25k/s) Relation(0 0.00/s)^C
....
```



Settings local.php: 
```
 @define('CONST_Website_BaseURL', '/nominatim/');                                                                     
 @define('CONST_Osm2pgsql_Flatnode_File', '/mnt/nominatim/flatnode/flatnode.file');                                   
 @define('CONST_Pyosmium_Binary', '/mnt/nominatim/.local/bin/pyosmium-get-changes');                                  
 @define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/hour');                               
 @define('CONST_Replication_MaxInterval', '40000');     
 @define('CONST_Replication_Update_Interval', '86400');  // 24h                        
 @define('CONST_Replication_Recheck_Interval', '900');   
```
Some settings postgresql (v10)

```# Nominatim Tuning                                                                                                    
shared_buffers = 4GB                                                                              
maintenance_work_mem = 10GB                                                                                           
work_mem = 100MB                                                                                                      
effective_cache_size = 24GB                                                                                           
synchronous_commit = off                                                                                              
checkpoint_timeout = 10min                                                                                            
checkpoint_completion_target = 0.9

**Comment by lonvia** [comment]
Please follow https://github.com/openstreetmap/osm2pgsql/issues/964 for updates on this or #1550.
