### ISSUE TITLE
Roads not showing up 

### ISSUE THREAD

**Issue by willston77** [twain47/Nominatim#438]
Hi there, I'm trying to geocode Lisgar street in Brighton, Ontario, Canada, however, nominiatim doesn't even see the road, even though I can manually go to it in the OSM window.  This is a problem which seems to apply to many of the roads in this area and I'm wondering if there is a bug affecting this area.

Thanks,
Will

**Comment by lonvia** [comment]
A link to the OSM object would be helpful, as well as the exact search term you were using to find it.

**Comment by mtmail** [comment]
This seems to be the street http://nominatim.openstreetmap.org/details.php?format=html&osmtype=W&osmid=33977267 and it get assigned to the town Belleville.

Brighton is only a node (center point) while Belleville has node, polygon and wikipedia tag.

Will adding a wikipedia tag (https://en.wikipedia.org/wiki/Brighton,_Ontario) to Brighton work?

**Comment by lonvia** [comment]
The road is too far away from the [town node for Brighton](http://www.openstreetmap.org/node/1301003559) to be considered belonging to the town. You'll need to add town boundaries to fix that. There are administrative boundaries in the area but they are completely broken (e.g. http://www.openstreetmap.org/relation/4660559)
