### ISSUE TITLE
tiles.js missing in current stable release

### ISSUE THREAD

**Issue by agastya71** [twain47/Nominatim#440]
the utils/setup.php script refers to "js/tiles.js" when verifying if the website was created properly. 
However, this particular javascript file is missing in the source/website/js folders.
Either the script needs to be updated to reflect this change or the tiles.js file needs to be re-instated into the website/js folder.

**Comment by mtmail** [comment]
Thanks! That's an obvious mistake.

**Comment by lonvia** [comment]
That's a candidate for backporting on 4.5.
