### ISSUE TITLE
Vagrant provision: Could NOT find Lua

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#443]
On a fresh checkout from master and immediate `vagrant up ubuntu` I get a fatal error when running cmake:

    Found Osmium: /home/vagrant/Nominatim/osm2pgsql/contrib/libosmium
    CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
    Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
    Call Stack (most recent call first):
       /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
       osm2pgsql/cmake/FindLua.cmake:167 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
       osm2pgsql/CMakeLists.txt:103 (find_package)
     Configuring incomplete, errors occurred!
     See also "/home/vagrant/Nominatim/build-vagrant/CMakeFiles/CMakeOutput.log".
     See also "/home/vagrant/Nominatim/build-vagrant/CMakeFiles/CMakeError.log".

Lua libraries aren't part of the Vagrant provision script or http://wiki.openstreetmap.org/wiki/Nominatim/Installation so currently a fresh install fails. I don't know if the intention was to add Lua or make it optional in the cmake script.

**Comment by lonvia** [comment]
The cmake script explicitly disables lua for osm2pgsql. Is it possible that your osm2pgsql submodule is not quite up to date?

**Comment by lonvia** [comment]
On second thought, maybe that is related to #370. At least there are similar issues with getting osm2pgsql correctly checked out.

**Comment by mtmail** [comment]
To be sure I ran a fresh installation in a different directory:

    cd /tmp
    git clone --recursive git@github.com:twain47/Nominatim.git
    vagrant up ubuntu

osm2pgsql points to `d0af11f267a202c7c1961c2061d121c726d8db3a` which is March/15th (https://github.com/openstreetmap/osm2pgsql/commit/d0af11f267a202c7c1961c2061d121c726d8db3a)
