### ISSUE TITLE
"Göreme Tarihî Millî Parkı" doesn't match http://www.openstreetmap.org/relation/252585

### ISSUE THREAD

**Issue by d1g** [twain47/Nominatim#449]
```
alt_name:en 	Göreme National Park and the Rock Sites of Cappadocia
name 	Göreme Milli Parkı
name:de 	Göreme Nationalpark
name:en 	Göreme National Park
name:tr 	Göreme Milli Parkı
```

"Göreme Tarihî Millî Parkı" (https://tr.wikipedia.org/wiki/G%C3%B6reme_Tarih%C3%AE_Mill%C3%AE_Park%C4%B1)

http://www.openstreetmap.org/search?query=G%C3%B6reme%20Tarih%C3%AE%20Mill%C3%AE%20Park%C4%B1 

but if you remove "Tarihî", it will find it: 

http://www.openstreetmap.org/search?query=G%C3%B6reme%20Mill%C3%AE%20Park%C4%B1

**Comment by mtmail** [comment]
Thanks. I edited the `name:tr` and added the `wikipedia` tag. Nominatim searches all languages, official, alt, local names so both queries return the national park now. https://www.openstreetmap.org/relation/252585
(Funny enough that will be my summer holiday and I hope I can close a couple of map notes there)

**Comment by d1g** [comment]
...this is not a solution.

"Yosemite Park" doesn't match http://www.openstreetmap.org/relation/1643367

    name 	Yosemite National Park
    name:de 	Yosemite-Nationalpark
    operator 	United States Nat
    wikipedia 	en:Yosemite National Park`

Yosemite National Park returns exact result http://www.openstreetmap.org/search?query=Yosemite National Park

PS. do NOT change tags of relation/1643367, because all of them are fine https://en.wikipedia.org/wiki/en:Yosemite%20National%20Park
