### ISSUE TITLE
Nominatim on a greenplum database

### ISSUE THREAD

**Issue by Florian-Traversaz** [twain47/Nominatim#451]
Hi,
i want to use a greenplum remote database to store my osm-data but i don't know if it is possible. After many tries, it never work.
Did anyone already try this?
Furthermore, did osm2pgsql work with that?
I read in another issue that use other database that a local postgres is complicated.
Can anyone confirm this?

thanks by advance

**Comment by lonvia** [comment]
I don't know what greenplum is but you will likely run into the same issues as when running on any remote postgres installation, see #318.

**Comment by mtmail** [comment]
It's basically a forked Postgres which different storage engine and query planner. Used for massive distribution of queries across machines as used by ETL or data warehousing. Supports SQL and PL/SQL. https://en.wikipedia.org/wiki/Pivotal_Greenplum_Database But yes, it's the remote part that will cause trouble
