### ISSUE TITLE
Build fails at target pgxs on centos

### ISSUE THREAD

**Issue by Florian-Traversaz** [twain47/Nominatim#454]
I try to build a docker container with centos 7 and i have somethink like in issue #453 
I have the last version of project with a fix for #453 but it doesn't change anything.

>[ 87%] Running external makefile /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk
/app/git/module/Makefile:9: warning: overriding recipe for target `install'
/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk:126: warning: ignoring old recipe for target `install'
make[3]: *** No rule to make target `nominatim.so', needed by `all'.  Stop.
make[2]: *** [/app/git/module/dummy] Error 2
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Error 2
make: *** [all] Error 2

Here is the full verbose stacktrace:
[nominatim-docker-centos.txt](https://github.com/twain47/Nominatim/files/284401/nominatim-docker-centos.txt)

**Comment by cogidoo** [comment]
Same here ... even without docker.

**Comment by lonvia** [comment]
Here is a helpful hint from @parkercoleman (see #453):

> edit: Think I just got past it. Looks like the issue was the postgres 9.2 pgxs.mk file, I don't know much about makefiles but 9.3's handles VPATH differently. Copying it over and using it allowed the project to compile.
