### ISSUE TITLE
Geocoding fails for Rudy

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#455]
I am geocoding:
Raciborska 8, Rudy, Poland

http://nominatim.openstreetmap.org/search?format=json&street=Raciborska%208&city=Rudy&country=pl

In the OSM data exists city "Rudy" with street Raciborska (but without number 8). In the result I am getting position in different city Ruda Śląska (which has Raciborska 8 address). I would expect in such case Nominatim to give no results instead of wrong result.

**Comment by lonvia** [comment]
Fix planned in #429.
