### ISSUE TITLE
Geocoding accented character

### ISSUE THREAD

**Issue by samcfc** [twain47/Nominatim#456]
Hi, 
I want to geocode some set of adresses and one of it contains accented character.

The bug is that the returned providedLocation is wrong in that case.

I send in POST request body 
{
	"locations": [{
		"street": "2 allée d'Espagne",
		"city": "ARCACHON Cedex",
		"postalCode": "33120",
		"country": "FRANCE"
	}]
}

and get a result with provided location set to 

"2 allA©e d'Espagne, ARCACHON Cedex, 33120, FRANCE"

The webapp triggering the request contains meta utf8 tag, and the $http call to Mapquest "http://www.mapquestapi.com/geocoding/v1/batch" with AngularJS contains the following headers 

headers: {
    'Content-Type': 'text/plain',
    "Accept": "application/json;charset=utf-8",
    "Accept-Charset":"charset=utf-8"
}

so I am kind of lost., how can I get the truly provided location without UTF8 <-> accented character problem.

Thank you

**Comment by lonvia** [comment]
You are using the MapQuest geocoding API which has nothing to do with Nominatim. Please try the forums at the MapQuest Developer Network.
