### ISSUE TITLE
"Error contacting nominatim.openstreetmap.org: 500" for certain type of queries

### ISSUE THREAD

**Issue by piotrfrankowski** [twain47/Nominatim#462]
Hello,

I have noticed, that some queries are hanging up Nominatim(for a while) and openstreetmap.org as well. I have tested following queries:
```
A: 0.00,0.02
A: 0.0,0.02
A: 0.0,0.01
T: 0.0,0.01
ÜT: 0.0,0.02
```
I have noticed also, that regex which brokes query engine is:
```
[A-Za-z]+: 0.0+,.* 
```

I do not know, whether it is problem with php code, or database. Take a look:
http://www.openstreetmap.org/search?query=A%3A%200.00%2C0.02#map=4/50.76/18.46
http://www.openstreetmap.org/search?query=%C3%9CT%3A%200.0%2C0.02#map=3/38.34/40.96

Is it bug or I just wrote bad query?

**Comment by lonvia** [comment]
The query doesn't make much sense to Nominatim (I suspect you actually want to do a /reverse query) but it shouldn't make it hang so badly either. So, there is a bug somewhere in there, too, that definitely needs fixing.

**Comment by lonvia** [comment]
Fixed and live on osm.org. Now the query is interpreted as "give me the thing named 'A' which is closest to coordinate 0.0, 0.02", which still doesn't make much sense but at least the server does not hang anymore. Thanks for the report.

**Comment by piotrfrankowski** [comment]
Thanks for solving:)
