### ISSUE TITLE
The remote server returned an error: (429) Too Many Requests

### ISSUE THREAD

**Issue by dkoloszc** [twain47/Nominatim#466]
Hi 

I am using Nominatim for the reverse Geo-coding and recently I have noticed, that address can't be displayed (unknown address). From the server I am getting such error: dbConverter.NominatimGeocoder [(null)] - Can't get addressSystem.Net.WebException: The remote server returned an error: (429) Too Many Requests.

Could you tell me where the problem might be? 
Is it possible that you blocked me somehow?

Thank You.

**Comment by lonvia** [comment]
Yes, the error message means that you have violated our usage policy and have been blocked. For more information see the [usage policy for nominatim.osm.org](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy).

**Comment by dkoloszc** [comment]
Is it possible, that "you" can tell me which point of usage policy has been violated?
if yes, what kind of data would you need?

**Comment by lonvia** [comment]
The error message already says it all really. You have either sent too many requests (more than 1 req/s) or using a software/library that is known to spam the server with too  many requests. Note that software that does not identify itself at all also falls under the latter category.

Stop your application for a while and fix your software to send less requests. If you are still not allowed back after a couple of hours, the second case applies to you. Either bug the developers of whatever library you are using to fix their software or find another geocoding provider. There are some alternatives listed on above mentioned policy page.

**Comment by bopoh13** [comment]
I used a [similar function](https://github.com/component/debounce) to avoid returning **code 429**.
Suppose a query with geocoding is in the `function updateInfo(...args) { }`. Then you need to create the variable `var updateInfo = debounce(updateInfo, 1000);` and then simply call the function in the method ex.:
``` javascript
map.on("moveend", function() {
   updateInfo(...args);
});
```

**Comment by bopoh13** [comment]
I used a [similar function](https://github.com/component/debounce) to avoid returning **code 429**.
Suppose a query with geocoding is in the `function updateInfo(...args) { }`. Then you need to create the variable `var updateInfo = debounce(updateInfo, 1000);` and then simply call the function in the method ex.:
``` javascript
map.on("moveend", function() {
  updateInfo(...args);
});
```
