### ISSUE TITLE
Error 500 on access WebServer

### ISSUE THREAD

**Issue by raphmte** [twain47/Nominatim#481]
Hei guys, all right?

I have a problem.

The installation of Nominatim works fine, data import works fine, apache2 works... BUT

When I access http://201.22.74.129:8080/nominatim/ the apache send a Internet Server Error 500.

This issue are in my Online VPS and im My Local VPS (My Local VPS don't have data) and the issue is the same.

Anyone have idea to solve this?

**Comment by mtmail** [comment]
Do you have errors in `/var/log/apache2/error.log` ?

**Comment by raphmte** [comment]
Yes.. Have:
[Thu Jul 07 20:10:17.001989 2016] [:error] [pid 24581] [client 177.156.170.50:59847] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /srv/nominatim/Nominatim/website/search.php on line 19

Line 19:
$oGeocode =& new Geocode($oDB);

**Comment by raphmte** [comment]
Update:
Searching about this error.. it refer to:
`require_once(CONST_BasePath.'/lib/Geocode.php');`

The code is not finding the file. Fine.

If I configure my `/etc/apache2/sites-available/400-nominatim.conf` with:

```
<Directory "/srv/nominatim/Nominatim/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  Require all granted
</Directory>

Alias /nominatim /srv/nominatim//Nominatim/website
```

And `settings/local.php` with:
```
@define('CONST_Website_BaseURL', 'http://192.95.21.83/nominatim/');
 @define('CONST_Osm2pgsql_Flatnode_File', '/srv/nominatim/Nominatim/flatnode.file');
 @define('CONST_Postgresql_Version', '9.5');
 @define('CONST_Postgis_Version', '2.2');
```
I'm not allowed to access the files:
```
Forbidden

You don't have permission to access /nominatim/ on this server.
Apache/2.4.18 (Ubuntu) Server at 192.95.21.83 Port 80
```
Tried:
```
sudo chown www-data /var/www/html/nominatim
sudo chown www-data /srv/nominatim/Nominatim
```

The problem persists.

How to solve this?

**Comment by tanzeelrana** [comment]
I am getting the following error : 
`[Mon May 01 05:14:10.603775 2017] [:error] [pid 5230] [client ::1:36750] PHP Fatal error:  require_once(): Failed opening required '/home/tanzeel/Documents/osrm/Nominatim/lib/init-website.php' (include_path='.:/usr/share/php') in /home/tanzeel/nominatim/build/website/search.php on line 5`
