### ISSUE TITLE
official Docker image

### ISSUE THREAD

**Issue by philtay** [twain47/Nominatim#482]
Do you provide an official Docker image of Nominatim?
Can't find any Dockerfile in the repo.
Thanks

**Comment by mtmail** [comment]
We maintain Vagrant installation files as guide, but no Docker images. There are a couple on https://hub.docker.com/
One thing to watch out for when splitting Nominatim into multiple containers is that the make/cmake process builds a `nominatim.so` file which the Postgresql server needs to access. So non-local databases are tricky.

**Comment by philtay** [comment]
Thanks for the quick reply. I was hoping for an official image. Unfortunately there's a lot of garbage on Docker Hub... Running more than one process in a single container is [easy](https://docs.docker.com/engine/admin/using_supervisord/). Of course this wouldn't be something meant for production, but it would come very handy to simply type `docker run twain47/nominatim` to get a working Nominatim instance.

**Comment by lonvia** [comment]
Unfortunately we don't have the resources to also maintain a docker image. If somebody wants to step up and create an image that follows the vagrant scripts for the stable and/or development version and offer continuous first tier support for installation issues, let me know and I'm happy to promote your docker image.
