### ISSUE TITLE
Incorrect GeoLocation for San Antonio Texas

### ISSUE THREAD

**Issue by dcb1101** [twain47/Nominatim#484]
http://nominatim.openstreetmap.org/search?q=san%20antonio%20texas

GeoLocates to San Antonio Texas, Cosamaloapan de Carpio, Veracruz, Mexico (Village)

**Comment by SuberFu** [comment]
Well, it does look correct in the sense that you're searching "San Antonio Texas", and it found the place with an exact name match.
If you want the actual city in San Antonio, you need "San Antonio, Texas" (note the comma separating the city and state name).

**Comment by lonvia** [comment]
That's right. San Antonio in Texas will be displayed as soon as you ask for 'more results'. Or just try 'San Antonio TX'.

Side note: I can't find any reference to 'San Antonio Texas' (the Mexican villages) anywhere. So there might be a data error worth fixing here.

**Comment by SuberFu** [comment]
Apparently it's a valid place, at least according to Google.
https://www.google.com/maps/place/San+Antonio+Texas/@18.1749421,-96.1321077,17z/data=!3m1!4b1!4m5!3m4!1s0x85c3e8e86deb4d5b:0x7384a3a64320be9!8m2!3d18.174937!4d-96.129919
Looks like an extremely tiny village.
