### ISSUE TITLE
Reverse geocoding doesn't return polygon in the response

### ISSUE THREAD

**Issue by cylon-v** [twain47/Nominatim#485]
Version 2.5. Custom installation.

Steps to reproduce:

1. Search a location: 
/search?format=json&q=London&addressdetails=1&polygon_geojson=1&extratags=1&namedetails=1. The response contains polygon data.
2. Pick osm_id from the response:  65606
3. Try to find the place using reverse geocoding:
reverse?format=json&osm_type=R&osm_id=65606&addressdetails=1&polygon_geojson=1&extratags=1&namedetails=1. The response doesn't contain any polygon data. 
The case was also reproduced for other polygon_ flags. 

BTW, it's interesting, but it works fine for http://nominatim.openstreetmap.org. What version do they use?

**Comment by mtmail** [comment]
Version 2.5 was released in February 2016. The polygon support for reverse search was added in March with this pull request https://github.com/twain47/Nominatim/pull/389 and was put on http://nominatim.openstreetmap.org shortly after.

**Comment by cylon-v** [comment]
@mtmail, thank you for information!

**Comment by teohhanhui** [comment]
Will there be another 2.x release? Or will this only be in 3.x?

**Comment by lonvia** [comment]
It will only go into the next major release. I haven't quite made up my mind if this is going to be called 2.5 or 3.0. In any case, it is still quite a bit away.
