### ISSUE TITLE
Incorrect Place Name - Dubai Media City Extension

### ISSUE THREAD

**Issue by tgbhd** [twain47/Nominatim#488]
The area marked as Dubai Media City Extension is now known as Barsha Heights. In fact before the name changed to Barsha Heights, it was known as Tecom. How can we change the name to Barsha Heights in the map? See screenshot below. You can also visit www.barshaheights.ae for more information. 

![image](https://cloud.githubusercontent.com/assets/20642075/17101571/6badb6ce-5286-11e6-8040-f3d90756a610.png)

**Comment by mtmail** [comment]
You click the `node 3087418334` link which leads to http://www.openstreetmap.org/node/3087418334
On that page you find an 'edit' link on the top left which opens an interactive editor, similar to wikipedia.
