### ISSUE TITLE
Probelm with make

### ISSUE THREAD

**Issue by fafabone** [twain47/Nominatim#489]
I'm quite noob on Linux compiling.
I'm following install-on-ubuntu-16.md. The result is here:
sudo cmake nominatim
[sudo] password di fabio: 
-- Building osm2pgsql 0.91.0-dev
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.5.3") 
Libraries used to build: /usr/lib/x86_64-linux-gnu/libboost_system.so/usr/lib/x86_64-linux-gnu/libboost_filesystem.so/usr/lib/x86_64-linux-gnu/libpq.so/usr/lib/x86_64-linux-gnu/libz.so-lpthread/usr/lib/x86_64-linux-gnu/libexpat.so/usr/lib/x86_64-linux-gnu/libbz2.so/usr/lib/x86_64-linux-gnu/libgeos.so/usr/lib/x86_64-linux-gnu/libproj.so
Active compiler flags:
-- Added test: test-expire-tiles...
-- Added test: test-hstore-match-only...
-- Added test: test-middle-flat...
-- Added test: test-middle-pgsql...
-- Added test: test-middle-ram...
-- Added test: test-options-database...
-- Added test: test-options-parse...
-- Added test: test-output-multi-line-storage...
-- Added test: test-output-multi-line...
-- Added test: test-output-multi-point-multi-table...
-- Added test: test-output-multi-point...
-- Added test: test-output-multi-poly-trivial...
-- Added test: test-output-multi-polygon...
-- Added test: test-output-multi-tags...
-- Added test: test-output-pgsql-area...
-- Added test: test-output-pgsql-schema...
-- Added test: test-output-pgsql-tablespace...
-- Added test: test-output-pgsql-z_order...
-- Added test: test-output-pgsql...
-- Added test: test-parse-diff...
-- Added test: test-parse-xml2...
-- Added test: test-pgsql-escape...
-- Added test: test-wildcard-match...
-- Added test: regression-test-pbf (needs Python with psycopg2 module)
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.5.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fabio
fabio@osmServer:~$ sudo make
[ 30%] Built target osm2pgsql_lib
[ 32%] Built target osm2pgsql
[ 35%] Built target middle-tests
[ 38%] Built target common-pg
[ 40%] Built target test-pgsql-escape
[ 42%] Built target test-parse-xml2
[ 44%] Built target test-output-pgsql
[ 46%] Built target test-middle-pgsql
[ 48%] Built target test-middle-flat
[ 51%] Built target test-options-database
[ 53%] Built target test-parse-diff
[ 55%] Built target test-output-multi-line-storage
[ 57%] Built target test-expire-tiles
[ 59%] Built target test-output-pgsql-schema
[ 61%] Built target test-output-multi-line
[ 63%] Built target test-middle-ram
[ 65%] Built target test-hstore-match-only
[ 68%] Built target test-output-multi-point-multi-table
[ 70%] Built target test-output-pgsql-area
[ 72%] Built target test-wildcard-match
[ 74%] Built target test-output-multi-point
[ 76%] Built target test-output-multi-poly-trivial
[ 78%] Built target test-output-multi-polygon
[ 80%] Built target test-output-multi-tags
[ 82%] Built target test-options-parse
[ 85%] Built target test-output-pgsql-tablespace
[ 87%] Built target test-output-pgsql-z_order
[ 88%] Running external makefile /usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk
/home/fabio/nominatim/module/Makefile:11: attenzione: sovrascrittura del set di istruzioni per l'obiettivo "install"
/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk:123: attenzione: ignorato il set di istruzioni obsoleto per l'obiettivo "install"
[ 88%] Built target nominatim_lib
[ 89%] Linking CXX executable nominatim
/usr/bin/ld: impossibile aprire il file di output nominatim: È una directory
collect2: error: ld returned 1 exit status
nominatim/CMakeFiles/nominatim.dir/build.make:279: set di istruzioni per l'obiettivo "nominatim/nominatim" non riuscito
make[2]: *** [nominatim/nominatim] Errore 1
CMakeFiles/Makefile2:2253: set di istruzioni per l'obiettivo "nominatim/CMakeFiles/nominatim.dir/all" non riuscito
make[1]: *** [nominatim/CMakeFiles/nominatim.dir/all] Errore 2
Makefile:138: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

What is the problem? Help me, please.

**Comment by mtmail** [comment]
You're running `sudo cmake nominatim` but the installation instructions https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md list `cmake $USERHOME/Nominatim`. `sudo` is not needed (and can set permissions too strict that the webserver can't access files. The parameter after `cmake` needs to be an existing directory and in case of `git clone git clone --recursive git://github.com/twain47/Nominatim.git` it's uppercase `Nominatim`.

**Comment by fafabone** [comment]
Is the same without sudo. The folder nominatim exists in my system. I've copied there the files/folders of the archive downloaded zipped (and after unzipped). This is the result (I've set the english language in my system to let the error understandable here):
cmake nominatim
-- Building osm2pgsql 0.91.0-dev
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.5.3") 
Libraries used to build: /usr/lib/x86_64-linux-gnu/libboost_system.so/usr/lib/x86_64-linux-gnu/libboost_filesystem.so/usr/lib/x86_64-linux-gnu/libpq.so/usr/lib/x86_64-linux-gnu/libz.so-lpthread/usr/lib/x86_64-linux-gnu/libexpat.so/usr/lib/x86_64-linux-gnu/libbz2.so/usr/lib/x86_64-linux-gnu/libgeos.so/usr/lib/x86_64-linux-gnu/libproj.so
Active compiler flags:
-- Added test: test-expire-tiles...
-- Added test: test-hstore-match-only...
-- Added test: test-middle-flat...
-- Added test: test-middle-pgsql...
-- Added test: test-middle-ram...
-- Added test: test-options-database...
-- Added test: test-options-parse...
-- Added test: test-output-multi-line-storage...
-- Added test: test-output-multi-line...
-- Added test: test-output-multi-point-multi-table...
-- Added test: test-output-multi-point...
-- Added test: test-output-multi-poly-trivial...
-- Added test: test-output-multi-polygon...
-- Added test: test-output-multi-tags...
-- Added test: test-output-pgsql-area...
-- Added test: test-output-pgsql-schema...
-- Added test: test-output-pgsql-tablespace...
-- Added test: test-output-pgsql-z_order...
-- Added test: test-output-pgsql...
-- Added test: test-parse-diff...
-- Added test: test-parse-xml2...
-- Added test: test-pgsql-escape...
-- Added test: test-wildcard-match...
-- Added test: regression-test-pbf (needs Python with psycopg2 module)
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.5.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fabio
fabio@osmServer:~$ make
[ 89%] Built target osm2pgsql_lib
[ 89%] Built target osm2pgsql
[ 89%] Built target middle-tests
[ 89%] Built target common-pg
[ 89%] Built target test-pgsql-escape
[ 89%] Built target test-parse-xml2
[ 89%] Built target test-output-pgsql
[ 89%] Built target test-middle-pgsql
[ 89%] Built target test-middle-flat
[ 89%] Built target test-options-database
[ 89%] Built target test-parse-diff
[ 89%] Built target test-output-multi-line-storage
[ 89%] Built target test-expire-tiles
[ 89%] Built target test-output-pgsql-schema
[ 89%] Built target test-output-multi-line
[ 89%] Built target test-middle-ram
[ 89%] Built target test-hstore-match-only
[ 89%] Built target test-output-multi-point-multi-table
[ 89%] Built target test-output-pgsql-area
[ 89%] Built target test-wildcard-match
[ 89%] Built target test-output-multi-point
[ 89%] Built target test-output-multi-poly-trivial
[ 89%] Built target test-output-multi-polygon
[ 89%] Built target test-output-multi-tags
[ 89%] Built target test-options-parse
[ 89%] Built target test-output-pgsql-tablespace
[ 89%] Built target test-output-pgsql-z_order
[ 89%] Running external makefile /usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk
/home/fabio/nominatim/module/Makefile:11: warning: overriding recipe for target 'install'
/usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk:123: warning: ignoring old recipe for target 'install'
[ 89%] Built target nominatim_lib
[ 89%] Linking CXX executable nominatim
/usr/bin/ld: cannot open output file nominatim: Is a directory
collect2: error: ld returned 1 exit status
nominatim/CMakeFiles/nominatim.dir/build.make:279: recipe for target 'nominatim/nominatim' failed
make[2]: *** [nominatim/nominatim] Error 1
CMakeFiles/Makefile2:2253: recipe for target 'nominatim/CMakeFiles/nominatim.dir/all' failed
make[1]: *** [nominatim/CMakeFiles/nominatim.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lonvia** [comment]
You have not created a build directory. It's likely that you have now destroyed your nominatim source directory in the process, so better to delete everything and start again.

**Comment by fafabone** [comment]
thanks. The make process finalize without errors
