### ISSUE TITLE
House number interpolation does not work for one particular way

### ISSUE THREAD

**Issue by ftrebien** [twain47/Nominatim#49]
House numbers in this particular way are not retrieved by Nominatim: http://www.openstreetmap.org/browse/way/215665429

I thought it was maybe related to the transition from 4 to 5-digit numbers. To test this, I tried adding numbers 9998 and 10000 manually and splitting the way. It worked, all interpolated house numbers could be located. Then I merged the two house number nodes without combining the ways, leaving only number 9998. Still worked. Then I deleted the node for number 9998 (bringing it back to its original state) and it stopped working.

**Comment by lonvia** [comment]
The computation of house number interpolations has changed. Example seems to be working now.
