### ISSUE TITLE
install-on-ubuntu-16.sh

### ISSUE THREAD

**Issue by fafabone** [twain47/Nominatim#494]
I've lunched the script but it throws this error:
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
What is the problem with postgresql?

Here the line of listen address in postgresql.conf
listen_addresses = '*'
Here the pg_hba.conf:
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
host    all         all         10.0.0.0       255.255.255.0    md5

**Comment by mtmail** [comment]
Usually you don't need to change anything.

On older ubuntu14 I had luck using

```
# make sure OS-authenticated users (e.g. ubuntu) can access
sudo sed -i "s/ident/trust/" /etc/postgresql/9.5/main/pg_hba.conf
sudo sed -i "s/md5/trust/" /etc/postgresql/9.5/main/pg_hba.conf
sudo sed -i "s/peer/trust/" /etc/postgresql/9.5/main/pg_hba.conf
sudo /etc/init.d/postgresql restart
```

**Comment by fafabone** [comment]
For ubuntu 16 this is not the solution.
Thanks for reply

**Comment by fafabone** [comment]
This solution help me for the error above:
http://askubuntu.com/questions/50621/cannot-connect-to-postgresql-on-port-5432
but the setup.php script prompt me another error:
WARNING: resetting threads to 1
Create DB
createdb: could not connect to database template1: FATAL:  role "fabio" does not exist
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim

I create the user fabio in postgres, but:
WARNING: resetting threads to 1
Create DB
createdb: database creation failed: ERROR:  permission denied to create database
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim

**Comment by fafabone** [comment]
Please what is the solution?

**Comment by mtmail** [comment]
Did you create the user as superuser (`-s` or `--superuser`)?
`sudo -u postgres createuser -s fabio`
There is `dropuser` to remove a user in case you need to recreate it.

**Comment by korstiaanS** [comment]
Hi,
When trying the installation on 16.04 I also ran into that fault.
In my case it was because I added the checkpoint_segments parameter to the postgresql.conf file.
Don't add this to the file and everything worked fine afterwards.

**Comment by fafabone** [comment]
The script ended without errors
Now I need to change the nominatim folder permissions because, following your procedure, the nominatim webserver owns to my user, but Apache uses www-data user.
So I don't know if your script installed all data in the right way now.

**Comment by korstiaanS** [comment]
I didn't followed the script completely. I used `wget http://www.nominatim.org/release/Nominatim-2.5.0.tar.bz2 
tar xvf Nominatim-2.5.0.tar.bz2 ` because otherwise I couldn't MAKE the project.

**Comment by mtmail** [comment]
@korstiaanS The `install-on-ubuntu16.sh` is for the latest release. If you downloaded version 2.5, the stable release, then follow instructions on http://wiki.openstreetmap.org/wiki/Nominatim/Installation

**Comment by korstiaanS** [comment]
Yes I know, but since I wanted it on 16.04 (PHP7) I used parts of this Installation script. The standard Installation script mentions that you must install PHP5.
(+ I had to add libboost-thread-dev, ...)
Anyway, I managed to get it running with the stable release on 16.04.1.
(PS: I only use reverse geocoding)

**Comment by mtmail** [comment]
@korstiaanS Ok, just wanted to make you aware that there are two instruction pages currently until version 2.6 is out (version 2.5 uses make, then we switched to cmake and a slightly different directory structure). Great to hear it worked!

**Comment by korstiaanS** [comment]
Maybe good to know (for others):
For me to get it (2.5.0 stable release) up and running (on 16.04.1) I had to:
- add package libboost-thread-dev (starting from the install-on-ubuntu-16.md, NOT from standard installation because that won't work on 16.04)
- do no not add checkpoint_segments = 100 in postgresql.conf of Postgesql 9.5 won't work properly.
- do not forget to change postgresql to 9.5 and Postgis to 2.2 in settings.php 
For the rest I used more or less the same.
