### ISSUE TITLE
Id of deleted (duplicate) relation not updated

### ISSUE THREAD

**Issue by tyrasd** [twain47/Nominatim#500]
The search result for `Romania` (http://nominatim.openstreetmap.org/details.php?place_id=2609779813) points to a long deleted relation (http://www.openstreetmap.org/relation/6099715, see its [history](https://osmlab.github.io/osm-deep-history/#/relation/6099715)), but the current relation for the country should be http://www.openstreetmap.org/relation/90689. (reported by StephanGeorg on [twitter](https://twitter.com/StephanGeorg/status/760943708825157632))

It looks like as if the country boundary relation was duplicated by mistake, the dupe deleted after a short time and nominatim somehow didn't notice this deletion for some reason.

**Comment by lonvia** [comment]
Nominatim has a protection against tagging accidents. Deleted areas of such a large size need to be manually removed from the database. I've done that now and also removed all other areas from the [pending deletable list](http://nominatim.openstreetmap.org/deletable.php).
