### ISSUE TITLE
Error during import of the data

### ISSUE THREAD

**Issue by JucianoC** [twain47/Nominatim#501]
`nominatim@ADDRESS:~$ cd /var/www/nominatim/Nominatim/build/
nominatim@ADDRESS:~/Nominatim/build$ ./utils/setup.php --osm-file /var/www/mapas/brazil-latest.osm.pbf --all --osm2pgsql-cache 2048 2>&1 | tee setup.log 
tee: setup.log: Permission denied
Create DB
Setup DB
Postgres version found: 9.5
CREATE EXTENSION
CREATE EXTENSION
Postgis version found: 2.2
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 250
CREATE INDEX
REVOKE
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 229
CREATE INDEX
CREATE INDEX
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 25477
CREATE INDEX
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
SET
SET
SET
SET
SET
SET
SET
COPY 1696035
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 32388
CREATE TABLE
CREATE TYPE
Import
osm2pgsql version 0.91.0-dev (64 bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2048MB, maxblocks=32768*65536, allocation method=11
Mid: loading persistent node cache from /path/to/flatnode.file
Failed to create node cache file: No such file or directory
Error occurred, cleaning up
ERROR: Error executing external command: /var/www/nominatim/Nominatim/build/osm2pgsql/osm2pgsql --flat-nodes /path/to/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 -C 2048 -P 5432 -d nominatim /var/www/mapas/brazil-latest.osm.pbf
Error executing external command: /var/www/nominatim/Nominatim/build/osm2pgsql/osm2pgsql --flat-nodes /path/to/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 -C 2048 -P 5432 -d nominatim /var/www/mapas/brazil-latest.osm.pbf`

What does this error? How to solve?

**Comment by lonvia** [comment]
This part of the error message is the interesting part:

    Mid: loading persistent node cache from /path/to/flatnode.file
    Failed to create node cache file: No such file or directory

The line in the instructions [here](https://github.com/twain47/Nominatim/blob/master/docs/Import_and_update.md#configuration-setup-in-settingslocalphp) was just meant as an example. Naturally you should replace it with a file path that actually exists on your system (and where you have around 35GB of free space).

**Comment by JucianoC** [comment]
Thanks lonvia!
But now a new error hapened...

`
. . .
Importing wikipedia articles......done
Importing wikipedia redirects......done
Drop old Data
PHP Notice:  pg_query(): Cannot set connection to blocking mode in /var/www/nominatim/Nominatim/build/utils/setup.php on line 311
ERROR: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
`

**Comment by mtmail** [comment]
> server closed the connection unexpectedly

The server in this case is Postgresql and it probably crashed. Do you see relevant entries in its logfile? `pg_config` should show where the logfiles are located on your machine, on Linux usually in `/var/log/postgresql/`. 

That's a rare and exceptional event. I could be lost network connection, not enough memory or disc space.

**Comment by JucianoC** [comment]
Thanks @mtmail, I upgrade the RAM (4GB to 8GB) and it works.
Now, how i merge other pbf file to the same database?

I found the example using a bz2 file:

./utils/update.php --import-file file.xml.bz2
./utils/update.php --index

It's the only way?

**Comment by mtmail** [comment]
Import another file (country, region) into an existing database doesn't work, you need to merge the files before the import.

The first answer on https://help.openstreetmap.org/questions/48843/merging-two-or-more-geographical-areas-to-import-two-or-more-osm-files-in-nominatim describes how to merge with osmconvert. You can merge 2 or more files with osmconvert.

**Comment by bidabil** [comment]
hello !
I have the same error message as jucianoC under version 3 of nominatim for ubuntu server 16.04 as virtual machine.
the link does not work so I was wondering, is the solution to create an empty file with the same arboressance?

**Comment by lonvia** [comment]
Link fixed.
