### ISSUE TITLE
Unable to geocode

### ISSUE THREAD

**Issue by teohhanhui** [twain47/Nominatim#503]
http://nominatim.openstreetmap.org/reverse?format=json&accept-language=en,*;q=0.5&osm_type=R&osm_id=2559126&polygon_geojson=1

gives
```json
{
  "error": "Unable to geocode"
}
```

But of course it's actually valid: http://www.openstreetmap.org/relation/2559126

**Comment by lonvia** [comment]
This is a data error. The relation does not have a `type` tag.

**Comment by teohhanhui** [comment]
Thank you!
