### ISSUE TITLE
"Regierungsbezirk" everywhere in Germany

### ISSUE THREAD

**Issue by saper** [twain47/Nominatim#509]
Something that struck me long time ago when I started using OSM:

When searching for some entity Nominatim is very precise in the search results - it returns the name of the entity with (almost?) all administrative levels listed. For example:

A search for "https://www.openstreetmap.org/search?query=marienstrasse%2C offenbach" produces:

```Marienstraße, Gravenbruch, Offenbach am Main, Regierungsbezirk Darmstadt, Hesse, 63069, Germany"```

almost every city in Germany has this "Regierungbezirk" included, which is I think pretty counterintuitive and not something anyone uses in reality (apart from delivery of traffic tickets, maybe:).

Would that be possible to mark some `admin_level` as something that is not displayed in the search results? Or to mark specific administrative_boundaries as not used for the purpose of Nominatim?

In this example also another problem is visible: `Gravenbruch` is incorrect (it's a result of my error in mapping), but demonstrates the issue: City like Offenbach is not completely split into suburbs ("Stadtteil"), only some specific locations are designated as suburbs, the rest is kind of unincorporated area belonging only to the city. Nominatim insists on searching the nearest suburb definition node,
in this case the nearest found is the "Gravenbruch" which is far, far away. Of course, we should map the suburbs with exact boundaries to fix the problem, but this is not possible yet.
I don't know how to workaround this problem, unless we have a flag that excludes certain administrative_boundary from the full name expansion (as proposed above).

**Comment by lonvia** [comment]
Country-specific use of admin_levels and localized address formats is definitely something that is planned for the future but I cannot say when it will be implemented. Issue #213 tracks the progress.

For the suburb problem there is already issue #231 which describes similar problems for towns in England. To be honest, I'm not quite sure yet how it can be solved.

Closing in favour of the other tickets.

**Comment by saper** [comment]
Thank you for update, I suspected this has been discussed already.

regarding #213: I think proper design and deployment of country address templates will take some time. I do not believe this can be done on a country-level even, due to some regional and language variations.

I have a possibly simpler suggestion for this problem: what about adding a tag something like `locality_identity_part`, with default value `yes`, which allows the mappers to exclude that particular administrative boundary (not a whole level!) from the locality name presented in the search results. If the community agrees, one could put that tag on all or some government districts in Germany.

for example Regierungsbezirke in Bayern do have some cultural and regional meaning (Unterfranken, Oberbayern), but those in Hessen and Nordrhein-Westfalen are named after their presiding cities, which has little practical meaning.

Should I take it to #213 or shall we discuss that here?
