### ISSUE TITLE
Wrong City for sent geopoint in tabriz city

### ISSUE THREAD

**Issue by RezaOruji** [twain47/Nominatim#518]
when i reverse geocode a point in Tabriz city(big city in iran) , it returns a wrong city name . look at this
http://nominatim.openstreetmap.org/reverse?format=json&accept-language=en&lat=38.078247&lon=46.304969
the city name should be **Tabriz** but it is wrong .

**Comment by mtmail** [comment]
I think I see what you mean.

http://nominatim.openstreetmap.org/details.php?place_id=102061357
![untitled](https://cloud.githubusercontent.com/assets/3727288/18254639/ff88b6ac-739f-11e6-849a-d178ec43f423.png)

The city Tabriz (تبريز) http://www.openstreetmap.org/node/26038590 is tagged as `admin_level=4` (province). The province is already East Azerbaijan (آذربایجان شرقی) http://www.openstreetmap.org/relation/2232180.

I'm changing it to `admin_level=8` (municipality, city) now. Let's check again in a couple of days.

**Comment by lonvia** [comment]
The admin_level on a place node won't have much effect. The problem are the newly imported boundaries like http://www.openstreetmap.org/relation/6556508. These relations are tagged admin_level=8, which Nominatim assumes is city level. Therefore they hide any city place nodes inside. My Persian is not good enough to determine what these boundaries are and the [wiki page for the import](https://wiki.openstreetmap.org/wiki/WikiProject_Iran/Iran_boundaries_import) is not useful either.

**Comment by RezaOruji** [comment]
@mtmail  @lonvia look at **Iran** in this link : http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative
the problem is that , _city_ and _rural_ in **Iran** have same admin level . the city name that Nominatim shows instead of Tabriz is actually a rural .

**Comment by lonvia** [comment]
The wiki page doesn't really help me to understand the situation in Iran. Here is my problem: normally, the assumption is that administrative area of the same admin_level must not overlap. But in the example above we have relation 6556508 which I assume is a Dehestan from what you say, so admin_level=8. But then the city of Tabriz is _inside_ even though the wiki page says that city admin borders are admin_level=8, too.

So, if you really have overlapping administrative boundary relations in admin_level=8 then the tagging is wrong and there is absolutely nothing Nominatim can do to fix that.

If, however, my assumption is wrong that place=city nodes are equivalent to admin_level=8 and if in reality all cities are inside a Dehestan or Shahr, then resolving #213 will help at some point. In the meantime, I would recommend to add place=city as an area, which will also help improve the addressing.

**Comment by mtmail** [comment]
OSM user http://www.openstreetmap.org/user/Adib%20Yz/ seems active in that area. He says he added the city boundaries http://www.openstreetmap.org/changeset/41936896

**Comment by lonvia** [comment]
Ok that has fixed the issue. Closing.
