### ISSUE TITLE
Forbidden 403 ubuntu 16.04

### ISSUE THREAD

**Issue by cetabio** [twain47/Nominatim#521]
Hi I followed the https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md but when I access my server IP/nominatim it say Forbidden 403.

Im using apache ubuntu 16.04 and apache with php 5.6 any config info needed to help me debugging this just tell me.

Ty for help.

**Comment by mtmail** [comment]
The hopefully easiest answer is: add `/search.php` to URL as `http://your_server/nominatim/` doesn't have an index.html/index.php file.

If that doesn't work check if the user account Apache uses can access the files, e.g.
`sudo -u www-data wc /where_nominatim_is_installed/Nominatim/build/website/search.php`

Lastly make sure the directory listed in `/etc/apache2/conf-available/nominatim.conf` exists. Though `sudo service apache2 restart` would print a warning if it doesn't.

**Comment by cetabio** [comment]
The hopefully easiest answer is: add /search.php to URL as http://your_server/nominatim/ 

Ty @mtmail that was the issue found it already after listing website dir
