### ISSUE TITLE
"Technological refresh" of the user interface

### ISSUE THREAD

**Issue by MKergall** [twain47/Nominatim#53]
Enhancement / Pull request

Seaching with Nominatim, I wanted to see the results as markers on the map. 
So I developed a new Web user interface to Nominatim. 

It's based on Leaflet and Jquery, and is accessing Nominatim service with Ajax json calls. So the user interface is completely distinct from the Nominatim service, which is quite good I think. 

This can be tested here: http://comob.free.fr/nominatim/
The whole source code is in index.html (so, easily accessible with a "View source code"). 

Nominatim developers can use it as a starting base, if they want.

**Comment by lonvia** [comment]
Done with #350.
