### ISSUE TITLE
How to add the correct address format for country?

### ISSUE THREAD

**Issue by RafalR** [twain47/Nominatim#531]
When I try to find a street in one city get the results of another city located in the same province. I'd like to somehow fix it.

**Comment by lonvia** [comment]
Are you asking how you can help with coding, so that your issue #479 gets fixed?

**Comment by RafalR** [comment]
Probably not. I do not fully understand how they work Nominatim and whether  supports any local address formats. I found this but I'm not sure if it is supported at this time - http://wiki.openstreetmap.org/wiki/Nominatim/Country_Address_Format

**Comment by lonvia** [comment]
Duplicate of #479.
