### ISSUE TITLE
Is this normal that we use rank_search in placex_update an rank_address in get_addressdata

### ISSUE THREAD

**Issue by RemiBou** [twain47/Nominatim#534]
Hi,

Some placex doesn't have anything when we call get_addressdata. Like this one

http://nominatim.openstreetmap.org/details.php?place_id=144938208

I think this is due to the following : in placex_update the IF " For low level elements we inherit from our parent road" is based on "NEW.rank_search > 27", if we enter this if, we don't fill the place_addressline table but just the parent_place_id. Which is fine because our place is not big and it'll get its adress from its parent.
In get_addressdata the condition for using the parent place_id is "and rank_address = 30 ", so in my exemple the place has a rank_search at 30 but a rank_address at 0 so the get_addressdata methode won't return anything.

Is this normal ? If not I'll send a pull request

**Comment by lonvia** [comment]
That looks like a bug. get_addressdata() should be checking for rank_search.

**Comment by lonvia** [comment]
Fixed in #542, which is now live. Thanks for tracking the issue down and providing a fix.
