### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Moggieggwp** [twain47/Nominatim#540]
Few days ago, everything was ok. But now when i'm trying find address details using latitude and longitude - nominatim gives me:
 "Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.
Message: Database request failed
SQL Error: DB Error: syntax error"

Example of query : http://nominatim.openstreetmap.org/search.php?&q=51.193058013916%2C15.5245780944824&addressdetails=1&format=jsonv2

Result must be like this: 
![capture2](https://cloud.githubusercontent.com/assets/16233043/19013464/432b614a-87da-11e6-8cea-483f8b3186a8.PNG)

**Comment by Moggieggwp** [comment]
Why search.php? stoped working?

**Comment by lonvia** [comment]
Fix is now deployed on nominatim.openstreetmap.org.

We've updated the server to a new version of nominatim yesterday evening. This was a bug in the new code. Thanks or reporting.
