### ISSUE TITLE
Installation error while build

### ISSUE THREAD

**Issue by yadujain** [twain47/Nominatim#544]
I am getting below error while building Nominatim using make command 

Scanning dependencies of target osm2pgsql_lib
[  1%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o
[  2%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/geometry-builder.cpp.o
[  3%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/geometry-processor.cpp.o
[  4%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/id-tracker.cpp.o
[  5%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-pgsql.cpp.o
[  6%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-ram.cpp.o
[  7%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle.cpp.o
[  8%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-persistent-cache.cpp.o
[  9%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-ram-cache.cpp.o
[ 10%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/options.cpp.o
[ 11%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/osmdata.cpp.o
[ 12%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-gazetteer.cpp.o
[ 13%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-multi.cpp.o
[ 14%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-null.cpp.o
[ 15%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/build.make:398: recipe for target 'osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o' failed
make[2]: *** [osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o] Error 4
CMakeFiles/Makefile2:437: recipe for target 'osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/all' failed
make[1]: *** [osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mtmail** [comment]
If osm2pgsql doesn't build then https://github.com/openstreetmap/osm2pgsql might be better to file an issue. They will be interested in the operating system and version, compiler version, version of the software you're trying to build and any other steps might might help to reproduce the error.

**Comment by lonvia** [comment]
Reported in https://github.com/openstreetmap/osm2pgsql/issues/627, closing here.
