### ISSUE TITLE
SQL error on reverse geocoding of interpolated address

### ISSUE THREAD

**Issue by lonvia** [twain47/Nominatim#545]
Occasionally reverse geocoding fails with the following message in the postgres error logs:

```
ERROR:  line_interpolate_point: 2nd arg isn't within [0,1]
STATEMENT:  select place_id, partition, 'W' as osm_type, osm_id, 'place' as class, 'house' as type, null admin_level, housenumber, null as street, null as isin, postcode, calculated_country_code as country_code, parent_place_id, null as linked_place_id, 30 as rank_address, 30 as rank_search, (0.75-(30::float/40)) as importance, null as indexed_status, null as indexed_date, null as wikipedia, calculated_country_code,  get_address_by_language(place_id, housenumber, ARRAY['short_name','name','brand','official_name','ref','type']) as langaddress, null as placename, null as ref, ST_X(point) as lon, ST_Y(point) as lat from (select *, ST_LineInterpolatePoint(linegeo, (housenumber-startnumber::float)/(endnumber-startnumber)::float) as point from  (select *,  CASE WHEN interpolationtype='odd' THEN floor((1*(endnumber-startnumber)+startnumber)/2)::int*2+1 WHEN interpolationtype='even' THEN ((1*(endnumber-startnumber)+startnumber)/2)::int*2 WHEN interpolationtype='all' THEN (1*(endnumber-startnumber)+startnumber)::int END as housenumber from location_property_osmline where place_id = 11679134) as blub1) as blub2
```

The problematic interpolation line is starting at this node: https://www.openstreetmap.org/node/1202725003 Note that the interpolation is odd but has an even endpoint. The error happens when the computed fraction is 1.

Need to write test case.

**Comment by lonvia** [comment]
The following test case reproduces the error:

    Scenario: Odd interpolation line with even end
        Given the places
          | osm | class | type  | housenr | street       | geometry |
          | N1  | place | house | 1       |              | 1 1 |
          | N2  | place | house | 6       |              | 1 1.1 |
        And the places
          | osm | class   | type    | housenr | geometry |
          | W10 | place   | houses  | odd    | 1 1, 1 1.1 |
        And the places
          | osm | class   | type     | name         | geometry |
          | W2  | highway | tertiary | Sun Way      | 1.001 1, 1.001 1.1 |
        And the ways
          | id  | nodes |
          | 10  | 1,2 |
        When importing
        And sending reverse coordinates 1.1,1.001
        Then results contain
         | osm_type | osm_id | display_name |
         | way        | 10   | 5, Sun Way |

The interpolation must already be outside the radius where POIs are searched. This must not happen as the interpolation should be handled in the same way as address points.

**Comment by lonvia** [comment]
We still see issues:

http://nominatim.openstreetmap.org/reverse.php?format=json&lat=-33.4885467&lon=-70.629193

**Comment by lonvia** [comment]
@mtmail I've pushed a fix for the example above. I'll leave this ticket open for a bit. If you still find examples that cause a 500, please add them here. Otherwise feel free to close.

**Comment by mtmail** [comment]
The fix worked. Deployed yesterday and the errors are gone. <edgy emoticon that expresses joy and satisfaction>
