### ISSUE TITLE
Details view for interpolated addresses doesn't work

### ISSUE THREAD

**Issue by lonvia** [twain47/Nominatim#546]
Example query: [5509 48 st, new town](https://nominatim.openstreetmap.org/search.php?q=5509+48+st%2C+new+town) and follow details link.

It would be nice if the details for the interpolation way could be shown in this case. details.html needs to search in location_propery_osmline for the appropriate parent_place_id. Bonus points if the details page also prints the information from the location_propery_osmline table.

@mtmail

**Comment by nicolas17** [comment]
I think this is also triggering a bug in the OSM website. If you search for "5509 48 st, new town" in Nominatim, the Details link goes to https://nominatim.openstreetmap.org/details.php?place_id=11679134, which says it's not a valid place ID. If you search the same on openstreetmap.org, it links to http://www.openstreetmap.org/way/11679134, and that way is somewhere *completely* different (it's assuming that place ID is a valid way ID?).

**Comment by boothym** [comment]
To expand on what @nicolas17 said, I found another error message with an unknown place id.

If I search on the OSM website for http://www.openstreetmap.org/search?query=18+Somerville+Street it gives me:
Error contacting nominatim.openstreetmap.org: No route matches {:action=>"tiger", :controller=>"browse", :id=>"175209404"}

Putting that id into http://nominatim.openstreetmap.org/details.php?place_id=175209404 gives a place in the USA rather the intended address in Scotland (another in itself!). I think the OSM site needs changed as it's assuming the placeid is a valid way/node and linking to it.

**Comment by mtmail** [comment]
Thanks @boothym. Fascinating. That `{:action=>"tiger", ` error looks like Ruby on Rails while Nominatim's frontend is written in PHP. Still the openstreetmap-website project doesn't (or shouldn't) know what `tiger` is so it must be related to the results Nominatim returns.

**Comment by lonvia** [comment]
The problems on osm.org are a different issue entirely actually. I'm tracking that now in #564.

**Comment by lonvia** [comment]
Fix is now live on osm.org.
