### ISSUE TITLE
Error request: Bad parameter 'viewbox'. Out of range.

### ISSUE THREAD

**Issue by josemamira** [twain47/Nominatim#549]
This is the query request
http://nominatim.openstreetmap.org/?format=json&addressdetails=1&q=[cafe]+sax&polygon_geojson=1&format=json&limit=100&viewbox=-0.802130699157715,38.54497682665608,-0.8500242233276368,38.52530509584052&bounded=1

Only a few minutes ago the same request was allright

**Comment by lonvia** [comment]
A sanity check for the viewbox parameter has been added [a few minutes ago](https://github.com/twain47/Nominatim/commit/6757e1b865da3e01d1ae9ce5d1e71b039e4a7a75). The expected (and documented) order for the viewbox parameter is left, top, right, bottom. You've switched left and right in your query.

**Comment by josemamira** [comment]
Oh. Sorry. Thanks
