### ISSUE TITLE
make sure PHP 5.4 is supported

### ISSUE THREAD

**Issue by billsinc** [twain47/Nominatim#555]
I've installed v2.5.1 twice to see if the problem was with my installation and I've had the same problem both times.  Reverse geocoding works properly but I'm getting errors when I hit the _details_ page `PHP Parse error:  syntax error, unexpected '[' in .../website/details.php on line 93` which keeps the page from rendering. Further, the map does not load on the search page and gives me `Uncaught ReferenceError: nominatim_map_init is not defined`.  I'm seeing the problem in Safari and Chrome at this point.

**Comment by mtmail** [comment]
Have you seen my reply on https://help.openstreetmap.org/questions/52558/multiple-errors-with-nominatim-251-installation

"This could be a mismatch of files in the /website and build/website directory. Try running the create-website setup step in https://wiki.openstreetmap.org/wiki/Nominatim/Installation again."

because I'm surprised you see an error in `website/details.php` when PHP should render `build/website/details.php`.

**Comment by billsinc** [comment]
Sorry, I didn't see a comment there prior to posting here (until I just now refreshed), investigating now, thanks.

**Comment by lonvia** [comment]
2.5.1 is still autoconf-based, so there is no `build` directory.

**Comment by billsinc** [comment]
Yes, I'm not seeing one nor any references to it.  The issue remains.  Thanks.

**Comment by lonvia** [comment]
You are using an old version of php and there are a few constructs in there that are only understood by PHP >= 5.4. I thought we had caught them all before the release but apparently not.

I've pushed [a fix for the reverse issue](https://github.com/twain47/Nominatim/commit/f42ae6b2f64ef9fe670dda8aacfd0bf98c220484) and [for the search issue](https://github.com/twain47/Nominatim/commit/6d77c08269eb1542d60ee39770240fab3011e850) to the 2.5.x branch. However, I have no way of testing this. Can you please try that branch (or apply the fixes to your version) and see if it works for you?

Alternatively switch to a newer PHP version (at least 5.4).

**Comment by billsinc** [comment]
The map renders on the _search_ page but not on the _details_ page.  The upgrade is unfortunately not trivial to go from 5.3 to 5.4 with yum as everything has to be removed first.  We can do it but it will require a more significant outage on this server.  Thanks.

**Comment by lonvia** [comment]
Same JSON_PRETTY_PRINT issue, see https://github.com/twain47/Nominatim/commit/567d81d10d2c5a2b4f1f774e5a65974f794151b5

**Comment by billsinc** [comment]
Yes, all set, thanks.

**Comment by mtmail** [comment]
I'll change the title to 'make sure PHP 5.4' is supported. The open task is to change the continuous integration tests to use PHP 5.4. I have that part working on my local machine but not checked into the main branch yet.
