### ISSUE TITLE
Deadlock Rank 16

### ISSUE THREAD

**Issue by sramp** [twain47/Nominatim#558]
Hello,
I'm running the Europe import with an underpowered hardware ( 8Mb RAM), anyway after settings adjustment as suggested by Sarah I did some progress. 
Now I get a deadlock error in the indexing phase at rank 16. 
After I have relaunched the script with ./utils/setup.php --index --create-search-indices I got anothe deadlock error. I have relaunched again and now it's working on rank 17.
Here the log of the first deadlock ( no memory errors in journalctl )

```
Done 7402 in 491 @ 15.075356 per second - Rank 16 ETA (seconds): 7744.493652
  Done 7404 in 492 @ 15.048780 per second - Rank 16 ETA (seconds): 7758.037109
index_placex: UPDATE failed: ERRORE:  rilevato deadlock
DETAIL:  Il processo 15310 è in attesa di ShareLock su la transazione 3482747; bloccato dal processo 15309
Il processo 15309 è in attesa di ShareLock su la transazione 3482746; bloccato dal processo 15310
HINT:  Vedi i log del server per i dettagli della query.
CONTEXT:  istruzione SQL "UPDATE placex SET linked_place_id = NEW.place_id WHERE place_id = linked_node_id"
PL/pgSQL function placex_update() line 137 at istruzione SQL
ERROR: Error executing external command: /srv/nominatim/Nominatim/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25
Error executing external command: /srv/nominatim/Nominatim/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25

```

Thanks in advance.

**Comment by lonvia** [comment]
There is some deadlock detection in the code but it only works with English because it has to scan the actual error message. Try running without locale:

    LANG=C ./utils/setup.php --index --create-search-indices

**Comment by MS-WebDev** [comment]
Hi,
i have the same problem (on rank 16) with an german extract

"LANG=C" doesnt solve this error:

`index_placex: UPDATE failed: FEHLER:  Verklemmung (Deadlock) entdeckt
DETAIL:  Prozess 25741 wartet auf ShareLock-Sperre auf Transaktion 23085081; blockiert von Prozess 25740.
Prozess 25740 wartet auf ShareLock-Sperre auf Transaktion 23085082; blockiert von Prozess 25741.
HINT:  Einzelheiten zur Anfrage finden Sie im Serverlog.
CONTEXT:  SQL-Anweisung »UPDATE placex SET linked_place_id = NEW.place_id WHERE place_id = location.place_id«
PL/pgSQL-Funktion placex_update() Zeile 129 bei SQL-Anweisung
ERROR: Error executing external command: /home/Nominatim/nominatim/nominatim -i -d nom_de -P 5432 -t 7 -r 5 -R 25
Error executing external command: /home/Nominatim/nominatim/nominatim -i -d nom_de -P 5432 -t 7 -r 5 -R 25`

**Comment by lonvia** [comment]
Ok, thanks for testing. I suspect we actually need to set the language for the postgres connection. See http://stackoverflow.com/questions/191428/change-language-of-system-and-error-messages-in-postgresql

**Comment by lonvia** [comment]
Could you please test, if the following patch works for you: https://github.com/lonvia/Nominatim/commit/3afe83b1b64b2cdf5dcec13cd7789eb59de652c3

Apply the patch, run `make` again and then the indexing command.

**Comment by MS-WebDev** [comment]
sorry - my import ran on an older nominatim version (2.3)

Now I continue the import with the latest release and it run without errors (Rank 16 is finished)

sorry for that

**Comment by lonvia** [comment]
You should be able to apply the patch above on any Nominatim version. Switching the Nominatim version mid-import comes with its own set of problems and is not recommended.

**Comment by SanyaBeer** [comment]
We have same problems:
```
  Slow place_id 164753168
  Done 28164 in 324 @ 86.925926 per second - ETA (seconds): 2056.083984
  Done 28194 in 324 @ 87.018517 per second - ETA (seconds): 2053.551514
  Done 28205 in 324 @ 87.052467 per second - ETA (seconds): 2052.624268
  Done 28427 in 325 @ 87.467690 per second - ETA (seconds): 2040.342041
index_placex: UPDATE failed: ОШИБКА:  обнаружена взаимоблокировка
DETAIL:  Процесс 40759 ожидает в режиме ShareLock блокировку "транзакция 348920"; заблокирован процессом 40779.
Процесс 40779 ожидает в режиме ShareLock блокировку "транзакция 348916"; заблокирован процессом 40759.
HINT:  Подробности запроса смотрите в протоколе сервера.
CONTEXT:  при блокировке кортежа (1180663,3) в отношении "placex"
SQL-оператор: "UPDATE placex SET linked_place_id = NEW.place_id WHERE place_id = linked_node_id"
функция PL/pgSQL placex_update(), строка 137, оператор SQL-оператор
ERROR: Error executing external command: /home/nominatim/Nominatim-2.5.1/nominatim/nominatim -i -d nominatim -P 5432 -t 31 -r 5 -R 25
Error executing external command: /home/nominatim/Nominatim-2.5.1/nominatim/nominatim -i -d nominatim -P 5432 -t 31 -r 5 -R 25
```
Sorry for logs on Russian. Seems indexing working only in one thread (--thread 1). But it more slowly in one thread then in 31, yes? 
We import latest full planet pbf (29.12.2016). Hardware 32CPU cores, 64GB RAM, 3TB HDD (3x1TB RAID). Postgres 9.4, Postgis 2.1
