### ISSUE TITLE
Error on installing nominatim

### ISSUE THREAD

**Issue by soulraven** [twain47/Nominatim#559]
Hello,
i have some problems on installing nominatim,

> Building index on table: planet_osm_rels
> Stopped table: planet_osm_nodes in 0s
> Stopping table: planet_osm_ways
> Stopped table: planet_osm_ways in 0s
> Killed
> ERROR: Error executing external command: /opt/Nominatim-2.5.1/osm2pgsql/osm2pgsql --flat-nodes /opt/Nominatim-2.5.1/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 -C 18000 -P 5432 -d nominatim /opt/europe-latest.osm.pbf
> Error executing external command: /opt/Nominatim-2.5.1/osm2pgsql/osm2pgsql --flat-nodes /opt/Nominatim-2.5.1/flatnode.file -lsc -O gazetteer --hstore --number-processes 1 -C 18000 -P 5432 -d nominatim /opt/europe-latest.osm.pbf

**Comment by lonvia** [comment]
You've most likely run out of run and one of the programs was killed. Check /var/log/syslog for any messages about being out of memory.

**Comment by soulraven** [comment]
i manage to get the errors with out of memory,
https://dpaste.de/Gg2W

> Oct 26 06:13:41 geo2 kernel: [79777.242570] Out of memory: Kill process 1235 (osm2pgsql) score 670 or sacrifice child
> Oct 26 06:13:41 geo2 kernel: [79777.245869] Killed process 1235 (osm2pgsql) total-vm:20387664kB, anon-rss:8392632kB, file-rss:0kB

You have any ideea how to prevent this?

**Comment by mtmail** [comment]
In OpenStreetMap Europe is about 1/3 of the data of the world. You should have at least 32GB of RAM https://wiki.openstreetmap.org/wiki/Nominatim/Installation#Hardware for the osm2pgsql step of the installation.

**Comment by soulraven** [comment]
i have installed on this current system last time the same Europa file,
Also i have a server identical with this, and is working just fine, so i guess the RAM memory is not a issue
