### ISSUE TITLE
Wrong ST_Distance_Spheroid definition in ./utils/setup.php

### ISSUE THREAD

**Issue by AlexMakII** [twain47/Nominatim#560]
Looks like ./utils/setup.php contains wrong definition of function ST_Distance_Spheroid.

Now - gives errors "Unknown function":
ALTER FUNCTION ST_Distance_Spheroid(geometry, double precision)

Should be:
ALTER FUNCTION ST_Distance_Spheroid(geometry, geometry, spheroid)

My setup: debian jessie, postgresql 9.4, postgis 2.1

**Comment by mtmail** [comment]
We added another check two weeks ago (https://github.com/twain47/Nominatim/commit/a855ffe) and haven't released a new stable release since then yet (http://www.nominatim.org/).

**Comment by lonvia** [comment]
There was too much copy&paste in the commit @mtmal mentioned. Fixed now. Thanks for reporting.
