### ISSUE TITLE
Lua dependency

### ISSUE THREAD

**Issue by VonTalavang** [twain47/Nominatim#561]
I noticed that lua is "optional"...

but isnt.
the make file keeps giving me errors:
/usr/bin/ld: cannot find -llua50
and many more about Lua.

Is there a way to disable this in the makefile ?

**Comment by lonvia** [comment]
Which version of Nominatim are you using? For the current master branch (using cmake) it should be disabled by force.

If you are using the latest release, it cannot be disabled easily. Best way is probably to hack `osm2pgsql/config.h` and change `HAVE_LUA 1` to `HAVE_LUA 0`. Or simply make sure that there is only one version of the lua libraries in your system.

**Comment by VonTalavang** [comment]
2.5.1
i did an ./autogen.h, make...
and was solved.
i dont know why or how

**Comment by lonvia** [comment]
Ok, great.
