### ISSUE TITLE
language inconsistency for the search result display on osm.org

### ISSUE THREAD

**Issue by dieterdreist** [twain47/Nominatim#563]
Languages are mixed up in the search results. I am logged in, language set to English, my browser language is German, and some results display a German name, e.g. "Vereinigte Staaten von Amerika" rather then USA.
![screen shot 2016-10-25 at 12 10 32](https://cloud.githubusercontent.com/assets/581288/19682065/392418ec-9aac-11e6-9854-8ef3c2f6281e.png)

**Comment by lonvia** [comment]
This is intentional. Each part of the address is localized separately according to the requested accepted languages. osm.org sends the browser languages as accept-language, so in your case you end up with German localizations where possible.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 25 ott 2016, alle ore 13:35, Sarah Hoffmann <notifications@github.com> ha scritto:
> 
> This is intentional. Each part of the address is localized separately according to the requested accepted languages. osm.org sends the browser languages as accept-language, so in your case you end up with German localizations where possible.


then it is a bug of the osm website, because if I have deliberately set the language in my profile settings to English, it should not care for the browser language.

**Comment by mtmail** [comment]
Makes sense. You can file an issue for the website here: https://github.com/openstreetmap/openstreetmap-website/issues/
