### ISSUE TITLE
interpolations and tiger results return wrong osm_id

### ISSUE THREAD

**Issue by boothym** [twain47/Nominatim#564]
Searched on OSM first, http://www.openstreetmap.org/search?query=22+Murray+Park - locates the address correctly, but it links to the wrong way: http://www.openstreetmap.org/way/26041327

Tried Nominatim, http://nominatim.openstreetmap.org/search.php?q=22+Murray+Park but again it tries to link to the same way: http://nominatim.openstreetmap.org/details.php?place_id=26041327

If I add the town (St Andrews) or use a different street/place (try 3 Nethergate, Crail) the same thing happens.

However if I use 20 Murray Park, it locates and correctly links to the address node (of course!).

**Comment by mtmail** [comment]
Thanks for reporting. This would be a same issue as https://github.com/twain47/Nominatim/issues/546. I hope to fix that during the upcoming OpenStreetMap hack weekend.

**Comment by lonvia** [comment]
There is actually two errors here. One is indeed the same as #546. The other is that for interpolations osm_id contains the place_id and not the way id. that needs fixing, too. The result should point to the interpolation way.

**Comment by lonvia** [comment]
tiger interpolations return wrong osm_ids as well see comments in #546.

Once that is fixed, the osm webiste needs to be changed to understand the new tiger osm type. I will open an issue for that.

Changed title to reflect the issue.

**Comment by mtmail** [comment]
I checked pull request https://github.com/twain47/Nominatim/pull/570 against an import of Scotland and "22 Murray Park" works if applied.

**Comment by mtmail** [comment]
Test case:
http://nominatim.openstreetmap.org/search.php?q=5598,Kimberly+Rd,Bryan,OK&format=json

```json
[
  {
    "importance": 0.301,
    "type": "house",
    "class": "place",
    "place_id": "184830193",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
    "osm_type": "tiger",
    "osm_id": "184830193",
    "boundingbox": [
      "34.007655",
      "34.007755",
      "-96.433218",
      "-96.433118"
    ],
    "lat": "34.007705",
    "lon": "-96.433168",
    "display_name": "5598, Kimberly Road, Durant, Bryan County, Oklahoma, 74701, United States of America"
  }
]
```

It should return `"osm_type": "way"` and the correct `osm_id` (not a copy of `place_id`).

And http://www.openstreetmap.org/search?query=5598%2CKimberly%20Rd%2CBryan%2COK should not display a ` No route matches {:action=>"tiger", :controller=>"browse", :id=>"184830193"}` error

raw Tiger data
```
40013.sql:select tigger_create_interpolation(ST_GeomFromText('LINESTRING(-96.433464 34.007707,-96.433769 34.007711)',4326), '5550', '5598', 'even', 'Kimberly Rd', 'Bryan, OK', '74701');
40013.sql:select tigger_create_interpolation(ST_GeomFromText('LINESTRING(-96.433467 34.007543,-96.433772 34.007547)',4326), '5551', '5599', 'odd', 'Kimberly Rd', 'Bryan, OK', '74701');
```

**Comment by mtmail** [comment]
I imported the area around Bryan
```
osmconvert oklahoma-latest.osm.pbf -b=-96.616516,33.644349,-95.784302,34.282184 --out-pbf -o=bryan.osm.pbf
./utils/setup.php --osm-file ../data/bryan.osm.pbf --all
```
plus the related Tiger postcode
```
cp 40013.sql Nominatim/data/tiger
 ./utils/setup.php --import-tiger-data
```
and set
```
   @define('CONST_Use_US_Tiger_Data', true);
```
and can confirm that https://github.com/twain47/Nominatim/pull/570 also fixes the issue.

```
curl 'http://localhost/nominatim/search.php?q=5592%2C+Kimberly+Rd%2C+Bryan&format=json'
[
  {
    "place_id": "139171",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
    "osm_type": "way",
    "osm_id": "14689980",
    "boundingbox": [
      "34.0076605",
      "34.0077605",
      "-96.433780875",
      "-96.433680875"
    ],
    "lat": "34.0077105",
    "lon": "-96.433730875",
    "display_name": "5592, Kimberly Road, Durant, Bryan, 74701, United States of America",
    "class": "place",
    "type": "house",
    "importance": 0.211
  }
]
```

**Comment by lonvia** [comment]
Fix is now live on osm.org.
