### ISSUE TITLE
Setup --create-functions doesn't work with remote PgSQL instanace

### ISSUE THREAD

**Issue by billsinc** [twain47/Nominatim#566]
Just did a brand new install on a CentOS 7 machine.  We are using PostgreSQL at AWS RDS and not locally on the CentOS instance.  When I run `./utils/setup.php --create-functions` I get the following error message:

> Functions
> psql: could not connect to server: No such file or directory
>     Is the server running locally and accepting
>     connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
> ERROR: pgsql returned with error code (2)
> pgsql returned with error code (2)

If I start the local instance of PgSQL, it connects fine but it's obviously ignore the connection string in my config file to the remote instance.  Do I need to specify it somewhere else? Thanks.

I'm using PHP v7 and PgSQL v9.3.

**Comment by mtmail** [comment]
You can have a look at this recent pull request for connecting to remote databases https://github.com/twain47/Nominatim/pull/552

But I don't think that help you with AWS RDS. It's assumed you have full access to the database server and you'd need to also push (copy) the compiled `nominatim.so` shared library to the database server's filesystem. AWS RDS doesn't allow that. (nominatim.so handles query normalization at index and search time).

**Comment by pranavbhargava** [comment]
We are in the same situation, have the data in RDS, but cant seem to get Nominatim connect to it. Any progress on this?

**Comment by mtmail** [comment]
AWS RDS doesn't allow installing of shared libraries (in our case the file `nominatim.so`) to their servers.

**Comment by bisoldi** [comment]
RDS actually does allow installing shared libraries, but not those 
written in C/C++.  It allows SO's written in: PL/pgSQL, PL/Tcl, PL/Perl 
and PL/V8.

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions

I found that out the hard way! :)

**Comment by lonvia** [comment]
Nothing we can do here really. I remember that some years ago someone wrote a pure PL/pgSQL replacement for nominatim.so but I can't find that code anymore. You might try to go down that road as well but it's unlikely that there will be ever official support for something like that as I don't have the time to maintain it.
