### ISSUE TITLE
country_code of Kosovo: rs vs xk

### ISSUE THREAD

**Issue by muratia** [twain47/Nominatim#567]
http://nominatim.openstreetmap.org/search?q=Gjilan&format=json&polygon=0&addressdetails=1

[{"place_id":"1244873","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"node","osm_id":"299448609","boundingbox":["42.3034051","42.6234051","21.308409","21.628409"],"lat":"42.4634051","lon":"21.468409","display_name":"Gjilan, Komuna e Gjilanit, Kosova","class":"place","type":"city","importance":0.57239695346006,"icon":"http:\/\/nominatim.openstreetmap.org\/images\/mapicons\/poi_place_city.p.20.png","address":{"city":"Gjilan","county":"Komuna e Gjilanit","country":"Kosova","country_code":"rs"}},{"place_id":"74039569","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"38167080","boundingbox":["42.4616075","42.462677","21.468622","21.4704886"],"lat":"42.4622523","lon":"21.4696809","display_name":"Xhemë Tupalla, Gjilan, Komuna e Gjilanit, 60000, Kosova","class":"highway","type":"residential","importance":0.21,"address":{"road":"Xhemë Tupalla","city":"Gjilan","county":"Komuna e Gjilanit","postcode":"60000","country":"Kosova","country_code":"rs"}},{"place_id":"12931878","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"node","osm_id":"1222862561","boundingbox":["42.6306937","42.6307937","21.1499652","21.1500652"],"lat":"42.6307437","lon":"21.1500152","display_name":"Gjilan, Rrafshi i Kosovës, Lagja NIC, Чаглавица, Komuna e Prishtinës, 38000, Kosova","class":"highway","type":"motorway_junction","importance":0.111,"address":{"junction":"Gjilan","road":"Rrafshi i Kosovës","suburb":"Lagja NIC","village":"Чаглавица","county":"Komuna e Prishtinës","postcode":"38000","country":"Kosova","country_code":"rs"}}]

This is the JSON returned form the link 
But Country code is "rs" while it should be "xk".

**Comment by mtmail** [comment]
I'm changing the title as 'found incorrect data' isn't precise enough.

**Comment by muratia** [comment]
OK

**Comment by SomeoneElseOSM** [comment]
If it helps, here's what I saw when I looked at Kosovo a week or so ago:
Here's Kosovo in OSM:

http://www.openstreetmap.org/relation/2088990#map=8/42.567/20.901

http://osm.mapki.com/history/relation.php?id=2088990

There's no "RS" anywhere there.  The "rs" that appears greyed-out at http://nominatim.openstreetmap.org/details.php?place_id=159334847 I've always interpreted as "somewhere nearby" (but I'm no Nominatim expert, obviously).

The Kosovo relation has:
ISO3166-1:alpha2     XK
ISO3166-1:alpha3     XXK

and the Serbia relation has:
ISO3166-1     RS
ISO3166-1:alpha2     RS
ISO3166-1:alpha3     SRB
ISO3166-1:numeric     688

So is it possible that a missing "ISO3166-1" for Kosovo is the problem?

**Comment by lonvia** [comment]
Kosovo currently isn't in Nominatim's [base country table](https://github.com/twain47/Nominatim/blob/master/data/country_osm_grid.sql). This table has been generated manually and needs to be redone at some point.

**Comment by muratia** [comment]
I am a software developer with lot of background in databases.

**Comment by lonvia** [comment]
The table I was referring to contains the geometry of the country.

**Comment by muratia** [comment]
Currently Kosovo hasn't done demarcation with all neighbors so the Geometry can be with errors.

**Comment by SomeoneElseOSM** [comment]
@lonvia just wondering what are the next steps here?  Does someone need to download and install Nominatim, figure out the format of https://github.com/twain47/Nominatim/blob/master/data/country_osm_grid.sql?raw=true , edit Serbia in there and create a new entry for Kosovo based on the existing OSM borders?  If so, is there any documentation that could help with that process, and does anything else need doing to link to "new country"?  Pardon my ignorance of Nominatim here; I'm aware of it only as a black box that things go into and things come out of... Presumably there are other country issues too (https://trac.openstreetmap.org/ticket/5305#ticket has been around for a while; is e.g. South Sudan a "country" in Nominatim too?).

**Comment by lonvia** [comment]
To be honest, I don't know exactly (incidentally that's what's the biggest blocker for this issue at the moment). country_osm_grid contains the polygons made from OSM administrative boundaries and split into convenient squares for faster lookup. There is a script that creates the table from an existing Nominatim database. So roughly the following needs to be done:

- import a Nominatim database (filter boundary relations with admin_level < 8 from a planet, that's sufficient)
- update country_name table (add new countries preferably by copying data from the relevant placex entries)
- create new country_osm_grid table using sql/country_grid.sql
- repeat: visualize result, check for errors, fix OSM data, create new country_osm_grid
- dump country_osm_grid and country_name tables

Note that the country_osm_grid.sql file has become a bit too large to host in a github repo, so we'll probably have to host an updated version somewhere else. So if somebody wants to take this update on, I would prefer to get a PR for country_name.sql only and have the grid table separate. Bonus points if you can also provide a visual diff between the old and the new content of country_osm_grid.

**Comment by lonvia** [comment]
country_name has been updated in e77a07cbb3d1114e8c26c8558bf96ec1a6d633dc. For country_osm_grid.sql we have created an updated version. Both are deployed on osm.org. We still need a place to permanently put the updated version. Progress for this is tracked on #616.

Kosovo should now appear fine in search results, so closing here.
