### ISSUE TITLE
Restrict search to nodes associated with Routes?

### ISSUE THREAD

**Issue by dbenoff** [twain47/Nominatim#574]
I am attempting to reliably retrieve the correct roadway names from Nominatim given lat/lon.  Address and all other details are unimportant to me.

My issue is that in many cases I get back a node representing an establishment, and the street information for the establishment is wrong.  

Example (Should be Sunset Boulevard, not Logan Street): http://nominatim.openstreetmap.org/reverse?format=xml&lat=34.07705000&lon=-118.258030&zoom=18&addressdetails=1

Ideally I would like to exclude these establishment entries if possible and restrict the search to roadways (which I believe in OSM terms means restrict the search to nodes associated with a route).

I would very much appreciate if someone could advise me whether this is possible (with or without my own Nominatim server).

**Comment by lonvia** [comment]
Just add the appropriate zoom parameter. For street level that would be zoom=16.

**Comment by dbenoff** [comment]
Thanks so much, that worked perfectly.  Much appreciated.
