### ISSUE TITLE
Reverse Geocoding doesn't return address for OSM Type and ID

### ISSUE THREAD

**Issue by SrihariThalla** [twain47/Nominatim#576]
Hi!

I've tried Reverse Geocoding with OSM Type and ID for a Node, Dallas, and Nominatim couldn't resolve it!

Here is the issue:

* https://www.openstreetmap.org/node/26506087
* https://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=26506087
* Open MapQuest geocodes it!! https://open.mapquestapi.com/nominatim/v1/reverse.php?key=YJvzgLDkgcETw7cFuY3pBP8fgvYYATKW&format=json&osm_type=N&osm_id=26506087
(I'll remove the key later!)

However, it does work for Austin and others:

* https://www.openstreetmap.org/node/1801308037
* http://nominatim.openstreetmap.org/reverse?osm_type=N&osm_id=1801308037

What am I missing?

**Comment by lonvia** [comment]
This is a data issue. The node is tagged with 'boundary=administrative' which makes no sense for a node and so the node is rejected by Nominatim (that's a recent change, MapQuest is running on an older version of Nominatim). Remove the tag and all should be well.

**Comment by SrihariThalla** [comment]
Thanks, @lonvia! The tags `admin_level=8` and `border_type=city` don't make any sense either. Removed them!

BTW, those tags are properly set for county and city relations.
* County - https://www.openstreetmap.org/relation/1837698
* City - https://www.openstreetmap.org/relation/6571629
