### ISSUE TITLE
undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'

### ISSUE THREAD

**Issue by choissac** [twain47/Nominatim#577]
I keep having this error: 

-- Build files have been written to: /srv/nominatim/build
[ 30%] Built target osm2pgsql_lib
[ 31%] Linking CXX executable osm2pgsql
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_get_cert_store@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_check_private_key@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_get_current_compression@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ENGINE_by_id@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ERR_put_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `BIO_s_socket@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_get_version@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `BIO_int_ctrl@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `CRYPTO_get_id_callback@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ENGINE_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ASN1_STRING_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `BIO_clear_flags@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `OPENSSL_config@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_get_current_cipher@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_NAME_get_entry@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_STORE_load_locations@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ASN1_STRING_length@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CIPHER_get_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `sk_num@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_set_ex_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_set_verify@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ERR_clear_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ENGINE_init@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CIPHER_get_bits@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_connect@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_NAME_get_index_by_NID@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_use_PrivateKey@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_STORE_set_flags@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `sk_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_pending@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ENGINE_finish@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `BIO_new@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `ENGINE_load_private_key@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `BIO_set_flags@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_get_ext_d2i@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `X509_NAME_ENTRY_get_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `CRYPTO_get_locking_callback@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `sk_value@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `CRYPTO_set_id_callback@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpq.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
osm2pgsql/CMakeFiles/osm2pgsql.dir/build.make:103: recipe for target 'osm2pgsql/osm2pgsql' failed
make[2]: *** [osm2pgsql/osm2pgsql] Error 1
CMakeFiles/Makefile2:602: recipe for target 'osm2pgsql/CMakeFiles/osm2pgsql.dir/all' failed
make[1]: *** [osm2pgsql/CMakeFiles/osm2pgsql.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

My current openssl version is 1.0.2g (Ubuntu 16.04) I tried to install 1.0.0 but no luck. Does anyone know why I have this error and how to fix it?

Thanks,

**Comment by lonvia** [comment]
This must be a problem with your system installation unrelated to Nominatim. I've just tried on a freshly installed Ubuntu 16.04 and it compiles without issues.

**Comment by choissac** [comment]
I figured out what was the problem. This was because of Anaconda.

**Comment by pentateu** [comment]
Hi @choissac what did you do to fix it ?

**Comment by andrewsilva9** [comment]
@pentateu Might not be the most helpful, but I just removed Anaconda and redirected to my system's other python2.7 install and it worked for me.

**Comment by choissac** [comment]
@pentateu I did what @andrewsilva9 did. I uninstalled Anaconda and used Ubuntu's python 2.7.

**Comment by groakat** [comment]
Instead of uninstalling anaconda and reinstalling it, you can just temporarily rename the anaconda folder.

**Comment by apaulworks** [comment]
@andrewsilva9 How did you redirect your system to python2.7? When uninstall or rename anaconda, the build process still looks for the anaconda libs.

**Comment by udion** [comment]
@apaulworks  @andrewsilva9 please tell me how did you guys resolve the issue? I'm facing it right now
