### ISSUE TITLE
JAVA API Unable to geocode

### ISSUE THREAD

**Issue by Noooorm** [twain47/Nominatim#580]
Hi folks,

I have the following code : 

	public void ComputeReverseGeoLocation(Double longitude, Double latitude) {
		
		NominatimReverseGeocodingJAPI reversegeocoding = new NominatimReverseGeocodingJAPI();
		Address address = reversegeocoding.getAdress(latitude, longitude);
		
		setCity(address.getCity());
		setCounty(address.getCounty());
		setState(address.getState());
		setCountry(address.getCountry());
		setSuburbs(address.getSuburb());
		setCountryCode(address.getCountryCode());
		setLod(address.getLod());
		setPostalCode(address.getPostcode());
		setRoad(address.getRoad());		
	}

When I call it, I get : Unable to geocode

The weird thing is that it used to work a few weeks ago ...

Thoughts ?

**Comment by mtmail** [comment]
I don't see that the software library (I assume http://www.daniel-braun.com/technik/reverse-geocoding-library-for-java/) is setting a user-agent. That would be against the https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy when you run queries against the nominatim.openstreetmap.org server. If you also run query fast it's likely you got blocked.

**Comment by Noooorm** [comment]
Mmmmm interesting ...

What would be your suggestion in that matter ? 

I'm building a Java/Vaadin Web app and kinda require to have reverse geocoding. Is there a way to use Nominatim in this context ? I am using Openstreetmap

Cheers

Norm.

**Comment by mtmail** [comment]
* Several companies offer a Nominatim API with support, all with a free quota and then pricing depending on number of requests. See the first section on https://wiki.openstreetmap.org/wiki/Nominatim for links. I'm sure you'll find one that fits your need, maybe your number of requests per day is within their free quota.

* You can contact the other of the Java library to add the feature to set a user-agent, then stay below the 1 request per second limit.

* You can install Nominatim on your own server. https://wiki.openstreetmap.org/wiki/Nominatim/Installation

**Comment by lonvia** [comment]
Can you give an example input location where you get the answer 'Unable to geocode'? Please also provide the exact URL the library sends to our servers.

**Comment by lonvia** [comment]
Reporter did not answer follow-up questions. Closing.
