### ISSUE TITLE
Removing specific geographical regions

### ISSUE THREAD

**Issue by hpadhuka** [twain47/Nominatim#585]
Hello,
I currently have an Nominatim setup for the openstreetmap planet file. The setup is taking close to 1.5 TB of disk space. Is there a simple way to delete regions/countries to save as some disk space (E.g. south america/Africa )

Thanks,
- Hari

**Comment by mtmail** [comment]
Is the full planet already imported? Are you running hourly/daily/weekly updates? If you don't run updates then you can check https://github.com/twain47/Nominatim/pull/322 for a list of essential database tables, all other tables can be deleted.

For a new installation you can select the countries/continents you need from http://download.geofabrik.de/ and then merge the files, see first answer on https://help.openstreetmap.org/questions/48843/merging-two-or-more-geographical-areas-to-import-two-or-more-osm-files-in-nominatim

Raw data of the planet is 32GB, Europe 17GB, Africa 1.5 GB, South America 1 GB. By removing Africa and South America you potentially only save 8% data.

**Comment by hpadhuka** [comment]
Thanks for the reply. The full planet is already imported. I use 
utils/update.php --import-osmosis-all --no- npi 
For updates. Any other way to reduce disk space ?

**Comment by mtmail** [comment]
Do you remember how much disc space the database took after you installed Nominatim? I've never seen 1.5TB used, a full planet install should be around 800GB these days. With incremental updates the database indices grow over time and reindexing those can help.

See https://lists.openstreetmap.org/pipermail/dev/2016-August/029432.html, where @rory points to https://github.com/rory/pgindexrebuild

**Comment by rory** [comment]
Yes, it's possible you are suffering from index (or table) bloat. Especially if you are doing lots of updates. 1.5TB sounds like it's definitely bloat. The [PostgreSQL wiki has a page on measuring disk usage](https://wiki.postgresql.org/wiki/Disk_Usage). This can tell you *were* your 1.5T are going.   There's a [nagios plugin for checking postgres, incl bloat](https://github.com/bucardo/check_postgres), it might tell you for sure if it's bloat. But it can be a little hard to just run that script if you're not using nagios.

You could try my [pgindexrebuild](https://github.com/rory/pgindexrebuild) to reduce index bloat. If you want something simplier (which will affect performance) you can use [PostgreSQL's `REINDEX`](https://www.postgresql.org/docs/9.6/static/sql-reindex.html).  [pgtoolkit](https://github.com/grayhemp/pgtoolkit) can help with table bloat. Both programmes have a `--dry-run` option which won't actually make any changes, but should print out information telling you how much (if any) bloat there is.

**Comment by lonvia** [comment]
This sounds like you are running a pretty old version of Nominatim. A lot has happened in the code in the last two versions to reduce the required database size. If it is an option, consider moving to the latest version from github, postgres 9.5 or 9.6 and then reimport the database. It will save you at least 50% of disk space, index bloat already included.

**Comment by lonvia** [comment]
You can import and update specific regions using the [Geofabrik extracts](http://download.geofabrik.de/). If you need to merge multiple extracts, merge them before import using for example osmium-tool or osmosis and use the script in issue #60 to keep the database up to date.

It is not recommended to cut down an existing database.
