### ISSUE TITLE
Nominatim instalation stuck

### ISSUE THREAD

**Issue by carvalhoelder** [twain47/Nominatim#588]
Hi guys!

Executing:
/home/nominatim/Nominatim-2.5.1/utils/setup.php --osm-file /home/nominatim/data/latest.osm.pbf --all --osm2pgsql-cache 1024 2>&1 | tee setup.log

I'm stuck 24hrs on step (tail setup.log):
Node-cache: cache=1024MB, maxblocks=131072*8192, allocation method=11
Mid: pgsql, scale=10000000 cache=1024
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/nominatim/data/latest.osm.pbf
Using PBF parser.
Processing: Node(13770k 222.1k/s) Way(0k 0.00k/s) Relation(0 0.00/s)

In _postregs_ select * from pg_stat_activity;  returns: 0 rows
I've restarted the process several times...

Any idea?

**Comment by mtmail** [comment]
Which city/country/countries are you trying to import? Do you see the system swapping RAM to disc?

The `osm2pgsql-cache` of 1GB is enough for tiny countries (Lichtenstein, Monaco, Andorra which are basically just one city) but for large countries it's: the more RAM, the better.

For testing we use 2GB RAM virtual machines, anything less and `osm2pgsql` fails (with an error message).

**Comment by carvalhoelder** [comment]
Hi mtmail!
I'm using a AWS m4.large (2vCPU / 8GB RAM) machineTrying to import SouthAmerica! 
file: http://download.geofabrik.de/south-america-latest.osm.pbf

**Comment by lonvia** [comment]
If you don't see activity in postgres, then osm2pgsql has most likely died. Do you still see a process named osm2pgsql in your process list? If not find out what killed it. Most of the time it is because some process ran out of memory and has been killed. Check the output of the `dmesg` command and the postgresql log files.

**Comment by lonvia** [comment]
Closing because reporter did not respond.
