### ISSUE TITLE
Road not found from address

### ISSUE THREAD

**Issue by PinkDuck** [twain47/Nominatim#589]
I searched for "Barber Place, Norwich", no results returned.

I expected to see http://www.openstreetmap.org/way/50733911, as it is a road named "Barber Place", whose nearest city is "Norwich".

I suspect nothing was returned as that road is not within the Norwich city admin boundary but is in Thorpe St Andrew, a civil parish of Broadland district.

Humans (and Google Maps) can understand and find the result.

**Comment by lonvia** [comment]
This is out-of-scope for Nominatim. It's not designed for that level of guessing.

**Comment by PinkDuck** [comment]
I guess I have misunderstood the aim of Nominatim then. Time wasted once more.
