### ISSUE TITLE
Data last updated:  DB Error: no such table during osm import

### ISSUE THREAD

**Issue by ambross** [twain47/Nominatim#590]
After start importing whole planet osm file into database, when I open browser to see progress , I get this message in home page. 
```
Data last updated: 
DB Error: no such table
````
For that reason I can't access to reverse search system. 

But If I import one single country osm, it works fine. What possibly be wrong? Do I have to wait for whole import to be completed? 

My system spec:
4 core
3.4 GZ processing
16 GB RAM
2 TB hard disk sata

**Comment by mtmail** [comment]
> Do I have to wait for whole import to be completed?

Yes, the last step in the `./utils/setup.php` is building the search indices and the search doesn't work until those are ready. You could check the number of places in the `place` and `placex` table but the output on the terminal is a better guide.

I'm currently running a planet import with 8core, 64GB RAM and SSDs and I'm hopeful it will take 48h. It will take longer with non-SSD discs.

**Comment by Andriuskislas** [comment]
Hi, thanks for reply.Yes, I also figured that out by importing a medium sized database.
