### ISSUE TITLE
http://localhost/nominatim ERROR 403  Forbidden

### ISSUE THREAD

**Issue by lkchao78** [twain47/Nominatim#591]
Hello,

I've followed the github documentation in order to install nominatim on a Ubuntu server but I've got an issue  when I try to access to http://localhost/nominatim : I have a "403" error, it's probably about a bad permission but I don't know where would be the source.

Here is my nominatim.conf
```
<Directory "$USERHOME/Nominatim/build/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  Require all granted
</Directory>

Alias /nominatim $USERHOME/Nominatim/build/website
```

So if someone met this issue before and got the solution it will be nice =)

**Comment by mtmail** [comment]
Make sure the webserver user (I'm guessing `www-data` based on https://github.com/lkchao78/Nominatim) can read files in the `$USERHOME/Nominatim/build/website` directory. For example `chmod a+x $USERHOME`, maybe repeat for the subdirectories.

**Comment by lkchao78** [comment]
I've already checked this part as suggested in the guide, USERHOME and its subdirectories have all the execution rights allowed to all.

**Comment by lonvia** [comment]
Does `http://localhost/nominatim/search.php` work? If yes, then you need to tell Apache what to use as default index page by adding `DirectoryIndex search.php` to your Directory section.

**Comment by lkchao78** [comment]
http://localhost/nominatim/search.php is working indeed.
So I've added the DirectoryIndex search.php to my nominatim.conf and http://localhost/nominatim is ow redirected yo search.php.
I was so focused on the permission I didn't think about it. Thanks !
