### ISSUE TITLE
"Search for more results" should honor countrycodes

### ISSUE THREAD

**Issue by hangy** [twain47/Nominatim#596]
If you use a query with a country code, ie. `/search?format=html&countrycodes=de&q=something`, then the `$sMoreURL` used for the "Search for more results" button no longer contains the `countrycodes` restriction.

I think it would be better to use this parameter for paginated queries, so that the restriction is applied to follow-up searches.

**Comment by lonvia** [comment]
Fixed an deployed on osm.org.

**Comment by hangy** [comment]
Works great, thank you! :+1:
