### ISSUE TITLE
blacklist all ips except one

### ISSUE THREAD

**Issue by Andriuskislas** [twain47/Nominatim#599]
I have installed nominatim planet database for a research work. I would like to block any ips to access nominatim  api expect one my own. I am using nginx for serving static file, I can restrict my server using nginx but I would like to know if is there any nominatim way to do this.

**Comment by lonvia** [comment]
No, there isn't anything built-in to restrict IPs. You could add a check in lib/init-website.php. That would be picked up by all the scripts accessible via the web interface. But I wouldn't recommend that. You shouldn't give anybody a chance to execute any php if they have no business using your installation in the first place. Blocking them in nginx already is much better.

**Comment by Andriuskislas** [comment]
@lonvia , Thanks , I got it.
