### ISSUE TITLE
Using WMS

### ISSUE THREAD

**Issue by aimdev** [twain47/Nominatim#602]
I have the tile based nominatim application working perfectly, however, substituting the WMS string in setting/local.php does not return a map, but all other functions are ok.

No errors in the browser error log.

The wms string, to the local UMN mapserver, is the same as the one used in openlayers.

//@define('CONST_Map_Tile_URL', 'http://osm.foo.bar/osm_tiles/{z}/{x}/{y}.png');  
@define('CONST_Map_Tile_URL', 'http://wms.foo.bar/cgi-bin/mapserv?map=/var/www/wms/wms.map&');

Any assistance would be helpful.

Thanks
Aimee

**Comment by mtmail** [comment]
Nominatim's website uses http://leafletjs.com/ and that doesn't support WMS without a plugin. You can load the https://github.com/heigeo/leaflet.wms plugin in HTML (`lib/templates/includes/html-footer.php`) and change `website/js/nominatim-ui.js` according to the plugin's documentation.

Nominatim's focus is the search itself, the website is secondary and meant to be for debugging.
