### ISSUE TITLE
`city_district` does not return any results

### ISSUE THREAD

**Issue by redgluten** [twain47/Nominatim#603]
Despite being mentioned in the API documentation, the `city_district` parameter does not seem to return any results in `search`.

Examples: 

- [`https://nominatim.openstreetmap.org/search?city=Berlin&city_district=Pankow&format=json&addressdetails=0`](https://nominatim.openstreetmap.org/search?city=Berlin&city_district=Pankow&format=json&addressdetails=0) returns the geographical center Berlin, compare with a [search on the debug interface](http://nominatim.openstreetmap.org/search.php?q=Berlin+Pankow&polygon=1&viewbox=).

- [`https://nominatim.openstreetmap.org/search?city_district=Pankow&format=json&addressdetails=0`](https://nominatim.openstreetmap.org/search?city_district=Pankow&format=json&addressdetails=0) omitting the `city` parameter returns empty, compare with a [search on the debug interface](http://nominatim.openstreetmap.org/search.php?q=Pankow&polygon=1&viewbox=).

- [`https://nominatim.openstreetmap.org/search?city=Paris&city_district=18e+arrondissement&format=json&addressdetails=0`](https://nominatim.openstreetmap.org/search?city=Paris&city_district=18e+arrondissement&format=json&addressdetails=0) returns the geographical center of Paris, compare with a [search on the debug interface](http://nominatim.openstreetmap.org/search.php?q=paris+18e+arrondissement&polygon=1&viewbox=).

**Comment by lonvia** [comment]
Which documentation are you referring to? https://wiki.openstreetmap.org/wiki/Nominatim#Parameters only mentions `street`, `city`, `county`, `state` and `country` as valid input parameters.

**Comment by lonvia** [comment]
There are no specific plans but it should be fairly easy to add if you like to have a go at it. Have a look at the function [setStructuredQuery](https://github.com/twain47/Nominatim/blob/master/lib/Geocode.php#L349). That's the main point to change.
