### ISSUE TITLE
Missing or Incorrect Hwy name in an area

### ISSUE THREAD

**Issue by Cheryl30523** [twain47/Nominatim#606]
The area between the intersection of Willingham Ave and (US 441 GA 15 & GA 105) up to the merge onto (US 23 & GA 365) is known as Hwy 441 Bypass, Baldwin GA 30511

All the mapping services send our customers over 10 miles south on Old 441.  Can this be corrected?

**Comment by lonvia** [comment]
This is an issue with OpenStreetMap data, not so much with the search engine. So this is the wrong place to report. You can add a note on the map: go to http://osm.org, zoom to the place in question and set a note (the speech bubble button to the right). Or even better, you can fix the name of the road yourself, OSM is freely editable by everybody.
