### ISSUE TITLE
Installation failed "Postgresql server package not found" -- but found version "9.4.9"

### ISSUE THREAD

**Issue by prkothan** [twain47/Nominatim#608]
Hi 

Installation failed with following error.  Please note in the same box OSM server is running properly.

-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.4.9") 
CMake Error at CMakeLists.txt:52 (message):
  Postgresql server package not found.

Regards,
Prasanna K Ram

**Comment by lonvia** [comment]
As pointed out by the message, you need to install the postgresql *server* dev package. On Ubunutu/Debian: `apt-get install postgresql-server-dev-9.4`.

**Comment by olearytd** [comment]
has anyone had this issue with Centos 7.3?  I can only get nominatim to build with cmake if I install the epel postgresql packages (v9.2) - which is very outdated.  If I build it this way the setup logs initialized and ingesting data gives a warning about the outdated version and disabled some api tools.

I can install postgresql-9.3 or 9.5, etc via pgdg rpm but when I try to run cmake the server package isn't found.

-- Found PostgreSQL: /usr/pgsql-9.3/lib (found version "9.3.16") 
-- PostgreSQL include dirs: /usr/pgsql-9.3/include;/usr/include/
-- PostgreSQL library dirs: /usr/pgsql-9.3/lib
-- PostgreSQL libraries:    pq
-- Using osmosis at /usr/local/osmosis/package/bin/osmosis
CMake Error at CMakeLists.txt:61 (message):
  Postgresql server package not found.


`sudo yum list postgres*`
```
postgresql93.x86_64                                                           9.3.16-1PGDG.rhel7                                            @pgdg93  
postgresql93-contrib.x86_64                                                   9.3.16-1PGDG.rhel7                                            @pgdg93  
postgresql93-devel.x86_64                                                     9.3.16-1PGDG.rhel7                                            @pgdg93  
postgresql93-docs.x86_64                                                      9.3.16-1PGDG.rhel7                                            @pgdg93  
postgresql93-libs.x86_64                                                      9.3.16-1PGDG.rhel7                                            @pgdg93  
postgresql93-server.x86_64                                                    9.3.16-1PGDG.rhel7                                            @pgdg93  
```

**Comment by mtmail** [comment]
(It's a bit risky to add a new issue as comment to one that got closed a month ago)
This just came in may be related https://github.com/twain47/Nominatim/pull/644/commits

**Comment by mtmail** [comment]
The Nominatim cmake installation looks for the program `pg_config`. If
```
pg_config --version
```
doesn't return `PostgreSQL 9.6.2` or similar, then add `/usr/pgsql-9.6/bin` to your `$PATH` environment (e.g. in the `~/.bash_profile` file and then re-login).

I upgraded to 9.6 and `yum` installed it into `/usr/pgsql-9.6`. I had to change the `$PATH` and `export PostgreSQL_ROOT=/usr/pgsql-9.6/` to get cmake to complete. I hope that helps with your 9.5 upgrade as well.

**Comment by olearytd** [comment]
awesome, I'll try that out @mtmail thanks for the response :+1:

**Comment by casaulenbo** [comment]
hi @mtmail 

After i upgrade postgres 9.4 to postgres 9.6 by command below, rebuild Nominatim failed.
`yum install postgresql96-server postgresql96-contrib postgresql96-devel postgis24_96-devel postgis24_96-utils `

I already setting /usr/pgsql-9.6/bin to PATH but there is no luck.
(i can execute pg_config at command line)
=============
[nominatim@localhost build]$ cmake $USERHOME/Nominatim-3.2.0
-- Building osm2pgsql 0.96.0
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
CMake Warning at /usr/share/cmake/Modules/FindPostgreSQL.cmake:109 (message):
  Couldn't determine PostgreSQL configuration.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:121 (fail_if)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:127 (run_pg_config)
  osm2pgsql/CMakeLists.txt:117 (find_package)

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY_DIRS
  PostgreSQL_INCLUDE_DIRS PostgreSQL_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:173 (find_package_handle_standard_args)
  osm2pgsql/CMakeLists.txt:117 (find_package)

-- Configuring incomplete, errors occurred!
See also "/srv/nominatim/build/CMakeFiles/CMakeOutput.log".
See also "/srv/nominatim/build/CMakeFiles/CMakeError.log".
=============

Do i miss something else?

**Comment by casaulenbo** [comment]
hi @mtmail 

After i remove completely postgres 9.4 and re-install postgres 9.6, i can compile Nominatim3.2.0.
`yum remove postgres\*
rm -rf /var/lib/pgsql
vi ~/.bash_profile
PATH=/usr/pgsql-9.6/bin/:$PATH:$HOME/.local/bin:$HOME/bin
`
I think, maybe i missed install below package
`yum install postgresql96-libs `

Hope this help someone.
Thank you and best regards,
