### ISSUE TITLE
The place:postcode tag

### ISSUE THREAD

**Issue by icemagno** [twain47/Nominatim#609]
Ref: https://help.openstreetmap.org/questions/53947/placepostcode-tag

Hi guys.
I need to know where the Nominatim Brazilian postal code came from and why are you using this strange tag `place:postcode` . 

http://wiki.openstreetmap.org/wiki/Key:postal_code

**Comment by lonvia** [comment]
It comes exactly from the object the map points you to in the details view: https://www.openstreetmap.org/way/202025903

Nominatim collects all addr:postcode tags and computes centroid points. This kind of centroid point is what you see. Unfortunately these points are static at the moment and can only be changed with a new import. For details on plans how to improve this see #403.

**Comment by icemagno** [comment]
Ok. And why `place:postcode` and not `addr:postcode` ?

**Comment by lonvia** [comment]
`place:postcode` is the internal name Nominatim uses for these centroid.
