### ISSUE TITLE
Nominatim Installation stucks

### ISSUE THREAD

**Issue by jwevaco** [twain47/Nominatim#611]
Hello guys,

Executing:
`/home/nominatim/Nominatim-2.5.1/utils/setup.php --osm-file /home/<user>/planet-latest.osm.pbf --all --osm2pgsql-cache 24000 2>&1 | tee setup.log`

I'm stuck more than 24hrs on step (tail setup.log):
```
Node-cache: cache=1024MB, maxblocks=131072*8192, allocation method=11
Mid: pgsql, scale=10000000 cache=1024
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/<user>/planet-latest.osm.pbf
Using PBF parser.
```

Any ideas?

kind regards

**Comment by mtmail** [comment]
After the line `Using PBF parser.` you should see something like
```
Processing: Node(130k 130.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(260k 260.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(390k 390.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
...
Processing: Node(3616415k 3287.7k/s) Way(378594k 76.81k/s) Relation(4599240 2127.31/s)
Processing: Node(3616415k 3287.7k/s) Way(378594k 76.81k/s) Relation(4599300 2127.34/s)
```
in your logfile. On my hardware with `--osm2pgsql-cache 34000` that step takes about 3 hours.

I'm surprised to see `Node-cache: cache=1024MB, max` in your output. With your command it should say `Node-cache: cache=24000MB`.

How much RAM does the machine have? Is it currently swapping memory to disc?

**Comment by jwevaco** [comment]
I tried the import with a small country (Luxembourg) first and there you can see the above "Processing..."
string in my logfile and the import was successfull.
It's a VM with 32 GB of RAM. Vsphere says its just using 2 to 4 GB RAM, and thats confusing me.
I let it run for at least 24 hours, but it stucks at the above step.

**Comment by lonvia** [comment]
As @mtmail said, the output of setup.log does not match the command line you were giving. Please check again that you are looking at the correct file. If the command line is in error and you are really using only 2GB of cache ram, then it is perfectly normal that a planet import takes that long.

**Comment by jwevaco** [comment]
Command was entered correct, there was just a typo above.
You can see the entered command and output here:
![command](https://cloud.githubusercontent.com/assets/25202186/22142652/5e2a144a-def7-11e6-99d5-e2b5d1882b09.PNG)
![output](https://cloud.githubusercontent.com/assets/25202186/22142651/5e23c0f4-def7-11e6-828d-767891440365.PNG)

**Comment by lonvia** [comment]
```
Mid: loading persistent node cache from /home/evanco/planet-latest.osm.pbf
```
That looks wrong. The node cache needs to be an empty file not your planet file. You very likely have just overwritten all data in the planet file. Fix the line about 'CONST_Osm2pgsql_Flatnode_File' in your local.php and try with a freshly downloaded planet.

**Comment by jwevaco** [comment]
Thanks!
Now it seems, that it's running correctly!
I'll close the issue, if it was imported successfully.
