### ISSUE TITLE
boundary=postal_code is not taken in to account

### ISSUE THREAD

**Issue by kurly1** [twain47/Nominatim#612]
A while ago when I was searching for addresses I recognized that I got wrong postal codes for some addresses.

Lately I did an own Nominatim installation for some address analysis. Now I was able to find the reason why Nominatim gifs wrong postal codes. It links an address to the nearest suburb and takes the postal code from there. In my special case there exist a boundary=postal_code polygon which specifies the exactly array. But this polygon just gets imported to the placex table but there is no place_id's which reverence to this record.

So I tried to remove the postal_code from the suburb node and imported the data again in nominatim. But the result did not change, the postal_code polygon boundary is still not reverenced by any record.

I think it would be a good idea to add those boundaries to the analysis that addresses get linked to this postal_code information and prefer this information since it should be more accurate than the information from a suburb node.

**Comment by lonvia** [comment]
Could you please given an example (the address you are searching for and the OSM id of the postcode boundary you expect to find).

**Comment by kurly1** [comment]
An example is the address Dorfmattweg 8, Ittigen or Burgerstrasse 14, Ittigen which are located in the postcode boundary 3063 osm_id=5511371.

**Comment by lonvia** [comment]
Thanks for the example. The matter is actually a bit more complicated. Have a look at the details page for Dorfmattweg 8: http://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=200611710
In the address list you can see that the postcode relation is actually taken into account, it's just grayed out. That means that other postcode information has taken precedence for the address. In this case, it's the 3063, which doesn't list an actual postcode object, and that means, there was postcode information on one of the OSM objects that makes up the address. If you go through the list, you'll find http://www.openstreetmap.org/node/31491332, which has a tag with the offending postcode.

So the actual problem for your examples is: what is Worblaufen doing in that address, given that it is not even in Ittingen. [There is already a restriction](https://github.com/twain47/Nominatim/blob/master/sql/functions.sql#L1680) in some cases that the address parts must be strictly hierarchical (lower administrative parts must be contained by higher ones). That doesn't effect suburbs like Worbhofen, though. It's probably time to enforce that for all areas.

**Comment by lonvia** [comment]
Turns out I was looking at the wrong relation. Worblaufen is a part of the administrative boundary of Ittingen. So this is actually a particularly bad case of #575 and #231, which unfortunately is not going to be fixed in the near future. The best advice in this case, is to add a boundary for Worblaufen and/or its postal code area and remove the post code from the suburb node.

Closing as the original problem is working fine (postcode areas are indexed) and the suburb issue is a duplicate.
