### ISSUE TITLE
Nominatim returns status 200 even if Postgresql doesn't works

### ISSUE THREAD

**Issue by martindolecek** [twain47/Nominatim#615]
If I stop Postgresql, Nominatim returns status 200 with connection error inside page. I would expect err 5xx.   

Problem is, that I have Nginx cache which stores 2xx responses and now I have broken responses in the cache.

Detail:
- OS Debian Jessie
- Nominatim 2.5.0
- Postgresql 9.4
- PHP - 5.6.29 (php5-fpm, php5-psql)
- Nginx 1.6.2

**Postgre works**:  GET /search.php?q=praha&format=json HTTP/1.1" **200** 5005 
**Postgre doesn't works**:  GET /search.php?q=praha&format=json HTTP/1.1" **200** 1811

in response page with status code 200:
`string(19) "pgsql://@/nominatim" object(DB_Error)#2 (8) { ["error_message_prefix"]=> string(0) "" ["mode"]=> int(1) ["level"]=> int(1024) ["code"]=> int(-24) ["message"]=> string(24) "DB Error: connect failed
...
...`

**Comment by lonvia** [comment]
This seems to be a misconfiguration in nginx. With Apache I get a 500 error code. I presume you have used the configuration snippet from `docs/Installation.md`? Unfortunately, my knowledge of nginx is pretty much zero. Maybe somebody else can help out?

**Comment by martindolecek** [comment]
Hmm, it seems to be a bug in PHP-FPM:  https://bugs.php.net/bug.php?id=50921   The error was reported five years ago :/

**Comment by lonvia** [comment]
If I read that bug report right then that only concerns errors that stop the script before anything was printed but Nominatim actually sends a full answer page (see [chksql() function](https://github.com/twain47/Nominatim/blob/master/lib/init-website.php#L13). Also, we use PHP-FPM together with Apache on the osm.org production servers and I see 500 errors there as well. It really must be some communication problem between nginx and PHP-FPM specifically.

**Comment by melvyn-sopacua** [comment]
Could you try this patch?

```diff
diff --git a/lib/init-website.php b/lib/init-website.php
index 967c6cc..1835501 100644
--- a/lib/init-website.php
+++ b/lib/init-website.php
@@ -14,8 +14,7 @@ function chksql($oSql, $sMsg = "Database request failed")
 {
     if (!PEAR::isError($oSql)) return $oSql;

-    header('HTTP/1.0 500 Internal Server Error');
-    header('Content-type: text/html; charset=utf-8');
+    header('Content-type: text/html; charset=utf-8', true, 500);

     $sSqlError = $oSql->getMessage();

```

**Comment by martindolecek** [comment]
Thx for patch. 

But unfortunately patch is for master branch version from git. I have installed Nominatim 2.5.0 with imported full planet (install steps from [wiki](http://wiki.openstreetmap.org/wiki/Nominatim/Installation#Downloading_Nominatim) ). 

If I just clone master from git and compile, then I got error, that psql does't contains some columns. I suppose that is because I imported psql with 2.5.0 Nominatim.

I'll try install and import planet from scratch, and inform You results.

**Comment by lonvia** [comment]
For Nominatim 2.5.0 the equivalent patch is:

```
+++ b/lib/lib.php
@@ -2,8 +2,7 @@
 
        function failInternalError($sError, $sSQL = false, $vDumpVar = false)
        {
-               header('HTTP/1.0 500 Internal Server Error');
-               header('Content-type: text/html; charset=utf-8');
+               header('Content-type: text/html; charset=utf-8', true, 500);
                echo "<html><body><h1>Internal Server Error</h1>";
                echo '<p>Nominatim has encountered an internal error while processing your request. This is most likely because of a bug in the software.</p>';
                echo "<p><b>Details:</b> ".$sError,"</p>";
```

**Comment by martindolecek** [comment]
hmm, not works. I also tryed add fastcgi_next_upstream to nginx.

But something is strange:
- postgre **running**: GET /status.php    > browser got **status 200**   
- postgre **stopped**: GET /status.php   > browser got **status 500**

So, if /status.php handle errors correctly, why not search.php?

With patch and fastcgi_next_upstream  I got status 200 with db conn error in the body.

**Comment by lonvia** [comment]
Now I wonder if we have actually fixed something on the master branch.

**Comment by melvyn-sopacua** [comment]
Ugh, got it.
getDb(), doesn't handle the connection error and in `search.php` we don't check it. In `status.php` we do.

**Comment by lonvia** [comment]
Indeed, thanks looking that up. It has been fixed on master with the move to chksql(), so closing here.
