### ISSUE TITLE
Always use addr:street for Streetname if set

### ISSUE THREAD

**Issue by quelbs** [twain47/Nominatim#617]
Way [196855602](https://www.openstreetmap.org/way/196855602) which is Place [109232133](https://nominatim.openstreetmap.org/details.php?place_id=109232133) in Nominatim has addr:street=Hintere Luegeten but the assigned streetname in Nominatim is Energiepfad which is from a path next to the building. In my understanding addr:streetname should also be taken if there is no way in OSM with this name next to the address.

**Comment by lonvia** [comment]
Currently Nominatim needs a street with exactly the same name as in addr:street, to get the address correctly. I see that somebody has added a street 'Hintere Luegeten' by now. Unfortunately, Nominatim's update mechanism didn't catch the house in question as it was too far away. I've now updated all the houses around the Energiepfad which should fix that specific example.

For actually using addr:* tags in the address, see #148. Closing as duplicate.
