### ISSUE TITLE
relation Kuortane missing

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#619]
I can't find the relation Kuortane (http://nominatim.openstreetmap.org/search.php?q=Kuortane) on either OSM Nominatim or my own world-wide installation. Based on a regular export script it disappeared about a month ago. I checked the database and the relation is neither in the `place` or `placex` table. `select name from place where osm_type='R' and osm_id='2366532';`

The relation is http://www.openstreetmap.org/relation/2366532/history and got it's wikipedia link removed. At least that's the changeset comment, I don't seem see that in the changeset XML. The `admin_centre` node is http://www.openstreetmap.org/node/84435358 and got a wikidata tag added.

Did the change of wikipedia/wikidata tags influence which feature (relation, node) gets imported? I want to get an understanding if that's a data issue of one place or something broader to look into.

thanks!

**Comment by lonvia** [comment]
The relation has lost it's boundary=adminstrative tag and is therefore typeless for Nominatim. Adding the tag back should bring it back.
