### ISSUE TITLE
Reverce geocode take error

### ISSUE THREAD

**Issue by fangelion** [twain47/Nominatim#621]
When i do request for this [coordinates](http://nominatim.openstreetmap.org/reverse?zoom=18&lon=37.783646&addressdetails=1&format=json&lat=48.084419), i receive error, but nearest coordinates take normal results

**Comment by mtmail** [comment]
The road has no name: http://www.openstreetmap.org/way/373718711 (south to north) http://www.openstreetmap.org/way/232721378 (north to south).

If you add a name, similar to the nearby road http://www.openstreetmap.org/way/25292742 then Nominatim should find a result.

**Comment by fangelion** [comment]
ok, one "tag" no name, but we have "country", "country_code", "postcode", "village", but we get error

**Comment by mtmail** [comment]
The request contains `zoom=18`. 

```
zoom=[0-18]
        Level of detail required where 0 is country and 18 is house/building
```

That means Nominatim will only return small map features (e.g. buildings) and not a larger map features like a state or a country.

**Comment by lonvia** [comment]
It should still pick up the country at the very least. zoom is a maximum value.

**Comment by lonvia** [comment]
Suspiciously looks like a variant of #545. With `debug=1` I get:

```
array (size=3)
  'place_id' => string '97286288' (length=8)
  'type' => string 'interpolation' (length=13)
  'fraction' => string '1' (length=1)
```

**Comment by lonvia** [comment]
Fix is now live on nominatim.openstreetmap.org.
