### ISSUE TITLE
Incorrect search results when "name:en" tag is provided

### ISSUE THREAD

**Issue by zstadler** [twain47/Nominatim#623]
When looking for "[Kfar Shemuel](http://nominatim.openstreetmap.org/search.php?q=Kfar+Shemuel&polygon=1&viewbox=)", the result is [node 461613375](http://www.openstreetmap.org/node/461613375) - tagged with "name:en"="Kfar Chabad" rather than [node 278471104](http://www.openstreetmap.org/node/278471104) - tagged with "name:en"="Kfar Shemuel"

**Comment by lonvia** [comment]
This is a variant of issue #170.

https://www.openstreetmap.org/node/278471104 is linked to https://www.openstreetmap.org/way/93463884, so only the latter should actually appear as a search result. This one, however, still has the previous name of 'Kefar Chabad'. When the node was changed the name change wasn't picked up by the entry for the area. If you update the name on the way as well, the problem should resolve itself for your example.

Closing as duplicate.

**Comment by zstadler** [comment]
I'm confused about the explanation above.

1. [This Overpass-turbo query](http://overpass-turbo.eu/s/lIm) shows that [node 278471104](https://www.openstreetmap.org/node/278471104) is not part of any way or relation. What is the "link" between [node 278471104](https://www.openstreetmap.org/node/278471104) and [way 93463884](https://www.openstreetmap.org/way/93463884)?
2. [This OSM Deep Analysis table](http://osmlab.github.io/osm-deep-history/#/way/93463884) shows that [way 93463884](https://www.openstreetmap.org/way/93463884) never had the name 'Kefar Chabad'.
3. [This OSM Deep Analysis table](http://osmlab.github.io/osm-deep-history/#/node/278471104) shows that [node 278471104](https://www.openstreetmap.org/node/278471104) never had the name 'Kefar Chabad'.

**Comment by lonvia** [comment]
> This Overpass-turbo query shows that node 278471104 is not part of any way or relation. What is the "link" between node 278471104 and way 93463884?

That's done internally by Nominatim. If it finds a place node geographically inside a place area of the same place type, it connects the two to avoid returning duplicate results. The result of linking is that only the area (here: the way) remains in Nominatim's index and is searchable. Normally the data of the two items is combined, so you would be able to find the way under both names but that doesn't work if the name on the node is changed after the way has been edited. That's what happend here and that's what #170 is all about.

> This OSM Deep Analysis table shows that way 93463884 never had the name 'Kefar Chabad'.
> This OSM Deep Analysis table shows that node 278471104 never had the name 'Kefar Chabad'.

Sorry, I meant the previous name of 'Kefar Shemuel' (as opposed to new name 'Kfar Shemuel'). Note that Nominatim doesn't know they are transliterations for the same thing, so typing one won't find the other.

**Comment by zstadler** [comment]
I understand that:
- Something is broken in the way Nominatim propagates changes. 
- When node 278471104 was created on July 14 2008, it was the result of a "Kfar Shemuel" Nominatim search. If this changeset was missed by Nominatim, the result of a "Kfar Shemuel" Nominatim search was empty.
- After way 93463884 was added on January 5 2011 3:48 PM, by [changeset 6871839](http://openstreetmap.org/browse/changeset/6871839), it became the result of a "Kfar Shemuel" Nominatim search because both had "place"="village" tag and node 278471104 was within the area defined by way 93463884. If this changeset was missed by Nominatim, the result of a "Kfar Shemuel" Nominatim search would continue to be node 278471104.

Since all versions of way 93463884 had some name tag with "Kfar Shemuel" value, I would expect it to continue and be the result of a "Kfar Shemuel" Nominatim search, regardless of any changeset was missed by Nominatim.

My questions:
- Which changeset caused the search results for "Kfar Shemuel" to be anything but way 93463884, and why?
- [This OSM Deep Analysis table](http://osmlab.github.io/osm-deep-history/#/node/461613375) shows that [node 461613375](https://www.openstreetmap.org/node/461613375) never had any name tag with  "Kfar Shemuel" value. How could it ever been a valid search result for "Kfar Shemuel"?
