### ISSUE TITLE
Error during import : Permission denied

### ISSUE THREAD

**Issue by yogeshkumarbalu** [twain47/Nominatim#625]
nominatim@byk-ubuntu:~/Nominatim/build$ ./utils/setup.php --osm-file /home/ybalasubramanian/Documents/germany-latest.osm.pbf --all 2>&1 | tee setup.log
WARNING: resetting threads to 1
Create DB
Setup DB
Postgres version found: 9.5
CREATE EXTENSION
CREATE EXTENSION
Postgis version found: 2.2
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 250
CREATE INDEX
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 229
CREATE INDEX
CREATE INDEX
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 25477
CREATE INDEX
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
WARNING: external UK postcode table not found.
SET
SET
SET
SET
SET
SET
SET
SET
SET
CREATE TABLE
COPY 32387
CREATE TABLE
CREATE TYPE
Import
sh: 1: /srv/nominatim/Nominatim/build/osm2pgsql: Permission denied
ERROR: Error executing external command: /srv/nominatim/Nominatim/build/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 2676 -P 5432 -d nominatim /home/ybalasubramanian/Documents/germany-latest.osm.pbf
Error executing external command: /srv/nominatim/Nominatim/build/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 2676 -P 5432 -d nominatim /home/ybalasubramanian/Documents/germany-latest.osm.pbf

Above is the error I am getting when I try to import osm.pbf data into nominatim. I am running as the nominatim user as per the documentation. All the files inside the above folder has rights with nominatim user. I have no idea why the permission is denied

**Comment by mtmail** [comment]
Can user `nominatim` read the file `/home/ybalasubramanian/Documents/germany-latest.osm.pbf` ? What does `ls -la /home/ybalasubramanian/Documents/germany-latest.osm.pbf` report? I

Is the file `/srv/nominatim/Nominatim/build/osm2pgsql` executable? What does `ls -la /srv/nominatim/Nominatim/build/osm2pgsql` and `/srv/nominatim/Nominatim/build/osm2pgsql --version` report?

**Comment by yogeshkumarbalu** [comment]
All as you asked

1. ```
nominatim@byk-ubuntu:~/Nominatim/build$ ls -l /home/ybalasubramanian/Documents/germany-latest.osm.pbf 
-rw-rw-r-- 1 nominatim nominatim 3112121110 Feb  3 19:09 /home/ybalasubramanian/Documents/germany-latest.osm.pbf
```

2.```
 nominatim@byk-ubuntu:~/Nominatim/build$ ls -la /srv/nominatim/Nominatim/build/osm2pgsql/
total 88
drwxrwxr-x  5 nominatim nominatim  4096 Feb  6 13:45 .
drwxrwxr-x 11 nominatim nominatim  4096 Feb  6 13:55 ..
drwxrwxr-x 32 nominatim nominatim  4096 Feb  6 13:45 CMakeFiles
-rw-rw-r--  1 nominatim nominatim  2416 Feb  6 13:45 cmake_install.cmake
-rw-rw-r--  1 nominatim nominatim   706 Feb  6 13:45 config.h
-rw-rw-r--  1 nominatim nominatim   302 Feb  6 13:45 CTestTestfile.cmake
-rw-r--r--  1 nominatim nominatim  2667 Feb  6 13:45 DartConfiguration.tcl
-rw-rw-r--  1 nominatim nominatim 53129 Feb  6 13:45 Makefile
drwxrwxr-x  3 nominatim nominatim  4096 Feb  6 13:45 Testing
drwxrwxr-x  3 nominatim nominatim  4096 Feb  6 13:45 tests
```


3. ```
nominatim@byk-ubuntu:~/Nominatim/build$ ls -la /srv/nominatim/Nominatim/build/osm2pgsql --version
ls (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard M. Stallman and David MacKenzie.
```

**Comment by yogeshkumarbalu** [comment]
All as you asked

1.
```
nominatim@byk-ubuntu:~/Nominatim/build$ ls -l /home/ybalasubramanian/Documents/germany-latest.osm.pbf 
-rw-rw-r-- 1 nominatim nominatim 3112121110 Feb  3 19:09 /home/ybalasubramanian/Documents/germany-latest.osm.pbf
```


2.
 ```
nominatim@byk-ubuntu:~/Nominatim/build$ ls -la /srv/nominatim/Nominatim/build/osm2pgsql/
total 88
drwxrwxr-x  5 nominatim nominatim  4096 Feb  6 13:45 .
drwxrwxr-x 11 nominatim nominatim  4096 Feb  6 13:55 ..
drwxrwxr-x 32 nominatim nominatim  4096 Feb  6 13:45 CMakeFiles
-rw-rw-r--  1 nominatim nominatim  2416 Feb  6 13:45 cmake_install.cmake
-rw-rw-r--  1 nominatim nominatim   706 Feb  6 13:45 config.h
-rw-rw-r--  1 nominatim nominatim   302 Feb  6 13:45 CTestTestfile.cmake
-rw-r--r--  1 nominatim nominatim  2667 Feb  6 13:45 DartConfiguration.tcl
-rw-rw-r--  1 nominatim nominatim 53129 Feb  6 13:45 Makefile
drwxrwxr-x  3 nominatim nominatim  4096 Feb  6 13:45 Testing
drwxrwxr-x  3 nominatim nominatim  4096 Feb  6 13:45 tests
```

3. I don't know the command to check the version but as i hopped into config file of osm2pgsql it said 0.93. Hope that helps

**Comment by mtmail** [comment]
I think it's two issues.

1. In the directory `/srv/nominatim/Nominatim/build/osm2pgsql` there should be files `osm2pgsql` and `libosm2pgsql.a`. Run the `cmake` step again (bottom of page https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md) as user `nominatim` in the `/srv/nominatim/Nominatim/build/` directory.

2. `build/utils/setup.php` tries to find the executable file and uses the variable `CONST_Osm2pgsql_Binary`. That is defined in `build/settings/settings.php`. Make sure the variable points to the executable file, by default it's
```
@define('CONST_Osm2pgsql_Binary', CONST_InstallPath.'/osm2pgsql/osm2pgsql');
```

3. If all works then running this command as user `nominatim` in directory `/srv/nominatim/Nominatim/build/` will print "yes".
```
php -r'require "settings/settings.php"; print is_executable(CONST_Osm2pgsql_Binary) ? "yes" : "no";'
```

**Comment by yogeshkumarbalu** [comment]
I made cmake again with the command cmake /srv/nominatim/Nominatim inside the build directory. But I cannot see the osm2pgsql and libosm2pgsql.a inside the folder. It has the same files as I mentioned in the previous command.

2nd step i did what you suggested.

3rd step, the answer is yes for the command. Even then getting the same error (permission denied)

I downloaded the osm2pgsql separately from the repo because twain47/Nominatim has osm2pgsql from seperate repo.

**Comment by lonvia** [comment]
Run `make` again inthe build directory, it should report an error.

Do **not** use any other osm2pgsql than the one that comes with the Nominatim source unless you know exactly what you are doing.

**Comment by yogeshkumarbalu** [comment]
Thanks, as you told, I was not having the proper osm2pgsql. I fixed it and now the import started.

**Comment by jdvjdv82** [comment]
hi, 
i had the same problem on ubuntu 18.04
try fist create db nominatim via ./utils/setup.php ended with error

then "append" created db with data like this

`    /srv/nominatim/Nominatim/build/osm2pgsql/osm2pgsql -S /srv/nominatim/Nominatim/settings/import-full.style -lsc -O gazetteer --hstore --number-processes 1 -C 2676 -P 5432 -d nominatim /home/ybalasubramanian/Documents/germany-latest.osm.pbf`

in my case i have 2 version of osm2pgsql. one for OSM maps, second for nominatim on the same server. maybe that causes the problem. i did not know proper style until i added -verbose option and then used the syntax for data import directly without setup.php
