### ISSUE TITLE
How to geocode using nominatim with no webserver integration ?

### ISSUE THREAD

**Issue by yogeshkumarbalu** [twain47/Nominatim#627]
Is there help available in internet on how to geocode using nominatim php scripts ? I don't wanna install webserver and query(geocode) using http protocol.

**Comment by lonvia** [comment]
There are two ways to do that: 

 * if you are interested in search only, there is a script: `./utils/query.php` It comes with a small `--help` option to get you started
 * use php-cgi. This is not documented but what we do in out test suite. The [send_api_query() function](https://github.com/twain47/Nominatim/blob/master/test/bdd/steps/queries.py#L259) is a good place to start looking for an example.
