### ISSUE TITLE
US places got assigned calculated_country Haiti

### ISSUE THREAD

**Issue by mtmail** [twain47/Nominatim#631]
On Jan/16th the USA was for a short-time named Haiti. http://www.openstreetmap.org/changeset/45233706 reverted that error.

Still 1000s of places got assigned to Haiti. Depends if you run daily, hourly or minutely updates. Example:
http://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=466510461

The shortest query to check the affected places is probably
`select count(*) from placex where calculated_country_code='ht' and st_y(centroid) > 23);`
and re-index them.

**Comment by lonvia** [comment]
I've done that now for nominatim.osm.org. Reindexing should be finished in a couple of minutes.

**Comment by SrihariThalla** [comment]
@lonvia What is the index that has to be reindexed? How long did it for you?

Thanks!

**Comment by lonvia** [comment]
Just run the following SQL command on your database:

```
update placex set indexed_status = 2 where calculated_country_code='ht' and st_y(centroid) > 23
```

If you are running updates in the background, the reindexing will take place automatically. If you don't normally run updates, you need to run the following commands afterwards:

```
./utils/update.php --index
```

The SQL command should take a couple of minutes (needs to go sequentially through all data), the subsequent indexing was about 20min.
