### ISSUE TITLE
Internal Server Error and DB Error: extension not found

### ISSUE THREAD

**Issue by drosoulitis** [twain47/Nominatim#636]
Hello everyone,

I am trying to install a nominatim server on a Kali GNU/Linux Rolling (ID_LIKE=debian) version 2016.2
I have installed postgresql-9.6 with postgis-2.3.
Everything about the installation runs smoothly but for some reason i can't find the reason why i keep getting the DB " [DB Error: extension not found] ** pgsql://@/nominatim" error.
My php version is: PHP 7.0.15-1 and after a recent update my running service for the postgresql looks like: postgresql@9.6-main (I don't know if that's relevant).
My local.php file looks like this:

`<?php
   // Paths
   @define('CONST_Postgresql_Version', '9.6');
   @define('CONST_Postgis_Version', '2.3');
   @define('CONST_Website_BaseURL', 'http://192.168.55.44/nominatim/');`

(I have the same file in both build/ and build/settings/ dirs to be sure)

I made all the nominatim files with full read-write-execute access and the nominatim DB has all the users (www-data, postgres etc.).

I don't think that it has to do anything with privilleges because running the script manually (sudo -u www-data php /srv/nominatim/build/website/search.php) i get the output:

[run_search_from_user_php_script_excerpt.txt](https://github.com/twain47/Nominatim/files/785186/run_search_from_user_php_script_excerpt.txt)
********************************************************************************************************
`PHP Notice:  Undefined index: REQUEST_METHOD in /srv/nominatim/Nominatim/lib/init-website.php on line 98
PHP Notice:  Undefined index: REMOTE_ADDR in /srv/nominatim/Nominatim/lib/log.php on line 23
PHP Notice:  Undefined index: QUERY_STRING in /srv/nominatim/Nominatim/lib/log.php on line 24
<!DOCTYPE html>
<html lang="en">
<head>
    <title>OpenStreetMap Nominatim: Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="http://192.168.55.44/nominatim/" />
    <link href="nominatim.xml" rel="search" title="Nominatim Search" type="application/opensearchdescription+xml" />
    <link href="css/leaflet.css" rel="stylesheet" />
    <link href="css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/common.css" rel="stylesheet" type="text/css" />
    <link href="css/search.css" rel="stylesheet" type="text/css" />
</head>

<body id="search-page">

    <header class="container-fluid">
    <div class="row">
        <div class="col-xs-4">
            <div class="brand">
                <a href="http://192.168.55.44/nominatim/">
                <img alt="logo" src="images/osm_logo.120px.png" width="30" height="30"/>
                <h1>Nominatim</h1>
                </a>
            </div>
        </div>
        <div id="last-updated" class="col-xs-4 text-center">
                            Data last updated:
                <br>
                2016/07/10 23:51 GMT                    </div>
        <div class="col-xs-4 text-right">
            <div class="btn-group">
                <button class="dropdown-toggle btn btn-sm btn-default" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    About &amp; Help <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="http://wiki.openstreetmap.org/wiki/Nominatim" target="_blank">Documentation</a></li>
                    <li><a href="http://wiki.openstreetmap.org/wiki/Nominatim/FAQ" target="_blank">FAQ</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#" class="" data-toggle="modal" data-target="#report-modal">Report problem with results</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

<div class="modal fade" id="report-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Report a problem</h4>
            </div>
            <div class="modal-body">
                <p>
    Before reporting problems please read the <a target="_blank" href="http://wiki.openstreetmap.org/wiki/Nominatim">user documentation</a>
    and
    <a target="_blank" href="http://wiki.openstreetmap.org/wiki/Nominatim/FAQ">FAQ</a>.

    If your problem relates to the address of a particular search result please use the 'details' link
    to check how the address was generated before reporting a problem.
</p>
<p>
    Use <a target="_blank" href="https://github.com/twain47/nominatim/issues">Nominatim issues on github</a>
    to report problems.

</p>
<p>
    Please ensure that you include a full description of the problem, including the search
    query that you used, the problem with the result and, if the problem relates to missing data,
    the osm type (node, way, relation) and id of the item that is missing.
</p>
<p>
    Problems that contain enough detail are likely to get looked at before ones that require
    significant research.
</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

    <form class="form-inline" role="search" accept-charset="UTF-8" action="http://192.168.55.44/nominatim/search.php">
        <div class="form-group">
            <input id="q" name="q" type="text" class="form-control input-sm" placeholder="Search" value="" >
        </div>
        <div class="form-group search-button-group">
            <button type="submit" class="btn btn-primary btn-sm">Search</button>
                            
                <input type="hidden" value="1" name="polygon" />
                        <input type="hidden" name="viewbox" value="" />
            <div class="checkbox-inline">
                <input type="checkbox" id="use_viewbox" >
                <label for="use_viewbox">apply viewbox</label>
            </div>
        </div>
        <div class="search-type-link">
            <a id="switch-to-reverse" href="http://192.168.55.44/nominatim/reverse.php?format=html">reverse search</a>
        </div>
    </form>

    <div id="content">

        <div id="intro" class="sidebar">
            <h2>Welcome to Nominatim</h2>

<p>Nominatim is a search engine for <a href="http://www.openstreetmap.org">OpenStreetMap</a>
data. This is the debugging interface. You may search for a name or address(forward search) or
look up data by its geographic coordinate(reverse search). Each result comes with a
link to a details page where you can inspect what data about the object is saved in
the database and investigate how the address of the object has been computed.</p>

For more information visit the <a href="http://wiki.openstreetmap.org/wiki/Nominatim">Nominatim wiki page</a>.
        </div>

        <div id="map-wrapper">
            <div id="map-position">
                <div id="map-position-inner"></div>
                <div id="map-position-close"><a href="#">hide</a></div>
            </div>
            <div id="map"></div>
        </div>

    </div> 

    <script type="text/javascript">
    var nominatim_map_init = {
    "zoom": 2,
    "lat": 20,
    "lon": 0,
    "tile_url": "http:\/\/{s}.tile.osm.org\/{z}\/{x}\/{y}.png",
    "tile_attribution": ""
};var nominatim_results = [];    </script>
    <footer>
    <p class="disclaimer">
        Addresses and postcodes are approximate
    </p>
    <p class="copyright">
        &copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors
    </p>
</footer>

<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/leaflet.min.js"></script>
<script src="js/leaflet-omnivore.min.js"></script>
<script src="js/nominatim-ui.js"></script>

</body>
</html>

********************************************************************************************************

But giving a url: "http://192.168.55.44/nominatim/?debug=1" I get an Internal Server Error in my page:

[page_output_debugging.txt](https://github.com/twain47/Nominatim/files/785189/page_output_debugging.txt)

********************************************************************************************************
Internal Server Error

Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.

Message: Failed to establish database connection

SQL Error: DB Error: extension not found

Details:

object(DB_Error)#2 (8) {
  ["error_message_prefix"]=>
  string(0) ""
  ["mode"]=>
  int(1)
  ["level"]=>
  int(1024)
  ["code"]=>
  int(-25)
  ["message"]=>
  string(29) "DB Error: extension not found"
  ["userinfo"]=>
  string(55) " [DB Error: extension not found] ** pgsql://@/nominatim"
  ["backtrace"]=>
  array(10) {
    [0]=>
    array(6) {
      ["file"]=>
      string(21) "/usr/share/php/DB.php"
      ["line"]=>
      int(967)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(10) "PEAR_Error"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        string(29) "DB Error: extension not found"
        [1]=>
        int(-25)
        [2]=>
        int(1)
        [3]=>
        int(1024)
        [4]=>
        string(32) " [DB Error: extension not found]"
      }
    }
    [1]=>
    array(7) {
      ["file"]=>
      string(23) "/usr/share/php/PEAR.php"
      ["line"]=>
      int(575)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(8) "DB_Error"
      ["object"]=>
      *RECURSION*
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        int(-25)
        [1]=>
        int(1)
        [2]=>
        int(1024)
        [3]=>
        string(32) " [DB Error: extension not found]"
      }
    }
    [2]=>
    array(5) {
      ["function"]=>
      string(11) "_raiseError"
      ["class"]=>
      string(4) "PEAR"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        NULL
        ["dsn"]=>
        array(0) {
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(1)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(0) ""
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(8) {
        [0]=>
        object(DB_pgsql)#1 (28) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["features"]=>
          array(7) {
            ["limit"]=>
            string(5) "alter"
            ["new_link"]=>
            string(5) "4.3.0"
            ["numrows"]=>
            bool(true)
            ["pconnect"]=>
            bool(true)
            ["prepare"]=>
            bool(false)
            ["ssl"]=>
            bool(true)
            ["transactions"]=>
            bool(true)
          }
          ["errorcode_map"]=>
          array(0) {
          }
          ["connection"]=>
          NULL
          ["dsn"]=>
          array(0) {
          }
          ["autocommit"]=>
          bool(true)
          ["transaction_opcount"]=>
          int(0)
          ["affected"]=>
          int(0)
          ["row"]=>
          array(0) {
          }
          ["_num_rows"]=>
          array(0) {
          }
          ["fetchmode"]=>
          int(1)
          ["fetchmode_object_class"]=>
          string(8) "stdClass"
          ["was_connected"]=>
          NULL
          ["last_query"]=>
          string(0) ""
          ["options"]=>
          array(8) {
            ["result_buffering"]=>
            int(500)
            ["persistent"]=>
            bool(false)
            ["ssl"]=>
            bool(false)
            ["debug"]=>
            int(0)
            ["seqname_format"]=>
            string(6) "%s_seq"
            ["autofree"]=>
            bool(false)
            ["portability"]=>
            int(0)
            ["optimize"]=>
            string(11) "performance"
          }
          ["last_parameters"]=>
          array(0) {
          }
          ["prepare_tokens"]=>
          array(0) {
          }
          ["prepare_types"]=>
          array(0) {
          }
          ["prepared_queries"]=>
          array(0) {
          }
          ["_last_query_manip"]=>
          bool(false)
          ["_next_query_manip"]=>
          bool(false)
          ["_debug"]=>
          bool(false)
          ["_default_error_mode"]=>
          NULL
          ["_default_error_options"]=>
          NULL
          ["_default_error_handler"]=>
          string(0) ""
          ["_error_class"]=>
          string(8) "DB_Error"
          ["_expected_errors"]=>
          array(0) {
          }
        }
        [1]=>
        NULL
        [2]=>
        int(-25)
        [3]=>
        NULL
        [4]=>
        NULL
        [5]=>
        string(32) " [DB Error: extension not found]"
        [6]=>
        string(8) "DB_Error"
        [7]=>
        bool(true)
      }
    }
    [3]=>
    array(4) {
      ["file"]=>
      string(23) "/usr/share/php/PEAR.php"
      ["line"]=>
      int(224)
      ["function"]=>
      string(20) "call_user_func_array"
      ["args"]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          string(4) "PEAR"
          [1]=>
          string(11) "_raiseError"
        }
        [1]=>
        array(8) {
          [0]=>
          object(DB_pgsql)#1 (28) {
            ["phptype"]=>
            string(5) "pgsql"
            ["dbsyntax"]=>
            string(5) "pgsql"
            ["features"]=>
            array(7) {
              ["limit"]=>
              string(5) "alter"
              ["new_link"]=>
              string(5) "4.3.0"
              ["numrows"]=>
              bool(true)
              ["pconnect"]=>
              bool(true)
              ["prepare"]=>
              bool(false)
              ["ssl"]=>
              bool(true)
              ["transactions"]=>
              bool(true)
            }
            ["errorcode_map"]=>
            array(0) {
            }
            ["connection"]=>
            NULL
            ["dsn"]=>
            array(0) {
            }
            ["autocommit"]=>
            bool(true)
            ["transaction_opcount"]=>
            int(0)
            ["affected"]=>
            int(0)
            ["row"]=>
            array(0) {
            }
            ["_num_rows"]=>
            array(0) {
            }
            ["fetchmode"]=>
            int(1)
            ["fetchmode_object_class"]=>
            string(8) "stdClass"
            ["was_connected"]=>
            NULL
            ["last_query"]=>
            string(0) ""
            ["options"]=>
            array(8) {
              ["result_buffering"]=>
              int(500)
              ["persistent"]=>
              bool(false)
              ["ssl"]=>
              bool(false)
              ["debug"]=>
              int(0)
              ["seqname_format"]=>
              string(6) "%s_seq"
              ["autofree"]=>
              bool(false)
              ["portability"]=>
              int(0)
              ["optimize"]=>
              string(11) "performance"
            }
            ["last_parameters"]=>
            array(0) {
            }
            ["prepare_tokens"]=>
            array(0) {
            }
            ["prepare_types"]=>
            array(0) {
            }
            ["prepared_queries"]=>
            array(0) {
            }
            ["_last_query_manip"]=>
            bool(false)
            ["_next_query_manip"]=>
            bool(false)
            ["_debug"]=>
            bool(false)
            ["_default_error_mode"]=>
            NULL
            ["_default_error_options"]=>
            NULL
            ["_default_error_handler"]=>
            string(0) ""
            ["_error_class"]=>
            string(8) "DB_Error"
            ["_expected_errors"]=>
            array(0) {
            }
          }
          [1]=>
          NULL
          [2]=>
          int(-25)
          [3]=>
          NULL
          [4]=>
          NULL
          [5]=>
          string(32) " [DB Error: extension not found]"
          [6]=>
          string(8) "DB_Error"
          [7]=>
          bool(true)
        }
      }
    }
    [4]=>
    array(7) {
      ["file"]=>
      string(28) "/usr/share/php/DB/common.php"
      ["line"]=>
      int(1907)
      ["function"]=>
      string(6) "__call"
      ["class"]=>
      string(4) "PEAR"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        NULL
        ["dsn"]=>
        array(0) {
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(1)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(0) ""
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        string(10) "raiseError"
        [1]=>
        array(7) {
          [0]=>
          NULL
          [1]=>
          int(-25)
          [2]=>
          NULL
          [3]=>
          NULL
          [4]=>
          string(32) " [DB Error: extension not found]"
          [5]=>
          string(8) "DB_Error"
          [6]=>
          bool(true)
        }
      }
    }
    [5]=>
    array(7) {
      ["file"]=>
      string(28) "/usr/share/php/DB/common.php"
      ["line"]=>
      int(1907)
      ["function"]=>
      string(10) "raiseError"
      ["class"]=>
      string(4) "PEAR"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        NULL
        ["dsn"]=>
        array(0) {
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(1)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(0) ""
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(7) {
        [0]=>
        NULL
        [1]=>
        int(-25)
        [2]=>
        NULL
        [3]=>
        NULL
        [4]=>
        string(32) " [DB Error: extension not found]"
        [5]=>
        string(8) "DB_Error"
        [6]=>
        bool(true)
      }
    }
    [6]=>
    array(7) {
      ["file"]=>
      string(27) "/usr/share/php/DB/pgsql.php"
      ["line"]=>
      int(212)
      ["function"]=>
      string(10) "raiseError"
      ["class"]=>
      string(9) "DB_common"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        NULL
        ["dsn"]=>
        array(0) {
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(1)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(0) ""
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        int(-25)
      }
    }
    [7]=>
    array(7) {
      ["file"]=>
      string(21) "/usr/share/php/DB.php"
      ["line"]=>
      int(557)
      ["function"]=>
      string(7) "connect"
      ["class"]=>
      string(8) "DB_pgsql"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        NULL
        ["dsn"]=>
        array(0) {
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(1)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(0) ""
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        [1]=>
        bool(false)
      }
    }
    [8]=>
    array(6) {
      ["file"]=>
      string(35) "/srv/nominatim/Nominatim/lib/db.php"
      ["line"]=>
      int(10)
      ["function"]=>
      string(7) "connect"
      ["class"]=>
      string(2) "DB"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(2) {
        [0]=>
        string(19) "pgsql://@/nominatim"
        [1]=>
        bool(false)
      }
    }
    [9]=>
    array(4) {
      ["file"]=>
      string(39) "/srv/nominatim/build/website/search.php"
      ["line"]=>
      int(11)
      ["function"]=>
      string(5) "getDB"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["callback"]=>
  NULL
}`

********************************************************************************************************
I know that the installation and instructions are for Ubuntu OS but i think that the similarities are many, so I tried to make it happen.
I searched for all the open/closed issues, but i didn't find any one (even from the very similar ones) that solves exactly this one.
Sorry for the long post. It's just that i've been trying four days now to install it (beggining with the official nominatim and then with the git one) and i've got nothing.
I'm looking forward to hearing from you with any ideas and suggestions.
I wrote the rest of the analysis also in the following txt file because i couldn't write them all in the same box readable enough.
I apologize for the inconvenience but it's my first post on the GIT community. 

[nominatim_internal_server_and_DB_issue.txt](https://github.com/twain47/Nominatim/files/785197/nominatim_internal_server_and_DB_issue.txt)

**Comment by lonvia** [comment]
This is normally an issue with the PHP library for connecting to postgres. Make sure you have the equivalent packages for php-pgsql and PEAR::DB installed. I have seen issues where the two libraries could not find each other even when they were both installed. Uninstalling and reinstalling helped in that case.

**Comment by drosoulitis** [comment]
Thanks for the reply. Unfortunately i didn't manage to overcome this problem. I have:

Installed packages, channel pear.php.net:

Package           Version State
Archive_Tar       1.4.2   stable
Console_Getopt    1.4.1   stable
DB                1.9.2   stable
MDB2              2.5.0b5 beta
MDB2_Driver_mysql 1.5.0b4 beta
PEAR              1.10.1  stable
PEAR_Manpages     1.10.0  stable
Structures_Graph  1.1.1   stable
XML_Util          1.4.1   stable

I also have installed php-pgsql and php7.0-pgsql. I tried with uninstalling them again (along with the pear DB) but with no result. I also did purge to my old version postgresql-9.4 and upgraded the pear package.
I finally tried with changing the DB with MDB2 (in every php file) to see if it works but the results were worse (no output even by scripting it). I rollbacked everything to DB but with no improvement.
Is there any way to find out what is the actual name of the postgresql extension (.so) for the php7.0 so i can add them properly in the php.ini?
I noticed an error as i was searching the syslog:
sessionclean[4576]: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/msql.so' - /usr/lib/php/20151012/msql.so: cannot open shared object file: No such file or directory in Unknown on line 0
I work with php7.0 but i have also installed php5 on my system. I gave a:
update-alternatives --set php /usr/bin/php5 but also with no result.
What would you suggest that i do next?
Thanks in advance!!!

**Comment by melvyn-sopacua** [comment]
So you **don't** have the [Php extension pgsql](http://php.net/manual/en/book.pgsql.php).

**Comment by drosoulitis** [comment]
Finally problem solved.
Thank you all for your valuable inputs.
I had the pgsql extension installed (by php7.0-pgsql and php-pgsql), but it wasn't loading it.
The solution was to purge all php versions to get rid of any php5 remains on my server.
After that and installing everything only according to php7.0 the nominatim worked.
Again Thanks a lot both of you!!!
