### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Krychool** [twain47/Nominatim#637]
Error 500 while calling this address

http://nominatim.openstreetmap.org/search?format=json&q=[hotel]&limit=25&bounded=1&viewbox=-81.9459972%2C153.102731%2C118.0540028%2C-46.897269

It happens when I put in q parameter tag "hotel"

**Comment by lonvia** [comment]
Thanks for the report. That was an operational issue on nominatim.osm.org, which is now fixed.
