### ISSUE TITLE
admin_center not used if rank_address is different

### ISSUE THREAD

**Issue by kkoop** [twain47/Nominatim#639]
Areas that have a designated admin_center should get their centroid from this admin_center, which is handled in the update trigger of placex:

          FOR relMember IN select get_osm_rel_members(relation_members,ARRAY['admin_center','admin_centre']) as member LOOP
            -- [...]
              -- For an admin centre we also want a name match - still not perfect, for example 'new york, new york'
              -- But that can be fixed by explicitly setting the label in the data
              IF make_standard_name(NEW.name->'name') = make_standard_name(linkedPlacex.name->'name') 
                AND NEW.rank_address = linkedPlacex.rank_address
                THEN

                -- If we don't already have one use this as the centre point of the geometry
                IF NEW.centroid IS NULL THEN
                  NEW.centroid := coalesce(linkedPlacex.centroid,st_centroid(linkedPlacex.geometry));
                END IF;

The name as well as the address_rank of the are and the admin_center have to be equal for this to work. But I'm now facing several places where the ranks are not the same, e.g. [this boundary](http://138.201.140.9/nominatim/details.php?place_id=155892643) with [this center](http://138.201.140.9/nominatim/details.php?place_id=129366). If one follows the link to openstreetmap.org, the boundary has its center [at the expected location](http://www.openstreetmap.org/relation/2413629). 

Is there any good reason to compare the address rank? It seems that the relation between the boundary and the admin_center has been explicitly set, so it makes sense to assume that the admin_center is indeed the center. Otherwise I would propose to drop this requirement. I get better results when removing the comparison, but now I'm wondering if there is a good reason for it.

**Comment by lonvia** [comment]
This behaviour is intentional. `admin_centre` normally descibes the seat of government for the administrative entity in question (capital, main village in a municipal cooperation), so it normally is not the same as the relation and should be indexed separately. If you have a place node and a boundary relation that describe exactly the same entity use the `label` role.
