### ISSUE TITLE
Does nominatim work with filtered osm data ?

### ISSUE THREAD

**Issue by yogeshkumarbalu** [twain47/Nominatim#640]
My task is to geocode only the buildings. I don't need to geocode anything else like roads or highways or railways. So, if I filter the germany.osm data to have only key "**building**" through **osmfilter** and then connect it to nominatim -- will it convert and work ? or is there a way to filter, provided by default in nominatim?

**Comment by mtmail** [comment]
Nominatim doesn't import railways.

You should run the setup without any filters. Building in OSM might have address data, but many have just the housenumber and street (and then Nominatim doesn't know which city it belongs to), you'd also miss address nodes (e.g. a large building with multiple addresses will have those stored separately), address interpolation or restaurants (which might have an address without being marked as building).
