### ISSUE TITLE
What EOF means

### ISSUE THREAD

**Issue by wolfbgn** [twain47/Nominatim#641]
When I put in browser:
http://localhost/nominatim/reverse.php?format=json&lat=43&lon=28&zoom=18
I get this responce:
EOF
{"place_id":"100175","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"node","osm_id":"31058194","lat":"43.2166104","lon":"27.9017131","display_name":"Варна, Varna Region, 9000, България","address":{"city":"Варна","county":"Varna Region","postcode":"9000","country":"България","country_code":"bg"}}
I want to use Nominatim 2.5 for reverse geocoding with Traccar, but the Traccar server returns error:
WARN: Geocoding failed - Unexpected char 69 at (line no=1, column no=1, offset=0) - JsonParsingExc$
I think it is because of this `eof` in the begining of line.
Help please.

**Comment by lonvia** [comment]
The EOF most likely comes from your settings/local.php. Make sure there are no characters before the <?php header.

**Comment by wolfbgn** [comment]
Well, sir... You are a genius.
Thank you, thank you, thank you.
