### ISSUE TITLE
Nominatim acknowledgement text

### ISSUE THREAD

**Issue by stgeorges** [twain47/Nominatim#643]
Hello,
I a developer of project called Gismo. It's an open source and free [GIS](https://www.google.rs/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj_7Zu666TSAhWJA5oKHXKTBCIQFggYMAA&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FGeographic_information_system&usg=AFQjCNHBxxj_C_SKs9W-41ZnFa1mGhXjRw&bvm=bv.147448319,d.bGs) plugin for commercial [Rhino3d](http://www.rhino3d.com/) software. This is Gismo's main repository:
```https://github.com/stgeorges/gismo```

Yesterday, one of Gismo's developers added an option of using the Nominatim API to query latitude, longitude coordinates for a given address. This is the source code of that script:
```https://github.com/stgeorges/gismo/blob/master/src/Gismo_Address%20To%20Location.py```

Since then I checked [Nominatim wiki page](http://wiki.openstreetmap.org/wiki/Nominatim), and also [Usage policy page](https://operations.osmfoundation.org/policies/nominatim/), but I couldn't find an answer to my question. Just to be clear on the usage limits: I do not think the upper mentioned script will ever reach 1 request per second. It's more likely a couple of requests per day at most. Right now, there may be a couple of requests per week.

This is my issue, though: I would like to add a certain acknowledge text to Gismo's [license file](https://github.com/stgeorges/gismo/blob/master/LICENSE.md). Something similar to this:

> Gismo uses Nominatim service to query latitude, longitude data for the given address.
> 
> Nominatim service is used in "Address to Location" component.
> 
> Data obrained through Nominatim service is provided under the ODbL license:
> https://openstreetmap.org/copyright
> 
> Please refer to the following page for more information:
> http://nominatim.openstreetmap.org 

I was wondering whether or not, there is some precise text, which I need to follow, in order to give credit to Nominatim?

I would welcome any kind of reply.

**Comment by mtmail** [comment]
Thank you for being so pro-active when it comes to the license!

Nominatim usage itself doesn't require attribution, it's more or less just a tool to search OSM data (though nice if you mention the tool by name). The important part is the "data © OpenStreetMap contributors", listing the data license (ODbL) and link to https://openstreetmap.org/copyright, which I think you already do.

Looking at your code I have two comments:
- please set the `email` parameter (https://wiki.openstreetmap.org/wiki/Nominatim#Parameters). If you don't feel comfortable putting an email address into the source code you can also set it to the github URL.
- it's better to construct the full URL using a library. Concatenating strings causes trouble with URI-Escaping, spaces (' ' vs '+'), unicode. Python example:
http://docs.python-requests.org/en/master/
```python
import requests
url = "http://nominatim.openstreetmap.org/search"
data = {
    'format': ...,
    'limit': ...,
    ...
}
response = requests.get(url, params=data)
if (response.status_code == 200): ...
elif
   print "error requesting from: "+response.url # that's the full URL including parameters
```

**Comment by stgeorges** [comment]
Thank you for the detailed reply @mtmail !!
We'll do as you've told us.
And use the github link for the ```email``` parameter.
Once again, thank you for the help!
