### ISSUE TITLE
London relation is no longer returned

### ISSUE THREAD

**Issue by don-vip** [twain47/Nominatim#645]
Hi,
We just noticed that the London relation (https://www.openstreetmap.org/relation/65606) is no longer returned with this search: https://nominatim.openstreetmap.org/search?format=xml&q=London
Only the place node (https://www.openstreetmap.org/node/107775) is now returned.

This cause problems with JOSM as we need the relation areas results for the overpass API QL.

I tried to play with parameters "dedupe" and "limit" but can't find how to get the London relation area.

**Comment by don-vip** [comment]
OK found it, someone removed the "boundary=administrative" tag on the London relation:
https://www.openstreetmap.org/changeset/46415025
Sorry for the noise.

**Comment by mtmail** [comment]
@don-vip No worries. Thanks for reporting.
