### ISSUE TITLE
Egypt relation wrong

### ISSUE THREAD

**Issue by ricardogreis** [twain47/Nominatim#646]
Hi, 
When I search for Cairo in my Nominatim instalation, in Address, Egypt line appear without osm relation.
If I search for Egypt, details, show me only the big brother island.
  
So, I recently re-imported Africa from scratch (using geofabrik Africa continent file downloaded 14/02/2017)
following the default installation guide.
Updated all Africa following the default update guide with configuration
> baseUrl=http://download.geofabrik.de/africa-updates
> maxInterval = 40000

But still appear wrong. 
Any idea how to fix?

**Comment by woodpeck** [comment]
The extracts on the Geofabrik server can occasionally miss a small piece of a country boundary, which may lead to the whole polygon not being built in Nominatim. It appears that this was the case here. I have fixed the Egypt boundary on the Geofabrik server and it should be ok tomorrow.

**Comment by ricardogreis** [comment]
after night updates still wrong.

```
5580477;5466227;"R";"place";"city";15;"Cairo"
5577864;4103336;"R";"boundary";"administrative";4;"Cairo Governorate"
;;"";"place";"country";;"Egypt"
;;"";"place";"country_code";;""
```

**Comment by lonvia** [comment]
The addresses inside the country won't be updated automatically because the area is too large. If you search for Egypt itself, do you get the correct polygon now (details link: details.php?osmtype=R&osmid=1473947)?

**Comment by ricardogreis** [comment]
Yes. So, I will find/update addresses (region) by demand.
Thank you

**Comment by lonvia** [comment]
You can force an update of all of Egypt:

 1. Find the place ID of the Eqypt relation (the ID is in the URL of the details when you search for Egypt and follow the details link)
 2. Invalidate the country like this: `psql -d nominatim -c 'select place_force_update(<place id>)'` (replace database name and place id as needed)
 3. Reindex the country like this: `./utils/setup.php --index --index-noanalyse`

Be warned that this might take a while. If you are only interested in Egypt in the first place, consider starting from scratch with only the Eqypt extract. It will work now as well.
