### ISSUE TITLE
create-website error

### ISSUE THREAD

**Issue by MirkoMixy** [twain47/Nominatim#647]
Hi , I'm trying to install nominatim on Ubuntu 16.04.
I have problems at step when I need to do this:

`./utils/setup.php --create-website /var/www/nominatim/`

I'm receiving error:

```
setup.php: Unknown option '/var/www/nominatim'
Try `setup.php --help` for more information.
```

Any idea how to fix this?

**Comment by mtmail** [comment]
The instructions on https://wiki.openstreetmap.org/wiki/Nominatim/Installation are for the stable 2.5.1 release which you can download from http://www.nominatim.org/ That includes the `--create-website` step.

When you install the latest Nominatim version (master branch on github) check the instructions on https://github.com/twain47/Nominatim/blob/master/docs/Installation.md where that step is no longer needed.
