### ISSUE TITLE
import tiger

### ISSUE THREAD

**Issue by marco110** [twain47/Nominatim#651]
I try to import tiger data to database and I enter the command according to the document,but it doesn't work.
Please tell me what happened?
![capture](https://cloud.githubusercontent.com/assets/20534952/23498946/f3c1e860-ff64-11e6-9af3-fa2f9dddc2d8.PNG)

**Comment by mtmail** [comment]
The command expects a directory containing 1000s of files as parameter. I think you need to unzip the archive first.

**Comment by marco110** [comment]
Oh,thank you very much,I forgot it.
