### ISSUE TITLE
Add "name" field to reverse geocode output

### ISSUE THREAD

**Issue by stevevance** [twain47/Nominatim#72]
Currently the API returns "display_name" which is a concatenation of all the available address objects and the object's "name" field, if that is available. 

It would be useful for [http://bikechi.com/chicago](my app) if the API also returned the object's name. I want my app to show the name on a separate line, like so:

Name
Address
City, State

Instead of:

[name], Address, City, State

**Comment by lonvia** [comment]
Feature request now tracked in #304.
