### ISSUE TITLE
additional details not used by search result in search failure

### ISSUE THREAD

**Issue by matkoniecz** [twain47/Nominatim#82]
Compare: "bora-komorowskiego" and "bora-komorowskiego, car dealership"

the second one should result in displaying http://www.openstreetmap.org/#map=19/50.08503/19.97560 or at least fall back to "bora-komorowskiego" rather than fail completely

**Comment by lonvia** [comment]
This is a tricky problem because for a machine it is not obvious which terms of the search query can be left out without changing the meaning of the query.

**Comment by lonvia** [comment]
Feature also discussed with more details in #145.
